### ISSUE TITLE
Use Unicode scalar values instead of Unicode code points

### ISSUE THREAD

**Issue by Lyberta** [WebAssembly/spec#1000]
I've noticed that the spec does not allow surrogate code points in names which means the technical definition of `codepoint` is incorrect in terms of the Unicode standard.

[Unicode code point](https://www.unicode.org/glossary/index.html#code_point) is any value in the range [0, 10FFFF].
[Unicode scalar value](https://www.unicode.org/glossary/index.html#unicode_scalar_value) is any Unicode code point except high-surrogate and low-surrogate code points.

So please, rename `codepoint` to something like `scalar_value` or `unicode_scalar_value`.

**Comment by ericprud** [comment]
+1
I had thought that `code point` excluded surrogates. Tx for catching this.

For posterity's sake, all strings are UTF-8 so any instance of a (UTF-8-encoded) surrogate would represent a `scalar value` of U+10000 or higher encoded first as a UTF-16 surrogate pair and then algorithmically encoded as UTF-8. Martin Dürst made a nice picture of how UTF-8 excludes surrogates. I can't lay my hands on it but here's a [copy I made for another project](https://www.w3.org/2005/03/23-lex-U#validutf8). The orange "surrogates d800-d8ff would encode as ED A0 80-ED BF BF" illustrates a prohibited encoding of a surrogate pair.
