### ISSUE TITLE
Local Declarations Vector Syntax Issue

### ISSUE THREAD

**Issue by Galaxtone** [WebAssembly/spec#1008]
Found [here.](http://webassembly.github.io/spec/core/binary/modules.html#binary-local)

`locals` is said to be a compressed vector however it shows `t:valtype` rather than `(t:valtype)ⁿ` which mismatches against `vec(B)` definition.

Definition of `locals`
![locals](https://user-images.githubusercontent.com/22679778/56909093-89f89b80-6a75-11e9-921e-f83ee203a38c.png)
Definition of `vec(B)`
![vector](https://user-images.githubusercontent.com/22679778/56909180-b8767680-6a75-11e9-9046-8801b0aeab71.png)

I don't understand this and I think it might be a typo.

**Comment by rossberg** [comment]
`locals` decodes into a sequence of n locals of the same type t. A `func` in turn contains a vector of those, whose results get concatenated to a single AST vector.

**Comment by Galaxtone** [comment]
Ah, so `{n=3 t=i32, n=2 t=f32}` would become `{i32, i32, i32, f32, f32}`

**Comment by rossberg** [comment]
Yes.

**Comment by Galaxtone** [comment]
Ok thanks, I'm a developer trying to understand the whole spec, and that was last thing I had issues understanding, with that the whole spec makes sense.

**Comment by rossberg** [comment]
@Galaxtone, good to hear!
