### ISSUE TITLE
[spec] name section: duplicate subsections allowed

### ISSUE THREAD

**Issue by nomeata** [WebAssembly/spec#1010]
The [current spec for the `name` section](https://webassembly.github.io/spec/core/appendix/custom.html#name-section) seems to allow multiple subsections within the same `name` section.

This seems to be an oversight, given that the spec is clear that there is at most one `name` section, and that within each name map, keys have to be unique, so it seems odd that one would be allowed to have, say, multiple module name subsections, or multiple function name subsections with non-disjoint keys.

I suggest to add the sentence “Each kind of subsection should appear at most once” or something similar to that end to the spec. Or, if duplicate subsections are intended, clarify their semantics (first wins, or last wins, and how to merge name maps).

**Comment by rossberg** [comment]
Indeed, see #1012 for a fix that matches the design docs.
