### ISSUE TITLE
[js-api] @@toStringTag values

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#1023]
Associated values for the `@@toStringTag` well-known symbol were originally [added to the design repo here](https://github.com/WebAssembly/design/blob/master/JS.md#webassembly--tostringtag--property).

It seems we never added these to the js-api spec, though there is a [reference to `@@toStringTag` here](https://github.com/WebAssembly/spec/blob/master/document/js-api/index.bs#L73.). The last reference seems to be the initial check-in in #591.

Was this an accidental omission? @littledan, do you know?

**Comment by littledan** [comment]
These are defined by the WebIDL specification to be values like "WebAssembly.Memory". Was that the intention?

**Comment by binji** [comment]
Yes, that's the intention. It wasn't clear to me (and in https://bugs.chromium.org/p/v8/issues/detail?id=9265), but if this is otherwise well-known then there probably doesn't need to be any fix here.

**Comment by binji** [comment]
Hm, actually -- where is this defined? I see https://heycam.github.io/webidl/#ecmascript-binding, but it seems to require a "class string" definition.

**Comment by littledan** [comment]
> The class string of a platform object that implements one or more interfaces must be the qualified name of the primary interface of the platform object

**Comment by littledan** [comment]
There is, unfortunately, an open debate about how `@@toStringTag` should work. I like @domenic's PR at https://github.com/heycam/webidl/pull/357 , and it matches the old specification. I would personally suggest that folks stick with those semantics while we work things out on the WebIDL side.

**Comment by binji** [comment]
Ah, I see. Thanks! OK, I think we should close this then.
