### ISSUE TITLE
[js-api] ref to css:Number rather than tc39:Number

### ISSUE THREAD

**Issue by ericprud** [WebAssembly/spec#1026]
[Step 4.5 of the WebAssembly module instantiation algorithm](https://www.w3.org/TR/wasm-js-api/#ref-for-sec-ecmascript-data-types-and-values%E2%91%A0) references the CSS definition of Number. Should that be a reference [20.1.1The Number Constructor](https://tc39.github.io/ecma262/#sec-number-constructor)?

**Comment by binji** [comment]
Sounds like there is a similar issue for Object (see https://github.com/w3c/transitions/issues/137#issuecomment-496579132)
