### ISSUE TITLE
CompileError: AsyncCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 3c 21 44 4f @+0]

### ISSUE THREAD

**Issue by Divy123** [WebAssembly/spec#1031]
I am running my unit tests with tape in which the test is running after browserified. Now when I try running the tests which include my wasm code compiled with web assembly explorer, it shows me this error.

The file is a wasm file and not a wat file.

Please help me with this.

Also noting that the code works in chrome.

**Comment by rossberg** [comment]
Those bytes are "<!DO" in ASCII, so probably you are trying to load an HTML document.

Anyway, this repo is for the Wasm spec and related issues. I suggest asking your question (with a bit more context) on StackOverflow.

**Comment by Divy123** [comment]
@rossberg can you please elaborate upon this?

> Those bytes are "<!DO" in ASCII, so probably you are trying to load an HTML document.

**Comment by rossberg** [comment]
The bytes 3c 21 44 4f are the string "<!DO". The error message says that they occur in place of the Wasm "magic word", which should be the first 4 bytes of a valid Wasm module.

**Comment by Divy123** [comment]
Any possible solution to it?
What can be the cause? I would be really grateful if you can help me with this.

Thanks a ton!!

**Comment by Pauan** [comment]
What's most likely happening is that when you try to load the `.wasm` file (using `fetch` or whatever), the file path is wrong, or the `.wasm` file doesn't exist on the server, so the server returns a 404 page instead (which is an `.html` file).

So make sure that your server is configured correctly, that the `.wasm` file exists on the server, that the file path you are loading is correct, and that you have the right permissions and MIME type setup for the `.wasm` file (the `.wasm` file must be served with the MIME `application/wasm`).

If you're still running into problems, you should ask on [StackOverflow](https://stackoverflow.com/), not here.

**Comment by Divy123** [comment]
Thanks @Pauan , this is something I can proceed with.

**Comment by benbatya** [comment]
Check your webserver's redirect filter... That worked for me

**Comment by nupur711** [comment]
Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0) getting this error. It shows that .wasm file is loaded as a html file. If any can help me with the same to know ho to use wasm with nodejs project.
