### ISSUE TITLE
How to reconcile imported table with table section?

### ISSUE THREAD

**Issue by RyanLamansky** [WebAssembly/spec#1038]
If an assembly requests a table import, but also has a table section internally, is this an error condition or are they combined in some way?

**Comment by rossberg** [comment]
It works the same way as with functions or globals: the imported tables come first in the index space, then the internal definitions.

**Comment by RyanLamansky** [comment]
But with 0 being the only legal table index, does that mean the extra table is inaccessible?

**Comment by rossberg** [comment]
Sorry, I misinterpreted your question, and thought you were talking about the multi table extension.

But nevertheless, the answer is yes: in the MVP, there is simply a check that 0 is the maximum resulting table index.

**Comment by RyanLamansky** [comment]
Thanks; I'm not deeply involved in the spec development so it didn't (initially) occur to me that multiple tables may be supported in upcoming releases, thus making my question unclear 🙄

So, for the MVP runtime I'm building, I'll accept multiple function tables but only the first will be usable.
