### ISSUE TITLE
wasm link error

### ISSUE THREAD

**Issue by OrenGitHub** [WebAssembly/spec#1039]
Hi, I'm trying to run a simple wasm file like described [in this SO post].(https://stackoverflow.com/questions/56824163/wasm-link-failure-with-clang8-compilation)

I compiled the following C file with `clang8`:

    $ cat main.c
    #include <stdio.h>
    int main(int argc, char **argv)
    {
        int x=-724;
        if (x*x > 2*2) { x++; }
        printf("%d\n",x);
    
        return x;
    }

Then I tried interpreting it with `wasm main.wasm` but I get:

    link failure: unknown import "env"."__linear_memory"

**Comment by rossberg** [comment]
Emscripten bundles the Wasm binary with some JS glue code that provides these imports. Naturally, the spec interpreter does not know anything about that. As it stands, you are more or less on your own when using Emscripten outside the JS/Web platform.

**Comment by OrenGitHub** [comment]
@rossberg thanks, I did that and indeed with `emcc` I can have a functional `*.html` file that invokes my compiled `*.wasm` file. However, that involved 1300 lines in the `html` file and `2517` lines in the `js` file.
You're saying this is my best option?

**Comment by rossberg** [comment]
Yes, or you'd have to emulate whatever the JS runtime glue code does if you wanted to take the Wasm produced by Emscripten to some non-Web environment. I don't think there currently is a batteries-included way to do that.

**Comment by OrenGitHub** [comment]
OK great, thanks again!
