### ISSUE TITLE
Confused about text format

### ISSUE THREAD

**Issue by ljulliar** [WebAssembly/spec#1042]
I started writing some wasm code (well actually WAT code) and I'm confused as to what the correct syntax is like I'm seeing wat sample using get_local although the WASM 1.0 spec says local.get. Same for set_local. I have noticed other discrepancies too here and thare

Is it that the WAT samples I'm looking at are outdated or is it that the various WAT -> WASM compilers available right now are not yet compliant with the [WASM 1.0 specification](http://webassembly.github.io/spec/core/intro/index.html) ?

Side question: is there a forum for SW development in WASM somewhere ?

Thank you everyone ! (and congrats for making WASM. It's a great initiative)

**Comment by rossberg** [comment]
Yes, there was a change in naming scheme from `get_local` to `local.get` -- and [other renamings](https://github.com/WebAssembly/spec/issues/884#issuecomment-426433329) -- late in the game, so many sources might still use the old syntax.

**Comment by ljulliar** [comment]
Thank you for that. And for another quick question about text format again. When writing wat code am I supposed to use the S expression style like

   (i32.add
    (get_local $1)
    (i32.const 5)
   )

or the stack-based postfix style :
local.get $1
i32.const 5
i32.add

Thanks!

**Comment by rossberg** [comment]
You use the style you prefer. ;)

**Comment by ljulliar** [comment]
Ah nice!
Except for the block / loop instructions where you have to use the S-expression style anyway, right ?

**Comment by binji** [comment]
No, there are different formats for those too:

```wasm
;; "flat" format
block
  nop
  i32.const 1
  i32.const 2
  i32.add
  drop
end

;; sexpr format
(block
  (nop)
  (drop
    (i32.add (i32.const 1) (i32.const 2)))
)
```

Same with `if` and `loop` too. `if` has a bit more syntax though:

```wasm
;; flat format
i32.const 1 ;; condition
if
  nop
else
  nop
end

;; sexpr format
(if
  (i32.const 1)  ;; condition
  (nop)
  (nop)
)

;; alternate sexpr format
(if
  (i32.const 1)
  (then (nop))
  (else (nop))
)
``` 

These all produce identical binary output.

**Comment by rossberg** [comment]
@binji:
> ```
> ;; sexpr format
> (if
>   (i32.const 1)  ;; condition
>   (nop)
>   (nop)
> )
> ```

Actually, we dropped this short form on the way to standardisation.

**Comment by binji** [comment]
Interesting, I must have missed that change. :)

**Comment by ljulliar** [comment]
@binji Thanks a lot. That was very helpful. Reading the WASM Standard it isn't obvious that you can use so many different style writing WAT code.

**Comment by rossberg** [comment]
This has been answered.
