### ISSUE TITLE
winmake wast.js => no output of wast.js

### ISSUE THREAD

**Issue by CarpeDiemKopi** [WebAssembly/spec#1051]
How can I get a wast.js under windows? 
I installed `bucklescript` in the interpreter directory with `npm install --save-dev bs-platform`.

**Comment by rossberg** [comment]
Sorry, to get wasm.js you'll need `make`, there is no special support for building that without it.

**Comment by CarpeDiemKopi** [comment]
I have made my first installation with [OCPWin, an OCaml distribution for Windows](https://www.typerex.org/ocpwin.html). 
You can choose between OCaml version 4.01.1 and 4.02.1. 

Here [Installing the BuckleScript OCaml compiler](https://github.com/BuckleScript/bucklescript/wiki/Installation) I found out that I need version **4.02.3** for BuckleScript.
 
### I did a little research and will try as follows:

1. [How to install OCaml and Opam in Windows 10 using Windows Subsystem for Linux (WSL)](https://stackoverflow.com/a/46414810/8373141)
2. [`make` in windows bash (WSL)](https://stackoverflow.com/a/54133058/8373141)

**Comment by bobzhang** [comment]
hi @CarpeDiemKopi on Windows, you can just run `npm i -g bs-platform`
