### ISSUE TITLE
Spec interpreter has strange behavior on test/core for alignments and floats

### ISSUE THREAD

**Issue by AntonXue** [WebAssembly/spec#1054]
Hello,

I noticed that it's possible to set up an adversarial `input.wast` and run

  `wasm -i input.wast -o output.wast`

such that `wasm input.wast` and `wasm output.wast` behave differently. In fact, there are several files within `test/core` that suffice to cause this issue. This concerns the latest commit as of writing: [ace189a8f906f4f0760656a2aa53b6dc7046e771](https://github.com/WebAssembly/spec/commit/ace189a8f906f4f0760656a2aa53b6dc7046e771), though it also shows up as far back as May 30 2019 on commit [41747bead1b92fb7d82dea19647dcccbaa6100c6](https://github.com/WebAssembly/spec/commit/41747bead1b92fb7d82dea19647dcccbaa6100c6).

For replication, starting from the `spec` directory:

1. `cd interpreter`
2. `make` (I used OCaml 4.07.1)
3. `./wasm -i ../test/core/align.wast -o ~/Desktop/hello.wast`
4. Observe that `./wasm ../test/core/align.wast` has no output
5. However `./wasm ~/Desktop/hello.wast` errors with `/home/celery/Desktop/hello.wast:408.1-415.2: assertion failure: expected validation error`

The files affected include:

`test/core/align.wast`
`test/core/float_literal.wast`
`test/core/float_exprs.wast`
`test/core/f64.wast`
`test/core/float_misc.wast`
`test/core/conversions.wast`

**Comment by rossberg** [comment]
Thanks for reporting. There were indeed two issues with the pretty printer: a bug with using the alignment short form and the fact that float literals weren't printed with sufficient precision. Both fixed in #1057.
