### ISSUE TITLE
Import arbitrary objects as immutable globals

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/spec#1067]
At the moment the js-api specification says in https://webassembly.github.io/spec/js-api/index.html#read-the-imports that the only valid values for an imported global are either a `Number` or a `WebAssembly.Global`. I wanted to flag this limitation, because I could not find any reasoning behind it here in the spec repository or in the Mutable Globals repository. Feel free to close this issue if the limitation is intentional.

The reason why I was surprised by this limitation is because typically when values come from JavaScript, the specification just refers to the [`toWebAssemblyValue`](https://webassembly.github.io/spec/js-api/index.html#towebassemblyvalue) function, which eventually calls to the JavaScript `valueOf` function. This is done e.g. in the constructor of `WebAssembly.Global`. Why do we not just do the same for imported globals?

**Comment by rossberg** [comment]
This was to maintain future extensibility. In particular, we did that that in anticipation of imports of mutable globals, before they actually were added. Had we allowed arbitrary coercions already, adding the WA.Global class would have been a breaking change.

This is consistent with other import conversions, which also require a mathcing WA.Xyz object. (And we really only still allow plain numbers as global imports for backwards compatibility now.)

It is slightly different from func parameters, where conversion is guided by a specific target Wasm valtype and can select coercions based on that.
