### ISSUE TITLE
Documentation for name custom section is wrong

### ISSUE THREAD

**Issue by kg** [WebAssembly/spec#1068]
The documentation for the name custom section is wrong (http://webassembly.github.io/spec/core/appendix/custom.html#name-section). It says the map assigns function names to function indices, but the indices are not function indices. From looking at the table, it appears to begin with the names of all the imports, and possibly follow with the names of all the exports? So offsetting the indices by some unknown value is required to actually map names to functions.

**Comment by kg** [comment]
That makes sense, but where is that specified? I can't find this specified anywhere on the website and it doesn't make any sense for funcidx to not be a 0-based index into the function section.

**Comment by tlively** [comment]
See https://webassembly.github.io/spec/core/syntax/modules.html#indices.

> The index space for functions, tables, memories and globals includes respective imports declared in the same module. The indices of these imports precede the indices of other definitions in the same index space.
