### ISSUE TITLE
[spec] on the use of result type

### ISSUE THREAD

**Issue by Huxpro** [WebAssembly/spec#1071]
The use of `resulttype` in the current spec is somewhat contrived, inconsistent, and uncomfortable. It could occur in at least 3 forms:

1. it's written as the non-terminal explicitly, e.g. [Structure - control instr](http://webassembly.github.io/spec/core/syntax/instructions.html#control-instructions), 
2. it's written as the optional occurrence explicitly e.g. [Validation - control instr](http://webassembly.github.io/spec/core/valid/instructions.html#control-instructions)
3. it's implicitly used as a constraint on the star in the "Note". e..g. [Validation - function type](http://webassembly.github.io/spec/core/valid/types.html#function-types)

The coercion between them happens often and often happened implicitly as well.

This is also inconsistent with the PLDI formalization and reference interpreter implementation. I understood the fact that [multi-value proposal](https://github.com/WebAssembly/multi-value) is postponed. But could we formalize this _temporary_ constraint better?

One idea is to generalize all occurrence of this notion of the result type and only attach the constraint once and for all during the validation (keep the full generality of un-typed dynamics)?

**Comment by rossberg** [comment]
Yeah, the reason may be somewhat non-obvious, but these differences reflect what is expressible in the binary format, which has different representations of function types (which include n-ary results syntactically) and the resulttypes (which currently cannot). Hence it's a typing restriction on the former but a syntactic restriction on the latter.

The cause of this difference was the desire to compress the common case of block types in the binary format. Unfortunately, that ad-hoc representation remains ugly even with the multi-value extensions, where it is confined to a new [blocktype](https://webassembly.github.io/multi-value/core/syntax/instructions.html#syntax-blocktype), though.

The more uniform representation in the interpreter predates the ad-hoc block type encoding. I should perhaps have changed it.

The POPL paper abstracted away from the indirection through typeidx's to express function types, so could ignore this nuisance.
