### ISSUE TITLE
[question] about incompleteness and stack-polymorphic

### ISSUE THREAD

**Issue by Huxpro** [WebAssembly/spec#1078]
This question is merely a question, out of curiosity. Say,

```wat
(func $stkpoly (param) (result i32)
  i32.const 1
  block (result i32)
    i32.const 10
    i32.const 100
    br 0
    i32.add  ;; vs. i64.add
  end
  i32.add
``` 

Using `i64.add` here is indeed, _safe_, but could not type check.

This reminds me of type checking `if e i32 i64` where `e` is undecidable so we have to lose the completeness and perform a safe approximation...is this also the case here?

My first intuition is like, do we need to care about instructions after the `br`? To me the type safety of the stack's been ensured by "keeping only as many `valtype` as the arity of `blocktype` and unwinding anything else"?

My second thought is that "okay I am not sure how to write the typing rule for the content of `block` (or other structurals) then...how do you know there is a `br` if you don't get there"? ...so maybe unconstraining this is indeed as hard as the halting problem?

**Comment by rossberg** [comment]
See the [design rationale](https://github.com/WebAssembly/design/blob/master/Rationale.md#why-polymorphic-stack-typing-after-control-transfer) for some explanation. A simple typing algorithm is sketched in the [Appendix](http://webassembly.github.io/spec/core/appendix/algorithm.html) of the spec.

**Comment by Huxpro** [comment]
@rossberg Ah. I think "Allowing but not type-checking unreachable code would break decomposability and requires the spec to provide a syntactic definition of reachability" answered my question perfectly. Thanks!
