### ISSUE TITLE
[web-api] Restrict WebAssembly.Module to same origin

### ISSUE THREAD

**Issue by annevk** [WebAssembly/spec#1081]
As discussed and per the rationale at https://github.com/whatwg/html/issues/4920.

Once https://github.com/whatwg/html/pull/4940 lands this will be trivial to define. Mostly raising this in case there are concerns.

**Comment by KronicDeth** [comment]
Is this part of the blockers for re-enabling `SharedArrayBuffer` by default in Firefox?

**Comment by annevk** [comment]
Not really. This is mostly about making it easier in the future to reduce the scope of an agent cluster if we manage to get rid of `document.domain` somehow.

**Comment by annevk** [comment]
This isn't really needed. It seems the serialization/deserialization restrictions around `WebAssembly.Module` are mostly artificial.
