### ISSUE TITLE
Should "read the imports' check the type of Global objects?

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#1095]
https://webassembly.github.io/spec/js-api/#read-the-imports has

> 1. If externtype is of the form 𝗀𝗅𝗈𝖻𝖺𝗅 mut valtype,
>    1. If v is a Global instance,
>       1. Let globaladdr be v.[[Global]]

seemingly without checking `global_type(store, globaladdr)`. Should it?

**Comment by rossberg** [comment]
It doesn't need to -- as in the other cases of imports, the type is checked in module_instantiate. This case should probably have the same note as the others.

**Comment by Ms2ger** [comment]
Thanks for the point, agreed about the note. Might be worth writing a test as well.

**Comment by rossberg** [comment]
Or maybe there should just be a single note further down that applies to all cases, instead of repeating it for each.

Agreed about test.
