### ISSUE TITLE
Broken LaTex Rendering on Chrome

### ISSUE THREAD

**Issue by Huxpro** [WebAssembly/spec#1096]
It seems likes some latest update (either on spec or Chrome) has broken the rendering of the main spec (and multi-value)
e.g. see if it could reproduce on <https://webassembly.github.io/spec/core/exec/instructions.html#control-instructions> 

I tried with several browsers and found it seems to be a Chrome-exclusive problem: (Top Firefox. Left Chrome 78. Right Safari)
![Screen Shot 2019-11-01 at 5 32 14 AM](https://user-images.githubusercontent.com/5563315/68015662-065c7900-fc69-11e9-84b6-e6773aa8370a.png)

**Comment by rossberg** [comment]
That is odd. I can reproduce that on Chrome 78, including for the [main spec](https://webassembly.github.io/spec/core/exec/instructions.html#control-instructions). Headers and parts of formulas disappearing.

That page hasn't changed in a while, so I think this is a Chrome bug.

**Comment by binji** [comment]
I saw this before too, I think it was a mathjax bug: https://math.meta.stackexchange.com/questions/30842/mathjax-formulas-hidden-behind-text

IIRC, it worked properly if you change the MathJax renderer. However, I don't see the problem anymore.
