### ISSUE TITLE
is:issue is:open 

### ISSUE THREAD

**Issue by woolfiraq** [WebAssembly/spec#1106]

**Comment by woolfiraq** [comment]
is:issue is:open

**Comment by woolfiraq** [comment]
Hello World

**Comment by rossberg** [comment]
Spam

**Comment by ericprud** [comment]
@rossberg , i don't have privs for this, but an admin could add this user to https://github.com/organizations/WebAssembly/settings/user_blocks

**Comment by rossberg** [comment]
@ericprud, done. User was also starting to spam one of my non-Wasm repos.
