### ISSUE TITLE
interpreter: new release tag for use in opam package

### ISSUE THREAD

**Issue by tuncer** [WebAssembly/spec#1108]
Since the necessary OCaml fixes (Pervasives deprecation) are already in master, is it possible to tag a new release for use in https://opam.ocaml.org/packages/wasm/? Alternatively, is it okay to use a snapshot (e.g. 3e5fdc6b51ca2cde537bb8ecb1ba25c1ee366833) in the package recipe?

/cc @msprotz

**Comment by rossberg** [comment]
Done, I created a `v1.1` release tag for the interpreter.
