### ISSUE TITLE
[js‑api] Should methods be made non‑enumerable to match other ECMAScript built‑ins?

### ISSUE THREAD

**Issue by ExE-Boss** [WebAssembly/spec#1110]
Currently WebAssembly is specified using WebIDL, which makes all methods enumerable, which contrasts with ECMAScript classes and built‑ins, which only have enumerable data properties.

Since WebAssembly is meant to be an ECMAScript platform feature, I find it surprising that its methods are enumerable.

<https://github.com/heycam/webidl/pull/825> provides the `[NonEnumerableMethods]` extended attribute, which makes methods non‑enumerable by default, which matches what ECMAScript does.

**Comment by Ms2ger** [comment]
I see no value in making this change.

**Comment by xtuc** [comment]
@ExE-Boss do you have a specific use-case in mind? Otherwise I agree with @Ms2ger.
