### ISSUE TITLE
Runtime error unreachable, at one server without error, at other error occurs

### ISSUE THREAD

**Issue by michalmicpaw** [WebAssembly/spec#1112]
Hi.

I’m using tikzjax tikzjax.com to render math graphics. At one of my servers, it runs without any problems. But on other is gives me an error:

```
wasm://wasm/wasm-0037530e:34 Uncaught (in promise) RuntimeError: unreachable
    at wasm-function[33]:0x3369
    at wasm-function[35]:0x3b89
    at wasm-function[57]:0x53fd
    at wasm-function[34]:0x3403
    at wasm-function[160]:0x1a58d
    at wasm-function[161]:0x1a6a3
    at wasm-function[375]:0x6135d
    at wasm-function[382]:0x6e506
```

Here is site, where it works without problems: https://fillthecode.com/tikz/tikz.html  At localhost with xampp at Windows10 it also works.

The same code returns error at other server.

What it can be?

Thanks
Mike

**Comment by tlively** [comment]
Hi, this looks like a bug in either your project or in the tikzjax tool you are using. This repo is not the best place for this kind of help because your issue is not with the WebAssembly spec. I would reach out to the maintainer or community of tikzjax for help using their tool.
