### ISSUE TITLE
[spec] Can the name of a custom section cause a validation error

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/spec#1122]
As far as I understand the spec, the content of a custom section must not invalidate a WebAssembly module, see the note in https://webassembly.github.io/spec/core/binary/modules.html#custom-section:

> If an implementation interprets the contents of a custom section, then errors in that contents, or the placement of the section, must not invalidate the module.

In the same section it say that the name of the custom section is part of its content: 

> Their contents consist of a name further identifying the custom section, followed by an uninterpreted sequence of bytes for custom use.

Tests suggest though that an invalid custom section can cause validation errors, e.g. in custom.wast:
```
 68 (assert_malformed
 69   (module binary
 70     "\00asm" "\01\00\00\00"
 71     "\00\00"
 72   )
 73   "unexpected end"
 74 )
```
I wanted to ask now if custom sections can cause validation errors, and if so can we clarify the spec?

**Comment by binji** [comment]
Yeah, the word "contents" should be clarified. But it's clear from tests that the name is required to be valid. You can also see that in the `utf8-custom-section-id.wast` tests.

**Comment by rossberg** [comment]
Yeah, the wording is slightly off, see #1124 for an improvement. However, this is only a non-normative note, the actual grammar prescribes that a name is required and it being malformed would hence be a decoding error.

**Comment by gahaas** [comment]
Ah, okay. Thanks
