### ISSUE TITLE
Do we need [[Values]] in WebAssembly.Table instances?

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#1128]
It seems like `ToJSValue` will preserve identity anyway - certainly for MVP, and AFAICT also for reference-types.

**Comment by Ms2ger** [comment]
CC @littledan

**Comment by littledan** [comment]
Good point, I guess the "exported function cache" would be enough to preserve identity, and there's no need to have a secondary cache in [[Values]].
