### ISSUE TITLE
i32.const -1 violates the formal grammar

### ISSUE THREAD

**Issue by hexagonrecursion** [WebAssembly/spec#1132]
Call me pedantic, but [the definition of const](https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-numeric)

> instr ::= ... | i*nn*.const i*nn* | ...

implies 

> instr ::= ... | i32.const i32 | ...

and i32 as defined [here](https://webassembly.github.io/spec/core/syntax/values.html#integers)

> i*N* ::= u*N*
u*N* ::= 0 | 1 | ... | 2^*N* -1

implies

> i32 ::= 0 | 1 | ... | 2^32 -1

which *technically* means that the use of `i32.const -1` [in the definition of memory.grow](https://webassembly.github.io/spec/core/exec/instructions.html#exec-memory-grow) violates the formal grammar.

**Comment by rossberg** [comment]
Ha, you are absolutely correct, thanks for pointing out. See #1133.
