### ISSUE TITLE
[web-api] MIME type check in "compile a potential WebAssembly response" imprecise and ambiguous

### ISSUE THREAD

**Issue by domenic** [WebAssembly/spec#1138]
> 2. Let mimeType be the result of extracting a MIME type from response’s header list.
>
> 3. If mimeType is not `application/wasm`, reject returnValue with a TypeError and abort these substeps.

Here _mimeType_ is a [MIME type record](https://mimesniff.spec.whatwg.org/#mime-type), as returned by [extract a MIME type](https://fetch.spec.whatwg.org/#concept-header-extract-mime-type).

However in step 3 it's compared against a byte sequence.

It's unclear how to interpret the intended check here:

- Do you want to get the raw value of the `Content-Type` header and check that against the byte sequence? In this case `application/wasm;` would not match.
- Do you want to serialize the MIME type and compare it against the string (not byte sequence) "application/wasm"? In this case `application/wasm;` would match, as would <code>&nbsp;&nbsp;&nbsp;application/wasm&nbsp;&nbsp;&nbsp;</code>.
- Do you want to check against the MIME type's essence? In that case `application/wasm;foo=bar` would match.
- Note that for any case except getting the raw value of the Content-Type header, using the "extract a MIME type" algorithm means that multiple headers (or, equivalently, one header with comma-separate values) will be treated forgivingly. E.g. `application/javascript, application/wasm` and `application/wasm, unparseable` would both end up as `application/wasm`.

https://github.com/web-platform-tests/wpt/blob/master/wasm/webapi/contenttype.any.js seems to pick "check the raw value of the `Content-Type` header".

/cc @Surma @annevk

**Comment by annevk** [comment]
(Given scripts, style sheets, etc. I think this ought to be an essence check to match precedent.)

**Comment by surma** [comment]
There is a note underneath saying “Note: extra parameters are not allowed, including the empty `application/wasm;`”

**Comment by surma** [comment]
I do wonder why this spec is so strict about the header value.

**Comment by domenic** [comment]
Another consequence here is that if you compare raw values then `APPLICATION/WASM` should not match either.

**Comment by rossberg** [comment]
Has this been resolved?
