### ISSUE TITLE
Relax OCaml < 4.08.0 for wasm 1.0

### ISSUE THREAD

**Issue by fangyi-zhou** [WebAssembly/spec#1139]
https://opam.ocaml.org/packages/wasm/wasm.1.0/ shows wasm 1.0 requires OCaml < 4.08.0.
Is there a reason for this constraint? There are API changes in 1.1, and some packages depending are wasm 1.0 inherit this version constraint (See https://github.com/FStarLang/kremlin/issues/169), but I was able to build wasm 1.0 with OCaml 4.08.1 (after silencing deprecation warnings) and tests are passing.

**Comment by rossberg** [comment]
Good question, I don't know if there was a reason for the constraint. @msprotz would probably know. Happy to approve a PR to change it, if it works without.

**Comment by msprotz** [comment]
I don't remember why I requested an old version. Maybe because of the deprecation warnings? In any case it should be ok to lift the restriction. Thanks @fangyi-zhou !

**Comment by fangyi-zhou** [comment]
Yes there was some deprecation warnings.

I have the following patch to silence the warnings. I think one of the maintainers need to make a new-release to opam. 
```
From 3af9ff23f748016eb790d57f36cef25fe28b4ca3 Mon Sep 17 00:00:00 2001
From: Fangyi Zhou <fangyi.zhou15@imperial.ac.uk>
Date: Mon, 16 Mar 2020 14:45:41 +0000
Subject: [PATCH] Do not warn as error deprecations

---
 interpreter/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/interpreter/Makefile b/interpreter/Makefile
index 97b94f6e..4dd3d4de 100644
--- a/interpreter/Makefile
+++ b/interpreter/Makefile
@@ -19,7 +19,7 @@ WINMAKE =	winmake.bat

 DIRS =		util syntax binary text valid runtime exec script host main
 LIBS =		bigarray
-FLAGS = 	-cflags '-w +a-4-27-42-44-45 -warn-error +a'
+FLAGS = 	-cflags '-w +a-3-4-27-42-44-45 -warn-error +a'
 OCB =		ocamlbuild $(FLAGS) $(DIRS:%=-I %) $(LIBS:%=-libs %)
 JS =		# set to JS shell command to run JS tests

--
2.17.1
```

**Comment by rossberg** [comment]
I created a [PR](https://github.com/ocaml/opam-repository/pull/16039) against opam to remove the upper version limit. Hope I got the procedure right.

Can tackle the warning issue separately, I assume it's no blocker.

**Comment by fangyi-zhou** [comment]
Thanks!
