### ISSUE TITLE
[wasm-web-api-1] Why is the MIME type check so strict?

### ISSUE THREAD

**Issue by surma** [WebAssembly/spec#1140]
The spec for the streaming APIs currently only allow `application/wasm` as values for the `Content-Type` header for `Response` objects. 

Responses that are not CORS-same-origin are spec’d to get rejected anyway, so only same-origin responses are allowed. Same-origin responses can always be wrapped as follows:

```js
const resp = await fetch("/my.wasm");
const newResp = new Response(resp.body, {headers: {"Content-Type": "application/wasm"}});
const {instance} = await WebAssembly.instantiateStreaming(newResp);
```

I’m curious why the spec was writting in this strict manner and if it has been considered to relax these constraints.

**Comment by annevk** [comment]
A strict MIME type check allows for overloading in the future (with a different MIME type). It also encourages servers to be setup correctly so such client-side wrappers aren't needed.

I'm not entirely sure rejecting on unknown parameters is the way to go though, although it does keep the check rather straightforward.

**Comment by rossberg** [comment]
Closing as answered.
