### ISSUE TITLE
bikeshed failures on Travis CI

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#1146]
bikeshed was recently updated to require pygments 2.6, which only supports python3, see https://github.com/tabatkins/bikeshed/commit/b0f81be0f49f3387bd83ca49a89f4b4e359ff6ca

We should update to python3 as well.

**Comment by ngzhian** [comment]
I think we can close this with #1151

**Comment by binji** [comment]
Yep, looks like the errors are all gone now. Thanks!
