### ISSUE TITLE
Ambiguity around typeuse in text format

### ISSUE THREAD

**Issue by dszakallas** [WebAssembly/spec#1150]
I'm not sure I understand the [production rule for type uses](https://webassembly.github.io/spec/core/text/modules.html#type-uses) with inlined parameters and results in the text format correctly. Is it valid to use parameter/result abbreviations as specified in [6.4.3](https://webassembly.github.io/spec/core/text/types.html#abbreviations), i.e is this syntax valid?
```wast
(type $a)
(param) (param i32) (param $a i64) (param f32 f64) 
(result) (result $b i64)
```
Also, empty `param` and `result` forms are discarded, right? I.e the above syntax should refer to a `typedef` with the following type:
```
[i32 i64 f32 f64] -> [i64]
```

**Comment by rossberg** [comment]
Yes, that's right. See also the tests [here](https://github.com/WebAssembly/spec/blob/master/test/core/func.wast).

**Comment by dszakallas** [comment]
OK, thanks for clarifying.
