### ISSUE TITLE
reduction rule for labels is incorrectly referenced

### ISSUE THREAD

**Issue by korreman** [WebAssembly/spec#1152]
A note in the section on [administrative instructions](https://webassembly.github.io/spec/core/exec/runtime.html#administrative-instructions) describes the reduction rule for labels as:
`label_n {instr^n} val* end -> val^n`

However, in the [actual section](https://webassembly.github.io/spec/core/exec/instructions.html#exiting-with-label) for exiting `instr*`s, the reduction rule is written as:
`label_n {instr*} val^m end -> val^m`

For my own sanity, I hope the latter is correct.

**Comment by rossberg** [comment]
You are right, thank for spotting! Fixed in #1153.
