### ISSUE TITLE
[interpreter] Table size limit is too strict

### ISSUE THREAD

**Issue by acfoltzer** [WebAssembly/spec#1158]
The following module fails validation (`wasm -d test.wat`):
```wat
(module
  (table (;0;) 0xFFFFFFFF funcref))
```

The error message indicates that this _should_ be allowed, though:
```
test.wat:2.3-2.35: invalid module: table size must be at most 2^32
```

The largest table size that _does_ validate is `0x7FFFFFFF`, or `Int32.max_int`, so I suspect this is a signedness issue in the validator.

**Comment by rossberg** [comment]
Indeed, thanks! Fixed in #1160.
