### ISSUE TITLE
Why do we use KaTeX for 1-page HTML but MathJax for multi-page?

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/spec#1165]
Can we use KaTeX for both?

**Comment by binji** [comment]
The WG discussed this recently. The main reason we use KaTeX currently is to avoid having JS in the spec document. But to do so, we introduce a lot of complexity into the doc process. We think we can instead use the multi-page document (with MathJax) as a basis for the official TR document, and remove the single-page document. Then we can use the PDF as a JS-free version of the same document.

**Comment by ngzhian** [comment]
Got it. Another question: will it be a good idea to KaTeX-fy our multipage html docs? If we do that, build times are longer, but pages will load/be interactive faster!

**Comment by binji** [comment]
I think that would be nice, but if we do so, I'd like it to be incorporated in a more principled way, like having a Sphinx extension to do it (like the upstream MathJax one). Another concern is that KaTeX is not as fully-featured as MathJax, so we've often had to work-around limitations by replacing certain Latex constructs with near-equivalents (IIRC the python script does this in a few places). We may want to push upstream KaTeX to do this work before we do more work on our end.

I should also mention that part of the reason for this proposed change is to reduce the amount of work we'd have to do to produce a wasm spec document, so I'm a little hesitant to make more work for ourselves here :)

**Comment by ngzhian** [comment]
So that explains what a bunch of the `.replace` calls in the script `mathjax2katex.py` is about! Make sense. It will be interesting to create a Sphinx extension to do it too. I'll just file a bug with them to see if there is any interest. Feels like it will be useful (they already have an imgmath extension that does rendering of latex to img anyway, seems similar).

**Comment by ngzhian** [comment]
Btw, found https://github.com/hagenw/sphinxcontrib-katex, can play around with it a bit and see what works.

**Comment by rossberg** [comment]
What @binji said. Our KaTeX support mostly is a gross and brittle hack to create a single static doc. Various aspects of the resulting type setting are suboptimal, including wrong fonts, spacing, alignment etc.

**Comment by rossberg** [comment]
Closing, since we now use MathJax for the W3C draft as well.
