### ISSUE TITLE
Missing invalid / malformed specification: total number of module instance members

### ISSUE THREAD

**Issue by rianhunter** [WebAssembly/spec#1172]
I don't see anything in the spec that limits the total length of imports + module instances to be less than 2 ** 32. For instances, it's allowed for a module to import 1 global and define 2 ** 32 - 1 globals. This would result in the number of module instance globals being 2 ** 32, meaning one of those globals would not be accessible by global.get/global.set.

Is this intentional or am I missing a line?

**Comment by rossberg** [comment]
No deep reason behind this. It merely was ease of specification and the fact that it does not make any practical difference, since Appendix B (Implementation Limitations) applies anyway. Do you think it's important to impose that constraint?

**Comment by rianhunter** [comment]
In my experience it would guide an implementer's decision on what types should be used when representing a runtime module instance (when there are different options) but as you said ultimately the spec leaves room for the implementer to impose limits as they wish.

I brought it up because it seemed like a module that specified instances that couldn't be accessed was probably a mistake and, if so, the module generator would probably want to be made aware. If the team is aware and has already considered this feel free to close :)

**Comment by rossberg** [comment]
It's a fair question. I'm on the fence. Might be worth adding this for theoretical hygiene. Alternatively, I could add a note clarifying it.
