### ISSUE TITLE
Binary integer format

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/spec#1182]
Hi, the definition of `uN` in 5.2.2 does allow **only** one training zero, no zero**s** as written in the note down. That is correct, because if the zeroes are many, the second alternative of `uN` must be changed, to reflect it, but that is 'bad', because it will introduce ambiguity. For `sN` also.

**Comment by binji** [comment]
It's intended to allow multiple trailing zeros, for example these are all of the valid u32 encodings of 3:
```
0x03
0x83 0x00
0x83 0x80 0x00
0x83 0x80 0x80 0x00
0x83 0x80 0x80 0x80 0x00
```

So there is already ambiguity in encoding. I don't understand how does the definition for `uN` needs to change for decoding, however.

**Comment by rossberg** [comment]
The definition is working as intended. Here is the derivation for representing the value 4 in 3 bytes
```
4:u32
|
0x84:byte 0:u25 => 2^7*0 + 0x84-2^7 = 4  (0x84 >= 2^7 /\ 32 > 7)
          |
          0x80:byte 0:u18 => 2^7*0 + 0x80-2^7 = 0  (0x80 >= 2^7 /\ 25 > 7)
                    |
                    0x00:byte => 0  (0x00 < 2^7 /\ 0x00 < 2^18)
```
Similarly, you can derive an encoding up to 5 bytes. Longer sequences will be rejected by the side condition `N > 7` and because uN doesn't allow negative length.

**Comment by verbessern** [comment]
I see. For me that are not trailing zeroes, that are 0x80 and one trailing zero. If the meaning is for the usable bits then yes, no issue.
