### ISSUE TITLE
[spec] Execution vs Validation: blocktype expansion

### ISSUE THREAD

**Issue by philipahlberg** [WebAssembly/spec#1183]
The description for Control Instructions in the [instructions section under Execution](https://webassembly.github.io/spec/core/exec/instructions.html#control-instructions), uses an `expand_F` function to transform a block type to a function type.

In the corresponding [instructions section under Validation](https://webassembly.github.io/spec/core/valid/instructions.html#control-instructions), the `expand_F` function is not used. Instead, the transformation is covered separately by the [types section under Validation](https://webassembly.github.io/spec/core/valid/types.html#block-types) (as far as I can tell).

Would it be possible to unify these two approaches? As it is, it seems like they are out of sync.

**Comment by rossberg** [comment]
The expand function is only defined when the blocktype is valid in the first place. So it cannot be used in validation itself. Think of it as part of the execution semantics.
