### ISSUE TITLE
[spec] Validation: block vs loop

### ISSUE THREAD

**Issue by philipahlberg** [WebAssembly/spec#1189]
In the validation judgement for block, `[t2*]` (the output type of the block) is prepended to the `labels` vector in the context, while in the judgement for loop, it's `[t1*]` (the input type of the loop). Is this intended?

**Comment by conrad-watt** [comment]
It is intended. The purpose of prepending the type to the `labels` vector is to ensure that a `br` instruction targetting that label has that type as its input type.

Targetting block with a br causes execution to jump to the end of the block, and so the stack must have the block's output type at the point the br is executed (the input type of the br must be the output type of the block).

Targetting loop with a br causes execution to jump to the _start_ of the loop body, so the stack must have the loop's _input_ type at the point the br is executed (the input type of the br must be the _input_ type of the loop, to match the start of the loop body).

**Comment by philipahlberg** [comment]
Ah, I see. Thank you for clarifying. Feel free to close the issue.
Also, is there a place better suited for questions like this regarding the spec?

**Comment by rossberg** [comment]
There is an IRC channel. But for seeking clarification on technical spec questions (or possible bugs), this place seems fine. At least we failed to introduce something more appropriate. :)
