### ISSUE TITLE
Reserved or undefined instructions

### ISSUE THREAD

**Issue by wcaughey** [WebAssembly/spec#1199]
Apologies if this question was answered elsewhere--I searched but didn't find an answer.

I don't see any rules on how validation is to proceed on instruction sequences that contain reserved or undefined instructions (which makes sense), but is it then correct to deduce, that if an instruction sequence contains a reserved or undefined instruction that the sequence, and ultimately the entire containing module, should be considered invalid, and therefore not able to be instantiated?

**Comment by rossberg** [comment]
Technically, the spec separates decoding ("parsing") from validation ("typing"). An unknown opcode fails decoding, so doesn't even reach validation -- we call the binary malformed, as opposed to invalid. In practice, either leads to module construction ("compilation") failing, so no need to worry about the difference.

**Comment by wcaughey** [comment]
I see, thank you for the clarification.
