### ISSUE TITLE
[interpreter] Add command line option to control maximum recursion depth

### ISSUE THREAD

**Issue by mdesharnais** [WebAssembly/spec#1200]
At this moment, the maximum recursion depth is [hard-coded to 300](https://github.com/WebAssembly/spec/blob/a7a1856cc8e0e9cb6378acb083bb9c43494d05b1/interpreter/exec/eval.ml#L68). When experimenting with recursive functions, I rapidly reached this limit and had to change manually it in the source code before recompiling the interpreter.

This number feels arbitrary and I cannot think of any reason to prevent users from setting it to a number that fit their purpose. I propose to add a command line option (e.g. `-max-recursion-depth <natural-number>`) with 300 being the default value.

I am just starting to get to know the code base but, if this suggestion is accepted, I am willing to provide a pull request.

**Comment by rossberg** [comment]
Sounds good to me, happy to review such a PR.

**Comment by rossberg** [comment]
Fixed.
