### ISSUE TITLE
Inconsistency between table limit validation and possible encodings

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/spec#1210]
Unsure if this an issue, but it seemed odd to me.

1. Limits are defined as valid within an [inclusive range](https://webassembly.github.io/spec/core/valid/types.html#limits)
2. Table limits use the range [`[0, 2^32]`](https://webassembly.github.io/spec/core/valid/types.html#table-types)
3. Limit binary encoding and text parsing use `u32` for an effective range of [`[0, 2^32 - 1]`](https://webassembly.github.io/spec/core/text/values.html#integers)

This implies that there's a valid module that cannot be encoded or decoded. This isn't an issue in practice, as the web embedding limits prevent tables of this size.

I'm curious if this was intentional, or has a future use? If not, it may make sense to lower the table limit validation to [0, 2^32-1].

(This isn't an issue for memory limits because they are restricted to [0, 2^16].)

**Comment by rossberg** [comment]
Yes, I remember noticing this as well during my edits for table bulk instructions and fixing it [in the reftypes proposal](https://webassembly.github.io/reference-types/core/valid/types.html#table-types). Since the plan is to merge this very soon it will get fixed then.

**Comment by eqrion** [comment]
> Yes, I remember noticing this as well during my edits for table bulk instructions and fixing it [in the reftypes proposal](https://webassembly.github.io/reference-types/core/valid/types.html#table-types). Since the plan is to merge this very soon it will get fixed then.

Ah perfect, thanks!
