### ISSUE TITLE
[Question] Curious what is the state of WebAssembly Web API

### ISSUE THREAD

**Issue by redradist** [WebAssembly/spec#1221]
I am curious what is the state of WebAssembly Web API ?

**Comment by ngzhian** [comment]
The Web Embedding API is at https://webassembly.github.io/spec/web-api/index.html

**Comment by redradist** [comment]
@ngzhian 
> The Web Embedding API is at https://webassembly.github.io/spec/web-api/index.html
> If you're looking for the JavaScript interface, it is at https://webassembly.github.io/spec/js-api/index.html
> 
> Both documents are linked from https://webassembly.github.io/spec/

Yeah, I am interested in Web API from WebAssembly without JavaScript ... first spec ...
But there is no the percent  of progress and it does not describe when spec will be published

**Comment by ShadowJonathan** [comment]
There are also no proposals related to the Web API that'd finalize the specification into WASM itself, has all development stalled regarding this?

**Comment by binji** [comment]
The current wasm-web-api is a W3C REC, and can be found here: https://www.w3.org/TR/wasm-web-api/

**Comment by redradist** [comment]
> 
> 
> The current wasm-web-api is a W3C REC, and can be found here: https://www.w3.org/TR/wasm-web-api/

@binji But what is more interesting is how many done in specification ... I mean, is it 50% complete, maybe 20% or maybe 60% ?

For me it seems like 10% done according the size of document ...

**Comment by binji** [comment]
The WebAssembly specification is layered. The Web API spec builds on the JS API spec, which builds on the core API spec. What functionality are you expecting that is missing? If you are asking about being able to access web APIs without using JS, then you may want to take a look at the [interface-types proposal](http://github.com/webassembly/interface-types).

**Comment by redradist** [comment]
> 
> 
> The WebAssembly specification is layered. The Web API spec builds on the JS API spec, which builds on the core API spec. What functionality are you expecting that is missing? If you are asking about being able to access web APIs without using JS, then you may want to take a look at the [interface-types proposal](https://github.com/webassembly/interface-types).

@binji Yes, I am asking about accessing Web API without JS ...
But interface type will allow to bypass data, but I think there will be separate specification for WebAssembly Web API without JS ?

**Comment by tlively** [comment]
@redradist No, there are no plans to expose Web APIs to WebAssembly directly without going through JS.

**Comment by ShadowJonathan** [comment]
@tlively can I get a source on this? I have only seen direct assertions that this is on the roadmap, even [mozilla's website](https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts) says [so](https://i.imgur.com/Dl4crIV.png).

**Comment by tlively** [comment]
Ah, I guess there is some nuance depending on what you mean by "direct access" to Web APIs.

 - If you mean new versions of Web APIs that are defined in terms of WebAssembly concepts: This is not on any roadmap.

 - If you mean being able to call Web APIs without explicitly importing them from the environment: This is not on any roadmap, either. As far as I can tell, even the [ESM integration](https://github.com/WebAssembly/esm-integration) proposal would require writing an ES module wrapping Web APIs to make them available to import, but I'm not super familiar with ES modules, so I could be wrong about that. Either way, the APIs still need to be imported.

 - If you mean being able to hold handles to objects used in Web APIs and pass them directly to imported Web APIs without redirecting through JS glue: This is possible using reference types, but it is not expressible in many source languages and ultimately still uses JS objects. A GC proposal might make it possible for those handles to behave more like first-class JS objects inside WebAssembly, but that still would be incompatible with many source languages and would still ultimately be using JS objects.

**Comment by redradist** [comment]
> 
> 
> Ah, I guess there is some nuance depending on what you mean by "direct access" to Web APIs.
> 
>     * If you mean new versions of Web APIs that are defined in terms of WebAssembly concepts: This is not on any roadmap.
> 
>     * If you mean being able to call Web APIs without explicitly importing them from the environment: This is not on any roadmap, either. As far as I can tell, even the [ESM integration](https://github.com/WebAssembly/esm-integration) proposal would require writing an ES module wrapping Web APIs to make them available to import, but I'm not super familiar with ES modules, so I could be wrong about that. Either way, the APIs still need to be imported.
> 
>     * If you mean being able to hold handles to objects used in Web APIs and pass them directly to imported Web APIs without redirecting through JS glue: This is possible using reference types, but it is not expressible in many source languages and ultimately still uses JS objects. A GC proposal might make it possible for those handles to behave more like first-class JS objects inside WebAssembly, but that still would be incompatible with many source languages and would still ultimately be using JS objects.

@tlively The topic is mostly about calling Web API without JavaScript, through WebAssembly directly to browser ...

**Comment by tlively** [comment]
> But interface type will allow to bypass data, but I think there will be separate specification for WebAssembly Web API without JS ?

To summarize, no, there is no such proposal at the moment. But proposals such as ES Module integration and interface types might help make the JS more invisible when calling Web APIs.

**Comment by redradist** [comment]
> 
> 
> > But interface type will allow to bypass data, but I think there will be separate specification for WebAssembly Web API without JS ?
> 
> To summarize, no, there is no such proposal at the moment. But proposals such as ES Module integration and interface types might help make the JS more invisible when calling Web APIs.

@tlively Don't you think this is strange ?

JavaScript compiles to intermediate representation that than executed by Engine, but WebAssembly is closer to Engine execution step than JavaScript

JavaScript -> Parsing ->Optimizations -> WebAssembly -> Intermediate Representation -> Engine

And every time WebAssembly call should go from:
                                                     Execute WebAssembly API Call
      |---------------------------------------------------------------------------------------------------------|  
JavaScript -> Parsing ->Optimizations -> WebAssembly -> Intermediate Representation -> Engine
       |__________________________________________________|
                              Web API Call

It is strange and due to this in engine you should implement a lot of workarounds as my opition

**Comment by devshgraphicsprogramming** [comment]
It would be useful to not have all that god-awful glue code in Emscripten, esp for WebGL and XHR

**Comment by sascha1337** [comment]
> It would be useful to not have all that god-awful glue code in Emscripten, esp for WebGL and XHR

this. so much. cmon we can do better, even it would not be some official WebAssembly workgroup / w3c standard, we need to solve these ultra-blockers asap as community, it's been years (!) of waiting, without any real upstream consensus implementation here.

KISS style, we should start with some simple cross-wasm/wasi/llvm/rust/wasm-bindgen/emscripten standard, to simply and safely make it possible to pass the basic language types as argument ( and obviously the ability for MULTIPLE arguments for some import function) like strings/varchar[x], int, float, whatever, and flat-non-nested json objects asap

**Comment by ROBERT-MCDOWELL** [comment]
after 6 years of the official start of webassembly, I still absolutely don't understand how to use it and why there is zero professional software like Adobe not using it...

**Comment by eqrion** [comment]
> It would be useful to not have all that god-awful glue code in Emscripten, esp for WebGL and XHR

It would be helpful for prioritization to know what is the problem with glue-code in the browser.

Is it performance? There are existing benchmarks, such as for [wasm-bindgen](https://rustwasm.github.io/wasm-bindgen/benchmarks/) that indicate glue code can be very fast. Firefox has done significant work to optimize this. There are possibly some cases where it's too slow, but often that has to do with large copies into and out of the wasm heap. There is one active proposal that may help [here](https://github.com/webassembly/memory-control), but it won't remove glue code.

Is it functionality? My understanding of the existing binding tools is that they can use essentially any API.

Is it a desire to remove a tool? If you're using wasm in the browser, you already have a tool to compile and so there's no good path to hand-write wasm without tools. It's possible there are some ergonomic improvements in the tools, but that is outside the wasm spec process.

**Comment by penzn** [comment]
> after 6 years of the official start of webassembly, I still absolutely don't understand how to use it and why there is zero professional software like Adobe not using it...

[Photoshop Web](https://helpx.adobe.com/photoshop/using/workspace-web.html)

**Comment by ROBERT-MCDOWELL** [comment]
I was talking about a decent software like animate that cmopile projects in wasm rather than javascript.

**Comment by tlively** [comment]
This has been sufficiently answered.

**Comment by devshgraphicsprogramming** [comment]
> This has been sufficiently answered.

I'd still like WASM without JS

**Comment by sascha1337** [comment]
> after 6 years of the official start of webassembly, I still absolutely don't understand how to use it and why there is zero professional software like Adobe not using it...

….. figma use it ?

**Comment by sascha1337** [comment]
> > This has been sufficiently answered.
> 
> I'd still like WASM without JS

its called wasi ser

**Comment by ROBERT-MCDOWELL** [comment]
@tlively 
for you apparently...

**Comment by dtig** [comment]
This thread has replies about the Web API, and examples of production applications that use the Web API. 

@ROBERT-MCDOWELL Do you have a specific question that hasn't already been answered?

**Comment by ROBERT-MCDOWELL** [comment]
@dtig
not at all anymore, since I understand that WebAssembly is a standard for corporations but not for everybody...

**Comment by dtig** [comment]
I'm not sure that there's anything in this thread that should lead to that conclusion, but if you do have specific inputs into the spec process to make the developer experience better, one way to address that is filing a new design issue with specific concerns about what you'd like addressed, or with ideas for a proposal. Here is a [helpful document ](https://github.com/WebAssembly/meetings/blob/main/process/proposal.md)that outlines how to get started with new design ideas/proposals.

**Comment by devshgraphicsprogramming** [comment]
> > > This has been sufficiently answered.
> > 
> > 
> > I'd still like WASM without JS
> 
> its called wasi ser

in the Browser.
