### ISSUE TITLE
Tests require more than MVP features

### ISSUE THREAD

**Issue by rianhunter** [WebAssembly/spec#1222]
Ever since c8fd933fa51eb0b511bce027b573aef7ee373726, running the automated spec test running requires a wasm interpreter that supports features that go beyond the MVP.

Is this intentional?

**Comment by Ms2ger** [comment]
Yes. This repository captures the current state of standardized WebAssembly (MVP + phase 5 proposals); it's not intended to be a snapshot of the MVP.

**Comment by rianhunter** [comment]
Ah I see, thanks for the info. Are all proposed features intended to eventually become standardized WebAssembly? Is there any standard notion of features that will remain optional? E.g I have no need to implement the "Non-trapping float-to-int conversions" since my use case does not require it, should there be a way for me to still use the test suite?

**Comment by tlively** [comment]
Yes, all proposed features are intended to become part of the WebAssembly standard. We do not currently have a mechanism in the standard to mark features as optional, so as features enter phase 5, engines that do not implement them will no longer be compliant with the latest spec and may need to pin older versions of tests and tools. That being said, there is widespread interest in introducing a mechanism to make features optional, so it is possible that this story will be different for future proposals.

**Comment by rossberg** [comment]
> Yes, all proposed features are intended to become part of the WebAssembly standard.

Well, strictly speaking I would say that is only true of features that have at least reached phase 2. Phase 1 is more like an investigation stage.
