### ISSUE TITLE
Inconsistent definition of the square root of negative 0

### ISSUE THREAD

**Issue by akirilov-arm** [WebAssembly/spec#1226]
I noticed a minor issue with the [definition](https://webassembly.github.io/spec/core/exec/numerics.html#op-fsqrt) of the square root operator - it implies that the square root of negative 0 is a NaN:
> * If z is a NaN, then return an element of nans_N{z}.
> * Else if z has a negative sign, then return an element of nans_N{}.
> * Else if z is positive infinity, then return positive infinity.
> * Else if z is a zero, then return that zero.
> * Else return the square root of z.

Note that this is a contradiction with the formal notation that follows (and which specifies that the result is negative 0).

**Comment by rossberg** [comment]
Indeed, thanks! See #1227.

**Comment by Ms2ger** [comment]
Do we have a test for this?

**Comment by rossberg** [comment]
Yes, e.g., f32.wast:2419.
