### ISSUE TITLE
About the maximum memory size limit

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/spec#1229]
Hi,

There is a core spec test that requires that the memory size of a module is at most 65536 pages. I know that this limit makes sense, but it's nowhere written. It is only written in the js-api spec, where it is defined as a dynamic limit. The difference between a core spec limit and a dynamic limit is that exceeding the core spec causes a validation error, whereas the dynamic limit only causes an error at instantiation or at runtime.

I think it would be best to add the limit to the core spec, and remove the dynamic limit from the js-api, as it would not be needed anymore. Wdyt?

Cheers, Andreas

**Comment by rossberg** [comment]
The core spec does specify this as part of the well-formedness of memory types, see [here](https://webassembly.github.io/spec/core/valid/types.html#memory-types).

**Comment by gahaas** [comment]
Thanks for the pointer.
