### ISSUE TITLE
Document compilation: `sphinx.ext.mathbase` has been deprecated

### ISSUE THREAD

**Issue by hachi8833** [WebAssembly/spec#1243]
Ref: https://www.sphinx-doc.org/en/master/extdev/deprecated.html

The following declarations in mathdef.py and mathdefbs.py under document/core/util/ have been deprecated in recent sphinx:

```python
from sphinx.ext.mathbase import math
from sphinx.ext.mathbase import MathDirective
```

At least, they should be updated like the following, which are still incomplete:

```python
import math
from docutils.parsers.rst.roles import math_role
from sphinx.directives.patches import MathDirective
```

Revising as above still causes an error on `ext_math_role` in mathdef.py:

>   File "/Users/hachi8833/deve/wasm/spec/document/core/util/mathdef.py", line 59, in ext_math_role
    return [math(raw, text)], []
TypeError: 'module' object is not callable

Current sphinx version on my macOS Catalina environment:

```
pip list sphinx|rg -i sphinx
Sphinx                        3.2.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
```

Hope someone would check this.
Regards,

**Comment by ngzhian** [comment]
The spec is set up to build with [Sphinx version 2.4.4](https://github.com/WebAssembly/spec/blob/master/.travis.yml#L24). If possible can you pin your installation of Sphinx to 2.4.4 and try again? You will still get the deprecation warnings in the output, but it will build fine.
(Maybe we should have a Pipfile in document/ to help with this).

**Comment by hachi8833** [comment]
The step-by-step guide worked! Thank you very much!
