### ISSUE TITLE
Stack width, 32 or 64 bit?

### ISSUE THREAD

**Issue by isral** [WebAssembly/spec#1244]
I want to know whether WASM stack is 32 bit or 64bit?
Or maybe undefined?

**Comment by tlively** [comment]
Hi @isral, can you elaborate a little more on what you'd like to know? The WebAssembly value stack is a conceptual stack of values of all WebAssembly types like `i32`, `i64`, `f32`, `f64`, etc. so it doesn't really have a bit width. There's also the in-memory stack used for address-taken variables in C, C++, Rust, and other languages. That stack is addressed using 32-bit pointers, just like the rest of WebAssembly memory. There is work on extending WebAssembly to handle 64-bit memories as well: https://github.com/WebAssembly/memory64.

**Comment by isral** [comment]
@tlively 
Maybe I use wrong term.
If the stack is 64 bit, pushing 2 i32 will consume 16 byte of stack (i32 widened to i64).
If the stack is 32 bit, pushing 2 i32 will consume 8 byte of stack.
If undefined, then it's up to the implementor.

**Comment by tlively** [comment]
The way the WebAssembly value stack is represented is up to the implementor. In fact, in optimizing engines it's not usually represented as a real stack at all. Instead, it compiles down to register accesses and stack slots on the host machine after going through normal, SSA optimizations.

**Comment by isral** [comment]
Thanks
