### ISSUE TITLE
[test] Memory grow test doesn't test dirty memory

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/spec#1256]
Memory grow tests grow already-zeroed memory. They don't take dirty memory into account. See also https://github.com/WebAssembly/wabt/pull/1557

**Comment by rossberg** [comment]
I don't follow, can you elaborate? The semantics requires that the new pages after a grow are zeroed.

**Comment by osa1** [comment]
I think they mean that none of the tests check old page contents after a grow. Contents in old pages should be preserved after a `memory.grow`.

**Comment by SoniEx2** [comment]
None of the memory grow tests *write* to old pages.

Because we decided to go with reverse memory for https://github.com/WebAssembly/wabt/pull/1557, well... C++ doesn't have a resize_left, so we have to move things around. The tests don't detect if you forget to zero things after moving things around, because it never writes to old pages.

**Comment by rossberg** [comment]
Hm, okay, how about creating a PR to add tests along these lines?

**Comment by rossberg** [comment]
Closing this old issue. Feel free to create a PR anyway.
