### ISSUE TITLE
[Question] Caching compiled wasmBinaryFile with WebAssembly.instantiate

### ISSUE THREAD

**Issue by rzydek** [WebAssembly/spec#1265]
I've got inlined wasmBinary in base64 format and I want to instantiate it without Fetch API and cache it to avoid compilation on every page refresh. I am also curious if there is a way to abort second browser compilation?

**Comment by titzer** [comment]
Unfortunately decoding base64 to binary and then feeding that to the Wasm engine is going to defeat the browser's HTTP-cache-based Wasm module caching. Your best bet is to have the .wasm file as a separate HTTP resource.

**Comment by rossberg** [comment]
Closing as answered.
