### ISSUE TITLE
[Question]Length of name in the custom section

### ISSUE THREAD

**Issue by imor** [WebAssembly/spec#1277]
The spec says that the contents of the [custom section](https://webassembly.github.io/spec/core/binary/modules.html#binary-customsec) start with a name. The [name section](https://webassembly.github.io/spec/core/binary/values.html#binary-name) says that a name is a vector of utf8 encoded bytes. My question is how would I find out where the name ends and the contents of a custom section begins? Especially since the note at the bottom says that the name strings are not 0-terminated.

**Comment by Ms2ger** [comment]
[One more click](https://webassembly.github.io/spec/core/binary/conventions.html#binary-vec):

> Vectors are encoded with their u32 length followed by the encoding of their element sequence.

**Comment by imor** [comment]
Ah cool, that makes sense. thanks.
