### ISSUE TITLE
binary-leb128.wast has unlinkable module commands

### ISSUE THREAD

**Issue by jasonwyatt** [WebAssembly/spec#1278]
There are three `(module binary .. )` commands in `binary-leb128.wast` which should fail given my understanding of the [script-execution spec](https://github.com/WebAssembly/spec/tree/master/interpreter#scripts):

> Commands are executed in sequence. Commands taking an optional module name refer to the most recently defined module if no name is given. They are only possible after a module has been defined.
> 
> After a module is registered under a string name it is available for importing in other modules.
> 
> The script format supports additional syntax for defining modules. A module of the form (module binary <string>*) is given in binary form and will be decoded from the (concatenation of the) strings. A module of the form (module quote <string>*) is given in textual form and will be parsed from the (concatenation of the) strings. **In both cases, decoding/parsing happens when the command is executed, not when the script is parsed, so that meta commands like assert_malformed can be used to check expected errors.**

The commands are located from [Line 74 to Line 109 of binary-leb128.wast](https://github.com/WebAssembly/spec/blob/4339e90f995019464b02513c2b11a33e0e7b3874/test/core/binary-leb128.wast#L74-L109):

```wast
(module binary
  "\00asm" "\01\00\00\00"
  "\01\05\01"                          ;; type section
  "\60\01\7f\00"                       ;; function type
  "\02\17\01"                          ;; import section
  "\88\00"                             ;; module name length 8, encoded with 2 bytes
  "\73\70\65\63\74\65\73\74"           ;; module name
  "\09"                                ;; entity name length
  "\70\72\69\6e\74\5f\69\33\32"        ;; entity name
  "\00"                                ;; import kind
  "\00"                                ;; import signature index
)
(module binary
  "\00asm" "\01\00\00\00"
  "\01\05\01"                          ;; type section
  "\60\01\7f\00"                       ;; function type
  "\02\17\01"                          ;; import section
  "\08"                                ;; module name length
  "\73\70\65\63\74\65\73\74"           ;; module name
  "\89\00"                             ;; entity name length 9, encoded with 2 bytes
  "\70\72\69\6e\74\5f\69\33\32"        ;; entity name
  "\00"                                ;; import kind
  "\00"                                ;; import signature index
)
(module binary
  "\00asm" "\01\00\00\00"
  "\01\05\01"                          ;; type section
  "\60\01\7f\00"                       ;; function type
  "\02\17\01"                          ;; import section
  "\08"                                ;; module name length
  "\73\70\65\63\74\65\73\74"           ;; module name
  "\09"                                ;; entity name length 9
  "\70\72\69\6e\74\5f\69\33\32"        ;; entity name
  "\00"                                ;; import kind
  "\80\00"                             ;; import signature index, encoded with 2 bytes
)
```

Each of these commands require an import from a module named `"spectest"` which has never (in the script itself) been registered with a `(register ....)` command.

**Comment by rossberg** [comment]
Spectest is a small host module that's assumed to exist. It is used by a number of other tests as well. See [here](https://github.com/WebAssembly/spec/blob/master/interpreter/host/spectest.ml#L33) for how the reference interpreter defines it. Any other environment running the tests needs to implement something equivalent.

The existence of this module predates the ability to register modules in tests. Today, I wouldn't mind removing it and change all respective tests using it to register their own auxiliary modules. Happy to accept patches. ;)

**Comment by jasonwyatt** [comment]
Is this documented anywhere? I am working on a spec test runner for my
interpreter and want to make sure I'm not missing anything else...

**Comment by rossberg** [comment]
@jasonwyatt, it wasn't other than in code. I just committed #1280, which adds a [section](https://github.com/WebAssembly/spec/tree/master/interpreter#spectest-host-module) to the README.
