### ISSUE TITLE
Provide release notes / diff when spec is updated

### ISSUE THREAD

**Issue by jasonwyatt** [WebAssembly/spec#1283]
I've been working on an interpreter as a side-project for a while now and I just noticed that the spec's version was recently bumped from 1.0 to 1.1, but there isn't an easy-to-find list of the changes/additions made in the release.

It would be great to provide release notes whenever the spec is updated, especially as the spec evolves quickly.

**Comment by philipahlberg** [comment]
To add to this, it would also be nice to have the spec for older versions published alongside the newest version. I imagine this is probably to do initially.

**Comment by tlively** [comment]
I agree this is an important issue. See also https://github.com/WebAssembly/design/issues/1395 for a similar request. @rossberg, would it make sense to have a change log appendix in the spec? Would there be a better mechanism to make changes more discoverable?

**Comment by rossberg** [comment]
An appendix summarising new features and other changes makes total sense to me. The only existing "mechanism" would be the [list of finished proposals](https://github.com/WebAssembly/proposals/blob/master/finished-proposals.md), which should reflect what was added. The design docs of merged proposals are also archived [in the spec repo](https://github.com/WebAssembly/spec/tree/master/proposals).

**Comment by helins** [comment]
I confirm that not having even a basic changelog is cumbersome. I am writing a WASM decompiler/compiler and by pure chance have noticed new additions yesterday (ref instructions and so one). I am currently re-reading all specs to guess what changed.

This is even more important if the purpose is having "living specs" that everyone is supposed to keep up with. It should be easy to find out "how" to keep up.

**Comment by rossberg** [comment]
Fixed by #1306.
