### ISSUE TITLE
WebAssembly.instantiateStreaming 2nd argument optional but required

### ISSUE THREAD

**Issue by yoones** [WebAssembly/spec#1284]
This issue follows this one: https://github.com/mdn/content/pull/2008

> I opened a stackoverflow thread about this: https://stackoverflow.com/questions/66008362/webassembly-instantiatestreaming-requires-an-optional-argument
>
> To sum up, the second argument of `WebAssembly.instantiateStreaming` is marked as optional in the documentation but is actually required in the browser (tested on firefox and chrome). I suggest to remove the `optional` flag from the documentation.

TL;DR: the [documentation](https://webassembly.org/docs/web/#webassemblyinstantiatestreaming) says `importObject` is optional but the implementation on Firefox and Chrome requires it.

**Comment by ngzhian** [comment]
I just tired it on 88.0.4324.96 MacOS, it works, the import object is not required. Are you running the test file via a http server? Where is the line of code that this error is thrown?

**Comment by Ms2ger** [comment]
It is required only if the module you're instantiating actually imports something.
