### ISSUE TITLE
PDF: text clips beyond right border

### ISSUE THREAD

**Issue by Toideng** [WebAssembly/spec#1299]
In PDF version dated by March 12, 2021, page 123 (127 of 186 in global counter), section "5.5.12  Element Section" clips beyond the right boundary, making it unreadable and unprintable.
![2021-03-21-191842_1090x484_scrot](https://user-images.githubusercontent.com/37709930/111917970-a0011200-8a7a-11eb-8b86-24ea81e5988e.png)

Same on page 84 (88 of 186, section "4.4.5  Table Instructions", subsection "table.copy x y")
Same on page 85 (89 of 186, section "4.4.5  Table Instructions", subsection "table.init x y")
Same on page 90 (94 of 186, section "4.4.6  Memory Instructions", subsection "memory.fill")
Same on page 91 (95 of 186, section "4.4.6  Memory Instructions", subsection "memory.init x")
Same on page 93 (97 of 186, section "4.4.7  Control Instructions", subsection "if blocktype instr1 else instr2 end")
Same on page 105 (109 of 186, section "4.5.3  Allocation", subsection "Modules")
page 123 already mentioned
Same on page 168 (172 of 186, section "7.5.2 Store Validity", subsection "Module Instances moduleinst")

**Comment by Toideng** [comment]
There are a couple other places, not mentioned above, where text is getting close to the border but not actually clipping through, but might still cause issues when printing on some printers which require ~1cm clear padding on both sides.

**Comment by rossberg** [comment]
Thanks for this, these clippings should be fixed by #1307, PTAL. Ideally, there shouldn't be any overwide math boxes, but the PDF version isn't checked as often as the HTML, so much slips through. Let me know if there are other places that you think need fixing.
