### ISSUE TITLE
Not equal signs are not displayed correctly in the one-page version

### ISSUE THREAD

**Issue by SpecLad** [WebAssembly/spec#1302]
For example, here:

https://webassembly.github.io/spec/core/bikeshed/#-hrefsyntax-instr-controlmathsfbr_ifl%E2%91%A0

Here's what I see in Firefox:

![screenshot](https://user-images.githubusercontent.com/2391761/113072347-85900c80-91cf-11eb-8f81-b53bda3baaac.PNG)

**Comment by ngzhian** [comment]
This looks okay for me on Safari Version 14.0.3 (16610.4.3.1.7), and Chrome Version 89.0.4389.90, and Firefox 87.0 (64-bit). What version of Firefox are you using? Also, this relies on a katex font, so make sure you're not blocking fonts or something like that.

<img width="862" alt="spec on firefox" src="https://user-images.githubusercontent.com/1749303/113184903-9b6ef300-920a-11eb-8527-562e2cdacacf.png">

**Comment by SpecLad** [comment]
Sorry, looks like I jumped the gun there.

I do block fonts; however, I was originally reading the 1.0 release version on w3.org, in which unblocking fonts does _not_ resolve this problem. But in the draft version, it does (I just didn't think to try).

I'm gonna assume this was some tooling problem that was resolved after the 1.0 release.
