### ISSUE TITLE
Incorrect condition for text encoding of call_indirect

### ISSUE THREAD

**Issue by SpecLad** [WebAssembly/spec#1310]
In section [6.5.2](https://webassembly.github.io/spec/core/bikeshed/#control-instructions%E2%91%A8) the encoding for `call_indirect` is given as follows:

> `‘call_indirect’`  _x_:`tableidx`  _y_,_I′_:`typeuse`<sub>_I_</sub>​​ ⇒​ `call_indirect` _x_ _y_ ​(if _I′_={})

With a note saying:

> The side condition stating that the identifier context I′ must be empty in the rule for `call_indirect` enforces that no identifier can be bound in any `param` declaration appearing in the type annotation.

However, according to the definition of `typeuse`, it will always produce a context whose **locals** component contains the same amount of elements as the number of parameters in the referenced function type. Therefore, the only way I' can be empty (i.e. { **locals** ϵ }) is if the function type has no parameters. I assume no such restriction is meant to be impled by the encoding rule.

It seems to be like the condition should actually be "if _I′_={ **locals** (ϵ)\* }", which permits all function types, but not parameter identifiers.

**Comment by rossberg** [comment]
Ah, good catch! There was a similar inaccuracy in the rule for blocktypes. PTAL at #1311 for a fix.

**Comment by SpecLad** [comment]
Fixed by #1311.
