### ISSUE TITLE
Identifiers can seemingly be replaced with fresh identifiers

### ISSUE THREAD

**Issue by SpecLad** [WebAssembly/spec#1313]
In [6.6.5.1](https://webassembly.github.io/spec/core/bikeshed/#abbreviations%E2%91%A0%E2%93%AA), the condition on the rewrite rule is (if `id`′ = `id`<sup>?</sup> !​= ϵ ∨ `id`′ fresh), which suggests that as long as `id`′ is a fresh identifier, the rule can be applied. So even if the declaration already has an identifier, that identifier can be replaced with a fresh one.

That seems wrong and unintentional, as it would break any references to the original identifier. The right side of the condition should probably be changed to something like (`id`′ fresh ∧ `id`<sup>?</sup> = ϵ).

Same thing applies to the many similar rewrite rules for other types of declarations.

**Comment by rossberg** [comment]
Ah yes, you are right, the right side needs to negate the left to be accurate. Please see #1315 for a fix, I reformulated the condition slightly to make it more symmetric.
