### ISSUE TITLE
[WAT Spec] Table abbreviation with vec(expr) unclear/ill-defined

### ISSUE THREAD

**Issue by laelath** [WebAssembly/spec#1318]
The second abbreviation for table definition [(here)](https://webassembly.github.io/spec/core/text/modules.html#text-table-abbrev) contains a `vec(expr)`, which is ambiguous since there's nothing delimiting the expressions, and elaborates it to an `(elem id' (i32.const 0) vec(expr))` which as far as I can tell is not a valid definition for an `elem`.

I assume the `vec(expr)` is supposed to be `vec(elemexpr)`?

**Comment by rossberg** [comment]
Thanks. In fact there were several bugs/typos in this one diagram. Should all be fixed by #1321, PTAL.

**Comment by rossberg** [comment]
Closed #1318 via #1321.
