### ISSUE TITLE
Finish TestingTodo.md

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#132]
We should work through the remaining items in [TestingTodo.md](https://github.com/WebAssembly/spec/blob/master/ml-proto/TestingTodo.md). Once finished, we can probably move to just filing new issues for new test ideas, at least until we start collecting ideas in bulk again (eg. when we introduce major features like threads).

Some of the items may already have tests (particularly the ones related to memory semantics), some may be out of date with respect to recent changes, some may need to be clarified, and some just need tests to be written. Anyone is welcome to join in; please post plans here so that we can coordinate our efforts.

**Comment by sunfishcode** [comment]
@pjuftring is working on several tests, as mentioned [here](https://github.com/WebAssembly/spec/pull/119#issuecomment-147695586).

**Comment by rossberg-chromium** [comment]
Closing as discussed offline.
