### ISSUE TITLE
WebAssembly.Global.value.set without argument

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/spec#1332]
There is a test which requires `WebAssembly.Global.value.set` to throw a `TypeError` if it gets called without parameter, see

https://github.com/WebAssembly/spec/blob/484bb2b5b8a9cf5f774310bcd28e11186aa1705e/test/js-api/global/value-get-set.any.js#L134

I cannot figure out where the spec requires this `TypeError`, especially in https://webassembly.github.io/spec/js-api/#dom-global-value no `TypeError` is specified. Wouldn't a missing parameter just get substituted by an `undefined`?

**Comment by Ms2ger** [comment]
Over here: https://heycam.github.io/webidl/#dfn-attribute-setter , step 4.1.

**Comment by gahaas** [comment]
Interesting. Now I'm wondering why webidl is different than pure JS, because in both Chrome and Firefox the snippet
```
let o = { set x(x_) { console.log('setter, param is ' + x_); } };
Object.getOwnPropertyDescriptor(o, 'x').set.call();
```
prints out `setter, param is undefined`.
