### ISSUE TITLE
[spec] Possible typo in Memory Instructions

### ISSUE THREAD

**Issue by rahulv4667** [WebAssembly/spec#1334]
In the second para of [memory instructions](https://webassembly.github.io/spec/core/bikeshed/#memory-instructions), it states `The static address offset is added to the dynamic address operand, yielding a 33 bit effective address that is the zero-based index at which the memory is accessed.`. Is it 32-bit effective address or am I missing some concept?

**Comment by rossberg** [comment]
No, that's intentional. Adding two 32 bit values (static offset and dynamic operand) yields a result in the 33 bit range. Of course, any value outside the 32 bit range will inevitably cause an out of bounds error.

**Comment by rahulv4667** [comment]
Oh. Ok. Thank you.
