### ISSUE TITLE
[Question] What is the "right" way to construct a `Values.value`?

### ISSUE THREAD

**Issue by abrown** [WebAssembly/spec#1340]
@rossberg, @ngzhian, and anyone else who may be familiar with the interpreter: today I worked on exposing interpretation with the OCaml spec interpreter in Rust by using the `ocaml-interop` crate. The Rust signature looks roughly like `fn interpret(module: Vec<u8>, params: &[Value]) -> Vec<Value>`. I have it working for I32 values, but need to expand to the rest of the Wasm types. It is relatively easy for me to pass OCaml `int` and `float` types across the FFI boundary using `ocaml-interop`, but before I call `Eval.invoke`, I need those `int` and `float` values to be of type `Values.value`. I have converter functions that do something like the following:

```
let convert_to_wasm (v: value) : Values.value = match v with
| VI32 n -> Values.Num (I32 (I32.of_int_s n))
| _ -> failwith "Unknown type"

let convert_from_wasm (v: Values.value) : value = match v with
| Values.Num (I32 n) -> VI32 (I32.to_int_s n)
| _ -> failwith "Unknown type"
```

The `Values.Num (I32 (I32.of_int_s n))` part seems a bit clunky so I figured I would ask: what is the "right" way to do this?

Also, if you're interested, I'd be happy to hear your suggestions for how to do the same for floats, references, and v128's. I should mention that I will also be able to pass OCaml `Bytes` across the FFI boundary along with `int` and `float`, if that helps.

**Comment by rossberg** [comment]
This looks okay to me, and this pattern should extend to other types (though SIMD is gonna be a bit trickier). Of course, the `Int.of/to_int_s` calls and similar conversions shouldn't be needed if the Rust FFI was able to handle OCaml's int32/int64 types -- can't it?

**Comment by abrown** [comment]
Yeah, that's a good point about using int32/int64 directly. I just assumed it wouldn't be available but it turns out the FFI layer I'm using does have the support, e.g., [OCamlInst64](https://docs.rs/ocaml-interop/0.8.4/ocaml_interop/struct.OCamlInt64.html). Thanks!
