### ISSUE TITLE
Test more side-effects/order of execution

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/spec#1343]
There should be a side-effects test-suite. In particular, trapping is a side-effect.

Code like this:

```
i32.const 0 i32.const 0 i32.div_s i32.const 1 global.set 0 local.set 0
```

breaks on an implementation that currently passes every other test. (the test should set the global to 0, call this code, and assert that the global is still 0.)

More importantly, this example is a fundamental core semantic. That's why it should be part of the spec test.

**Comment by rossberg** [comment]
@SoniEx2, sounds good, we are happy to accept PRs adding more tests.
