### ISSUE TITLE
What mime type would be used with `.wat` (text format) file extensions?

### ISSUE THREAD

**Issue by summercms** [WebAssembly/spec#1347]
Did a search through this repo and couldn't my an answer.

The closet issue was found here: https://github.com/WebAssembly/spec/issues/573

I noticed @ericprud registered the IANA found here: https://github.com/WebAssembly/spec/issues/573#issuecomment-824715263

```
.wat (text format)
.wasm (binary format)
```

`.wasm` uses `application/wasm`

What would `.wat` use?

I was expecting to see: `text/wasm` in IANA for the `.wat` file extension.

Should I use `application/wasm` for `.wat` file extensions?

Please advise.

p.s. Just working on a mime type app and want to register the correct mime-type to the `.wat` file extension.

**Comment by Ms2ger** [comment]
Certainly not `application/wasm`. `.wat` is not intended for interchange, so I'm not sure it needs a mime type.

**Comment by ericprud** [comment]
> `.wat` is not intended for interchange, so I'm not sure it needs a mime type.

If you have to pick some media type, `text.plain` seems appropriate. If it isn't specific enough, i.e. some client is switching its behavior based on the media type for some `foo.wat` resource, it's probably being used for interchange and we have to revisit the above assumption.

**Comment by summercms** [comment]
@ericprud Thank you, will go with `text/plain`
