### ISSUE TITLE
Inspecting memory limits from the Javascript API

### ISSUE THREAD

**Issue by jashug** [WebAssembly/spec#1348]
JavaScript should be able to inspect the declared limits on imported memories.

The `Module.imports` function returns information about the types of the module's imports, but it is missing some important information about memory limits. When memory is imported, the provided memory size is checked against the minimum size (and optional maximum size) declared by the module. However, there does not seem to be a way for JavaScript to learn about those limits.

The specification of `Module.imports` (linked below) defines what information is available to JavaScript about the module.
For memories, all it tells you is that the import has kind "memory". 
https://github.com/WebAssembly/spec/blob/2e629bc63aad31982d8941a4263e4ecacae00c94/document/js-api/index.bs#L542-L548 https://github.com/WebAssembly/spec/blob/2e629bc63aad31982d8941a4263e4ecacae00c94/document/js-api/index.bs#L561-L570 (This algorithm has been mostly unchanged since at least https://github.com/WebAssembly/spec/pull/591, maybe earlier)

Adding a line after L567 like:
```
If |type| is of the form [=mem=] <var ignore>memtype</var>, add "{{ModuleImportDescriptor/limits}}" →
   «[ "min" → type.min, "max" → type.max (if defined), "shared" → type.isShared ]» to |obj|.
```
would specify a way of communicating the details of the memory type to JavaScript. This may be useful for tables as well.
___
My use case is making a general-purpose WebAssembly worker, that you can pass a Module and it sets it up for you. To do the setup, in case there are imported memories, I have to figure out appropriate parameters to pass to the Memory constructor. Since the declared limits put hard constraints on the acceptable values, it would make my life much simpler to be able to read these from the Module itself, rather than having to track it out-of-band.
___
(Hi, I'm new here, apologies if this is the wrong place for this issue.)

**Comment by rossberg** [comment]
If I understand correctly, this is subsumed by the more general type reflection extension already [proposed](https://github.com/WebAssembly/js-types/blob/master/proposals/js-types/Overview.md): with that, you can get the maximum size of a memory import as `mem_import.type.maximum`.

**Comment by jashug** [comment]
Oh wonderful, thank you very much. Yes, that proposal is exactly what I need, and this issue is essentially a duplicate of the linked WebAssembly/design#1046.
