### ISSUE TITLE
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by clark-97** [WebAssembly/spec#1353]
I am using angular and lib jitsi meet to implement the background blur function, I copied some code snippets from 
https://github.com/jitsi/jitsi-meet/tree/master/react/features/virtual-background
and 
https://github.com/jitsi/jitsi-meet/tree/master/react/features/stream-effects/virtual-background

https://github.com/jitsi/jitsi-meet/blob/4dc642fb4dff8e470eb7576fd4dffe8a44d04248/react/features/stream-effects/virtual-background/index.js#L48
show this error: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -s ASSERTIONS=1 for more info.
3c 21 64 6f means what? any other solution to implement the background blur function with angular and lib jitsi meet?
related issue: #1031

**Comment by ngzhian** [comment]
`3c 21 64 6f ` is ASCII for `<!do`, it looks like you are instantiating a HTML page? WebAssembly.instantiate need a Wasm module, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate

**Comment by ericprud** [comment]
maybe a 404 message or a redirect?

**Comment by clark-97** [comment]
I guess cause I make those files on https://github.com/jitsi/jitsi-meet/tree/master/react/features/stream-effects/virtual-background/vendor into angular src folder , after `ng build` , those files cannot be found.

**Comment by clark-97** [comment]
I moved https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/virtual-background/vendor/tflite/tflite-simd.wasm and https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/virtual-background/vendor/tflite/tflite.wasm to server folder from src folder, it seems no error like above. 
but I got another error,  

```
ERROR RuntimeError: memory access out of bounds
    at tflite-simd.wasm:0x141797
    at tflite-simd.wasm:0x1e1d4a
    at Object.push.V6rI.Module._runInference (tflite-simd.js:9)
    at JitsiStreamBackgroundEffect.runInference (JitsiStreamBackgroundEffect.ts:92)
    at JitsiStreamBackgroundEffect._renderMask (JitsiStreamBackgroundEffect.ts:113)
    at JitsiStreamBackgroundEffect._onMaskFrameTimer (JitsiStreamBackgroundEffect.ts:45)
    at Worker.wrapFn (zone-evergreen.js:1218)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27474)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)
    at Worker.globalZoneAwareCallback (zone-evergreen.js:1647)
```
should I move those files on https://github.com/jitsi/jitsi-meet/tree/master/react/features/stream-effects/virtual-background/vendor/models to sever folder?

**Comment by ngzhian** [comment]
That error doesn't seem related to where you serve those files, it's a Wasm memory access out of bounds, something wrong in the code. You can try any of these methods listed in https://emscripten.org/docs/debugging/Sanitizers.html to try and track down this failure. I think you can also ask on jitsi-meet repository how to set this up.

**Comment by rossberg** [comment]
Closing as answered / off-topic for this repo.
