### ISSUE TITLE
Ready to flip the default branch to main

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/spec#1368]
With https://github.com/WebAssembly/spec/blob/master/.github/workflows/mirror.yml, any pushes to main branch will be mirrored to master, so we are now ready to flip the default branch to main following https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch.
Someone with permissions can try it out, and any problems can be reported to this bug.

**Comment by ericprud** [comment]
> so we are not ready to flip the default branch to main

if you meant "we are *now* ready", feel free to edit in place and delete this comment. (Maybe I have to do the deleting)

**Comment by sunfishcode** [comment]
The default is now `main`. Please report any problems here.

**Comment by rossberg** [comment]
This has happened.
