### ISSUE TITLE
Is it possible that we design a virtual machine to run several wasm module at one time?

### ISSUE THREAD

**Issue by LBruyne** [WebAssembly/spec#1392]
Hi, 
I want to know if it's possible that we design a vm that run several wasm modules at one time.
Actually, we can define some native module initially, so that some auxiliary functions can be used for developers.
A similar reference is JVM.
I believe this VM can be used in popular browsers in the future.

**Comment by LBruyne** [comment]
I'm doing this work on my own now...

**Comment by penzn** [comment]
@LBruyne a pretty recent proposal in https://github.com/WebAssembly/wasi-native-threads would allow that for standalone runtimes.
