### ISSUE TITLE
[Bug Report] Duplicated 0xFC instructions in the "Index of Instructions" page

### ISSUE THREAD

**Issue by asukakenji** [WebAssembly/spec#1400]
In https://webassembly.github.io/spec/core/appendix/index-instructions.html, we can see that the 0xFC instructions with sub opcode 0 to 7 are duplicated.

As we can see in the source code:

https://github.com/WebAssembly/spec/blob/98493151c578434e82558001677d4fc947ba1129/document/core/appendix/gen-index-instructions.py#L334-L341

is a duplicate of:

https://github.com/WebAssembly/spec/blob/98493151c578434e82558001677d4fc947ba1129/document/core/appendix/gen-index-instructions.py#L316-L323

(the only difference is that the L316-L323 use hexadecimal while L334-L341 use decimal) and thus lines L334-L341 need to be deleted.

**Comment by rossberg** [comment]
Thanks, probably a merge artefact. See #1402 for a fix.
