### ISSUE TITLE
[Bug Report] Inconsistent 0xFD instruction names

### ISSUE THREAD

**Issue by asukakenji** [WebAssembly/spec#1401]
The instruction names written on https://webassembly.github.io/spec/core/binary/instructions.html#vector-instructions are different from that written on https://webassembly.github.io/spec/core/appendix/index-instructions.html.

In the "binary" page, the name of `0xFD 0x01` is `v128.load8x8_s`, while in the "index" page, its name is `i16x8.load8x8_s`. According to my observation, `i16x8.load8x8_s` should be the correct name and `v128.load8x8_s` is a typo by copy-and-paste.

Some other instructions have the same issue. Here is a summary of the discrepancies I found:

| Opcode | "binary" page | "index" page |
| --- | --- | --- |
| `0xFD 0x01` | `v128.load8x8_s` | `i16x8.load8x8_s` |
| `0xFD 0x02` | `v128.load8x8_u` | `i16x8.load8x8_u` |
| `0xFD 0x03` | `v128.load16x4_s` | `i32x4.load16x4_s` |
| `0xFD 0x04` | `v128.load16x4_u` | `i32x4.load16x4_u` |
| `0xFD 0x05` | `v128.load32x2_s` | `i64x2.load32x2_s` |
| `0xFD 0x06` | `v128.load32x2_u` | `i64x2.load32x2_u` |
| `0xFD 0x07` | `v128.load8_splat` | `i8x16.load_splat` |
| `0xFD 0x08` | `v128.load16_splat` | `i16x8.load_splat` |
| `0xFD 0x09` | `v128.load32_splat` | `i32x4.load_splat` |
| `0xFD 0x0A` | `v128.load64_splat` | `i64x2.load_splat` |

The source code of the "binary" page could be found here:

https://github.com/WebAssembly/spec/blob/98493151c578434e82558001677d4fc947ba1129/document/core/binary/instructions.rst#L485-L494

while the source code of the "index" page could be found here:

https://github.com/WebAssembly/spec/blob/98493151c578434e82558001677d4fc947ba1129/document/core/appendix/gen-index-instructions.py#L343-L352

**Comment by rossberg** [comment]
Thanks. Actually, `v128.load8x8_s` is the correct name, the instruction table still contained outdated names. See #1402.
