### ISSUE TITLE
Make website adaptive

### ISSUE THREAD

**Issue by vwkd** [WebAssembly/spec#1414]
The website should be readable on a mobile screen without horizontally scrolling the text.

![8492657B-5DB5-450D-BB27-6D1D6E6C8060](https://user-images.githubusercontent.com/33468089/152445034-8cb6fe35-8998-4497-9e81-6f1533b39542.jpeg)

**Comment by rossberg** [comment]
Much of the spec doc will require a certain amount of screen estate. Not sure how feasible this would be, or how to implement it. Closing as "won't fix", but PRs are welcome. ;)
