### ISSUE TITLE
Push a git tag for each W3C spec URL

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/spec#1425]
I find some things confusing to know what was added after MVP. The W3C permalink has an explicit ref to `REC-wasm-core-1-20191205`. However a date encoded permalink isn't precise as that could be the publication date, days or weeks after something was submitted, and the also it could be on another branch. If we had a tag `REC-wasm-core-1-20191205` here, it would be easy to know which things were merged afterwards.

Most notably, I can't really understand if global import/export of mutable globals are post MVP as there's some mixed language, ex https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/ discusses the ability to export definitions after mentioning globals can be mutable, and unlike return values, there's no constraint mentioned. That doesn't mean they are supported, just I am confused and I think if there was a git tag directly matching that version of the href, I could simply see if #814's commit happened after it.

**Comment by codefromthecrypt** [comment]
ps looking at the diff I was able to figure out mutable globals are supported in that draft, by looking to see if the text the PR deleted was in the published thing. Suffice to say a tag would have been easier and less confusing especially as the word MVP had different meanings and people still call 1.0 MVP

Ex. this is not in https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/  so I infer mutable globals are supported
> In the current version of WebAssembly, only *immutable* globals may be exported.

**Comment by rossberg** [comment]
I think this is resolved with our switch to the evergreen model and our new release versioning scheme.

**Comment by codefromthecrypt** [comment]
I'm guessing this is more a won't fix than a resolved. though won't fix is a resolution.

The publication has no link to the actual source. ex if you click source history it goes to main

<img width="420" alt="Screen Shot 2022-08-04 at 8 03 25 PM" src="https://user-images.githubusercontent.com/64215/182796333-afb547b7-366f-40ef-96ea-45db4b0aa42c.png">
 
You can't tell where the spec was linked to in the source tree unless that's done elsewhere in what you've mentioned. If so, please let me know. I wasn't asked, but if was I would suggest that "evergreen" is not the answer to a spec which has w3c process around it. It should be knowable which commit is associated to what phase etc. we may disagree here.

**Comment by codefromthecrypt** [comment]
what I would guess for example, is that https://github.com/WebAssembly/spec/tree/wg-2.0.draft1 is the same as https://www.w3.org/TR/2022/WD-wasm-core-2-20220419/ just I don't have a way to know that without guessing. This is something I feel should be made clear ideally in the history link as it is less guessing.
