### ISSUE TITLE
Is `vectype` part of `valtype`?

### ISSUE THREAD

**Issue by Cyborus04** [WebAssembly/spec#1435]
In the [syntax spec](https://webassembly.github.io/spec/core/syntax/types.html#value-types), `valtype` is defined as `numtype | reftype | vectype`, but in the [binary spec](https://webassembly.github.io/spec/core/binary/types.html#value-types) it is defined as `numtype | reftype`. Is there a reason for this conflict?

**Comment by ngzhian** [comment]
`vectype` should be part of `valtype`, we probably missed this when merging the SIMD proposal into the main spec. Fixed in #1436 .
