### ISSUE TITLE
Strange range in `extmul` definition

### ISSUE THREAD

**Issue by Cyborus04** [WebAssembly/spec#1437]
In [the execution definition for *t<sub>2</sub>*x*N*\.extmul\_*half*\_*t<sub>1</sub>*x*M*\_*sx*](https://webassembly.github.io/spec/core/exec/instructions.html#t-2-mathsf-x-n-mathsf-xref-syntax-instructions-syntax-instr-vec-mathsf-extmul-mathsf-xref-syntax-instructions-syntax-half-mathit-half-mathsf-t-1-mathsf-x-m-mathsf-xref-syntax-instructions-syntax-sx-mathit-sx), it reads:

> Let i\* be the sequence lanes<sub>t<sub>1</sub>xM</sub>(c1)[N : N]
> Let j\* be the sequence lanes<sub>t<sub>1</sub>xM</sub>(c2)[N : N]

This seems to be a range of length 0. Should this be [N : M] instead?

**Comment by ngzhian** [comment]
Yea it looks weird, because the range syntax is `[ start_index : length ]`,  (not `[ start_index : end_index ]`), from https://webassembly.github.io/spec/core/syntax/conventions.html#notation-slice

e.g. `s[4:4] -> s[4] ... s[4+4-1] -> s[4] ... s[7]`

**Comment by Cyborus04** [comment]
Ohh, okay, thanks for clearing that up. 👍🏻
