### ISSUE TITLE
The binary encoding format of the CALL instruction in WASM

### ISSUE THREAD

**Issue by abc767234318** [WebAssembly/spec#1438]
![image](https://user-images.githubusercontent.com/51507451/160793507-f1b23ffe-ebc6-4d19-a6a7-74f5fae99ace.png)
I see that the WebAssembly Specification gives the call instruction format as shown in the figure above.But the call command encoding I looked at with wasm-objdump is shown below.
![image](https://user-images.githubusercontent.com/51507451/160794152-a36767b9-2585-4a9a-9d10-96f1b58a8d3f.png)
Why not 10 01?

**Comment by tlively** [comment]
The `81 80 80 80 00` is a 5-byte LEB128 encoding of 1. Some producers like clang/wasm-ld will use a 5-byte encoding for function indices to allow the linker to patch in arbitrary indices into those locations once it has assigned indices to all functions in the program. If clang only used one byte there but the linker then happened to assign that called function to a large index, the linker would have to move more bytes around to make room for the larger index, which is something linkers typically try to avoid.

**Comment by sbc100** [comment]
Running the binary through `wasm-opt` will remove this padding.    You can also pass `--compress-relocations` to the linker (`-Wl,--compress-relocations` if run via clang), but be aware that this compression will invalidate the DWARF debug information.

**Comment by titzer** [comment]
Indeed, as @tlively said, it's just padding of variable-length integers. Thanks @sbc100 for the tip on having the linker fix it.

**Comment by abc767234318** [comment]
Thank you very much.
