### ISSUE TITLE
Namesubsection not mentioned in the Name Section

### ISSUE THREAD

**Issue by abc767234318** [WebAssembly/spec#1444]
![image](https://user-images.githubusercontent.com/51507451/163565703-50be6e4b-ae9a-4e0f-9dd7-7079c56af861.png)
There are three NamesubSections mentioned here, but I look at my WASM binary and there are other Namesubsections. As shown in the figure below.
![image](https://user-images.githubusercontent.com/51507451/163566351-bcc7bb97-9dda-4c93-ad50-523e98457302.png)
Their ids are 7 and 9. How do I know the binary format of these two NamesubSections?

**Comment by rossberg** [comment]
These are part of the [extended name section proposal](https://github.com/WebAssembly/extended-name-section/blob/main/proposals/extended-name-section/Overview.md) that has not yet been standardised (and apparently been rather inactive).
