### ISSUE TITLE
[bikeshed] Typo in the Abstract

### ISSUE THREAD

**Issue by neauoire** [WebAssembly/spec#1446]
> This document describes version 2.0 of the core WebAssembly standard, a safe, portable, low-level code format designed for efficient execution and compact representation. WebAseembly Core is part of a collection of WebAssembly specifications: the [Core WebAssembly Specification](https://www.w3.org/TR/wasm-core/), the [WebAssembly JS Interface](https://www.w3.org/TR/wasm-js-api/), and the [WebAssembly Web API](https://www.w3.org/TR/wasm-web-api/).

> WebAseembly

**Comment by rossberg** [comment]
Hm, I can't find this in the repo. @ericprud, is that a local change in your fork?

**Comment by neauoire** [comment]
![image](https://user-images.githubusercontent.com/1455726/165813763-a964083b-6fa4-4e9e-9a81-00ca3c30845f.png)

It's still there

**Comment by ericprud** [comment]
Sorry, trying to get back from a bike trip. will check on Mon or Tue

**Comment by ericprud** [comment]
w3c/sphinx-to-tr#3 should fix this. We don't typically re-publish WDs for types, but we also need to set up echidna (auto-publish scripts) so hopefully this artifact will be fixed relatively soon. Any urgency?

**Comment by rossberg** [comment]
@ericprud, can you manually push to fix this?

**Comment by sunfishcode** [comment]
This looks fixed by w3c/sphinx-to-tr#3, and looking at [the latest draft](https://www.w3.org/TR/2024/WD-wasm-core-2-20241130/) the typo is no longer present.
