### ISSUE TITLE
Add a tag for 2.0 draft 1?

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/spec#1457]
Particularly for the purpose of running spec tests, a git tag would be helpful (vs picking an arbitrary commit). This would also be helpful to know which source relates to the draft (ex which template derived the published draft).

This is a more specific request than #1425 as concretely I would like to use this to track what tests define 2.0 compliance even if not a recommendation, yet.

**Comment by rossberg** [comment]
Right, I just created `wg-2.0.draft1` for top of trunk. Unfortunately, I don't know which exact commit @ericprud created the doc from, so there may be some minor deviation. @ericprud, feel free to move the tag to the precise commit.

**Comment by ericprud** [comment]
I believe it was
```
commit ce4b6c4d47eb06098cc7ab2e81f24748da822f20 (HEAD -> main, origin/main, origin/HEAD)
Author: Andreas Rossberg <rossberg@chromium.org>
Date:   Sat Apr 16 02:44:20 2022 +0200
```

**Comment by rossberg** [comment]
Thanks, I moved the tag to that commit.
