### ISSUE TITLE
Is V128 restricted to wasm or Global?

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/spec#1474]
In the current specification, javascript is restricted from any external function definitions that include a v128 value type

> Calling an Exported Function will throw a [TypeError](https://tc39.github.io/ecma262/#sec-native-error-types-used-in-this-standard-typeerror), when parameters or results contains a v128.

https://github.com/WebAssembly/spec/blob/f5a260a2025ba4d7d398654581c7c532e3a2c319/proposals/simd/SIMD.md#module-function-imports

Moreover, the host test only includes V128 as a global type (not a func type)

> VecType V128Type -> Vec (V128 (V128.I32x4.of_lanes [666l; 666l; 666l; 666l]))

https://github.com/WebAssembly/spec/blob/f5a260a2025ba4d7d398654581c7c532e3a2c319/interpreter/host/spectest.ml

It seems like there's an implicit rule that host functions shouldn't use the V128 type, which can make sense as vectorizing via the host feels like it would never be performant. OTOH, there is exposing a global of V128 which is strange without rationale.

Can you please clarify the following?
1. Are languages besides javascript supposed to support V128 param or results and why?
2. What is the use case for a V128 global?

**Comment by codefromthecrypt** [comment]
I did some digging around implementations and still can't figure out the use case for a V128 global.

However, I do see evidence of v128 being unsupported even outside javascript cc @alexcrichton I would really like to have this point clarified before the next draft of the core spec https://github.com/bytecodealliance/wasmtime/blob/321124ad21e40927934c2bee34293019aeca8035/crates/wasmtime/src/func.rs#L1120

**Comment by rossberg** [comment]
Wasm modules can import and export functions or globals using v128 without problems. Only JavaScript can't access it. But it can still instantiate e.g. one Wasm module exporting a v128 global and then another importing that.

**Comment by codefromthecrypt** [comment]
ok so lack of implementation in wasmtime is not something to read into gotcha.

Still would like to know the use case of a v128 global if anyone knows. v128 as defined as vector used for SIMD, doesn't make sense. v128 as opaque bytes for any reason (ex trace ID) makes sense, but it wouldn't make sense to have no means to define it in wasm except via vector initialization..

**Comment by rossberg** [comment]
Why wouldn't it make sense? From Wasm's perspective, it's no different from im/exporting, say, an f64. It's a fully transparent type as far as Wasm is concerned.

**Comment by codefromthecrypt** [comment]
I suppose what's different about v128 vs another routine type is that it is only defined in context of vectorization:
<img width="558" alt="Screen Shot 2022-05-16 at 9 02 28 AM" src="https://user-images.githubusercontent.com/64215/168623547-94faedc2-2ffa-4b87-bb26-15f7be5c40f5.png">

This makes it odd and curious why a global would have a v128 value. Do you think it is otherwise?

**Comment by rossberg** [comment]
Honestly, I don't understand what you are getting at. Maybe my [other reply](https://github.com/WebAssembly/spec/pull/1391#discussion_r873840518) clarifies?

**Comment by rossberg** [comment]
A global does not "process" a value, if that's all you wonder about. It just stores it.

The JS API treats both globals and functions involving v128 alike: you can export both to JS, but you cannot access either in JS – you get a TypeError when calling a function or when accessing a global. But you can pass both to another Wasm module.
