### ISSUE TITLE
Do not use MathML for BNF definitions

### ISSUE THREAD

**Issue by ethindp** [WebAssembly/spec#1494]
Currently the specification uses MathML for grammar definitions of both the text and byte-code forms. Though this might've been done to enhance accessibility, it actually makes it harder to read the spec. As an example, the section for "Administrative Instructions" contains the `instr` production. Normally, I would be able to trivially navigate and read this production in the way its formatted, making it easy to interpret. However, since it uses MathML, my screen reader reads the entire production at once, so I can't navigate the rule by, say, alternatives. I would recommend only using MathML on mathematical operations/formuli/etc., and simply using code blocks for productions and everything else.

**Comment by rossberg** [comment]
Which exact document/link are you looking at, and with what browser? The main doc is produced by Sphinx, and that generates a page that uses the MathJax plug-in, which also controls the use of MathML. I thought that MathJax does not render with MathML by default, since most browsers don't support it properly. Perhaps it does on some browsers. Unfortunately, Sphinx does not provide a way to configure this more fine-grained. Is there perhaps an option to switch it on or off manually via some context menu on the formula?

**Comment by dontcallmedom** [comment]
looking at https://www.w3.org/TR/wasm-core-2/syntax/instructions.html#numeric-instructions, it does indeed use mathjax to generate the list of productions that are formatted via a `<mtable>` which is probably a semantic abuse of that MathML element.

It looks like sphinx has support for a [production list format](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#grammar-production-displays which gets translated into a `<pre>` formatted rendering à la https://docs.python.org/3/reference/compound_stmts.html#index-3

Is the LaTeX-based authoring of the grammar tied to some other uses?

**Comment by rossberg** [comment]
Yeah, but the Sphinx production support is super simplistic, and rendering into `<pre>` way insufficient. It can't express all the attribution we need or the notation. And it would neither allow producing hyper-links nor consistent type-setting. Would it even address the OP's problem?

**Comment by dontcallmedom** [comment]
> Would it even address the OP's problem?

not sure, but hopefully the link to the output example in Python can help assess that aspect.

Looking some more into it, the WebIDL spec has also a grammar definition (although probably less rich than WASM):
  https://webidl.spec.whatwg.org/#idl-grammar

They use a custom post-processor to add links & formatting to the raw input:
  https://github.com/tobie/webidl-grammar-post-processor

(I confess I don't have clarity on what requirements the current solution fulfills, so if my ill-informed input isn't useful, I'll happily leave that thread alone :)

**Comment by ethindp** [comment]
Why not just use standard code blocks? This problem is pretty much a solved one already. Just use a `<code>`...`</code>` block with hyperlinks to productions elsewhere.

**Comment by rossberg** [comment]
@dontcallmedom, no worries, suggestions welcome.

To give you an idea of a more complex example that the grammar markup must scale to, consider e.g. the one [here](https://webassembly.github.io/spec/core/text/instructions.html#control-instructions). I'm afraid we cannot get that without math mode.

**Comment by ethindp** [comment]
@rossberg We can't just use standard ABNF/EBNF formulations?

**Comment by rossberg** [comment]
Well, this is an attribute grammar. So EBNF + attributes and side conditions.

**Comment by rossberg** [comment]
I believe this has been answered.
