### ISSUE TITLE
minor correction to the documentation

### ISSUE THREAD

**Issue by kam1986** [WebAssembly/spec#1505]
I spotted that there in the execution section are integer operations "not" and "andnot", but they are nowhere to be found in the structure section, encoding or any other section.

**Comment by ngzhian** [comment]
They are both used for SIMD instructions, v128.not and v128.andnot https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-vec

**Comment by rossberg** [comment]
Closing as answered.
