### ISSUE TITLE
WASM and SSA form?

### ISSUE THREAD

**Issue by drom** [WebAssembly/spec#151]
May be a question here? Can WebAssembly format hold Static Single Assignment (SSA) based representation? Does it have `opcode` for the Phi function?

**Comment by sunfishcode** [comment]
WebAssembly's local variables are not in SSA form; one can use `set_local` to reassign them new values at any time. SSA-based compilers can [lower into non-SSA form](https://en.wikipedia.org/wiki/Static_single_assignment_form#Converting_out_of_SSA_form) when targeting WebAssembly. Many existing SSA-based compilers that target machine code will already have the ability to do this.

WebAssembly's expression trees do effectively provide a form of SSA, but they are limited to values that are only used once.

**Comment by drom** [comment]
@sunfishcode I guess my question is: does WASM has all needed `opcodes` to store SSA formed code, if someone need to?

**Comment by sunfishcode** [comment]
@drom WebAssembly does not have phi functions. Compilers will need to lower these as part of lowering into non-SSA form. As I mentioned above, compilers built to target machine code will usually have support for doing this already, so there isn't a strong producer-side motivation to add phi functions to WebAssembly.

WebAssembly does have all the operators needed to support code lowered from SSA form though. I am building a [WebAssembly backend](http://llvm.org/viewvc/llvm-project/llvm/trunk/lib/Target/WebAssembly/) for an SSA-based compiler, for example. It relies on the compiler's existing platform-independent support for lowering SSA form, including phi functions, into non-SSA form.
