### ISSUE TITLE
[test] global_i64 inconsistency

### ISSUE THREAD

**Issue by yamt** [WebAssembly/spec#1514]
* global.wast uses global_i64

* imports.wast has it commented out

* "spectest" in sync_index.js/async_index.js doesn't have it

**Comment by rossberg** [comment]
> * imports.wast has it commented out

That's because JS originally couldn't handle it. We should be able to activate these tests nowadays.

> * "spectest" in sync_index.js/async_index.js doesn't have it

That's odd. How does it handle global.wast then? @Ms2ger, do you know?

**Comment by Ms2ger** [comment]
Not off hand - I can try to look into it if that's helpful.

**Comment by rossberg** [comment]
Yeah, that would be great, since I don't really know or use that code and it looks like @bnjbvr is no longer around.
