### ISSUE TITLE
_start export

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/spec#152]
I have seen some talk about a `_start` export and see it mentioned [here](https://github.com/WebAssembly/design/blob/f680241dce374c1645b540507338f23d4bd82d10/Modules.md#imports-and-exports) in the doc. Would be something we could as to the spec? Could it replace `invoke`?

**Comment by wanderer** [comment]
Related: https://github.com/WebAssembly/design/issues/398

**Comment by rossberg** [comment]
See also #146. I don't think a start function is a replacement for `invoke`.

**Comment by jcbeyler** [comment]
I already have this rewrite: https://github.com/jcbeyler/design/commit/c78ac628b88fda1e37f2ca9fb967c87d34bab1a7

I still have not seriously started the ml-proto implementation of it though :)

**Comment by sunfishcode** [comment]
The spec repo now supports the `start` attribute.
