### ISSUE TITLE
Validation of internal globals in const expressions is inconsistent between interpreter and spec

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#1522]
The following WebAssembly module is invalid in the reference interpreter:
```wat
(memory 1)
(global i32 (i32.const 0)
(data (global.get 0) "")
```

This was originally disallowed in https://github.com/WebAssembly/spec/pull/383. However, the test added in that PR was commented out.

However, the spec currently explicitly mentions that [global initializers can only reference imported globals](https://webassembly.github.io/spec/core/valid/instructions.html#constant-expressions), but does not mention anything about the same for data and element segments. [Module validation](https://webassembly.github.io/spec/core/valid/modules.html#valid-module) also seems to use `C` instead of `C'` when validating data/element segments too, indicating that they can access both internal and imported globals.

**Comment by rossberg** [comment]
Indeed. Please see #1525 for a fix.

**Comment by binji** [comment]
Interesting, I would have assumed the spec should be changed, not the interpreter! I guess I should mention that AFAIK all browser engines currently treat using an internal global in a segment initializer as an error. But I suppose it's safe to extend the functionality.

**Comment by rossberg** [comment]
I see! I wasn't aware that browsers agree with the interpreter instead of the spec. I'm also totally fine changing the spec. Since that's just codifying reality then it would be the simpler change. I'll prepare an alternative PR.

**Comment by binji** [comment]
I just tested Chrome, Safari, Firefox and they all seem to agree. Here's the test I was using [segment-init-global.zip](https://github.com/WebAssembly/spec/files/9409507/segment-init-global.zip). It might be worthwhile to see what the other engines do in this case, since I seem to remember @cyborus04 (who originally discovered this issue) mentioning a few that had a different result.

**Comment by Cyborus04** [comment]
Hi! My testing showed that wasm3 and wasmtime agree with the spec, while wasmer agrees with the tests

**Comment by rossberg** [comment]
Thanks @Cyborus04. That makes the issue somewhat less clear-cut. Though arguably, there is a clear majority of implementations agreeing with the tests, so I would still tend towards tweaking the spec. Do you agree?

**Comment by binji** [comment]
Yeah, I think it makes sense to update the spec. I suppose it's worth notifying those two projects too. I've opened new bugs on those projects to track.

**Comment by rossberg** [comment]
Well, in fact, the backwards compatibility requirements for Wasm are even stronger than Rust's. But in this case, even the test suite said otherwise, so one could argue that the spec merely has a typo for saying something else.

In any case, I put it on the agenda for the next meeting.

**Comment by Cyborus04** [comment]
Oh, is it? Interesting. I guess then, it's a question of which one is prescriptive and which is descriptive.
