### ISSUE TITLE
Question about a potential error in spec/document/core/valid/conventions.rst

### ISSUE THREAD

**Issue by WeZZard** [WebAssembly/spec#1538]
I'm reading the core spec recent days. I think there may be a potential error in the last math block in `spec/document/core/valid/conventions.rst` which the first comma(`,`) on the numerator part of the fraction should be a period (`.`).

In detail, the original one is:

```latex
\frac{
  C \vdash \blocktype : [t_1^\ast] \to [t_2^\ast]
  \qquad
  C,\LABEL\,[t_2^\ast] \vdash \instr^\ast : [t_1^\ast] \to [t_2^\ast]
}{
  C \vdash \BLOCK~\blocktype~\instr^\ast~\END : [t_1^\ast] \to [t_2^\ast]
}
```

But I think the correct version is:

```latex
\frac{
  C \vdash \blocktype : [t_1^\ast] \to [t_2^\ast]
  \qquad
  C.\LABEL\,[t_2^\ast] \vdash \instr^\ast : [t_1^\ast] \to [t_2^\ast]
}{
  C \vdash \BLOCK~\blocktype~\instr^\ast~\END : [t_1^\ast] \to [t_2^\ast]
}
```

**Comment by rossberg** [comment]
`C, label <type>` is rather the opposite of `C.label[<index>]`: it adds a label to `C`, not looks one up. The notation is defined near the end of [this subsection](https://webassembly.github.io/spec/core/valid/conventions.html#contexts).

What may be confusing here is that the syntax for label types, `[<valtype>*]`, looks a bit like an indexing operator. But it is the notation for a list. (It admittedly is suboptimal to use brackets for both lists and indexing, but it's so wide-spread that I didn't dare using something less common.)
