### ISSUE TITLE
[test] SIMD f64x2.neg tests require nan and nan:canonical to be the same?

### ISSUE THREAD

**Issue by osa1** [WebAssembly/spec#1542]
Consider these two tests:

- https://github.com/WebAssembly/spec/blob/8a352708cffeb71206ca49a0f743bdc57269fb1a/test/core/simd/simd_f64x2_arith.wast#L5221-L5222
- https://github.com/WebAssembly/spec/blob/8a352708cffeb71206ca49a0f743bdc57269fb1a/test/core/simd/simd_f64x2_arith.wast#L5297

Here's a test file with just the two tests:

```
(module
  (func (export "f64x2.neg") (param v128) (result v128)
    (f64x2.neg (local.get 0))))

(assert_return (invoke "f64x2.neg" (v128.const f64x2 nan nan))
               (v128.const f64x2 -nan -nan))

(assert_return (invoke "f64x2.neg" (v128.const f64x2 nan 1.0))
               (v128.const f64x2 nan:canonical -1.0))
```

The first test expects negation of `nan` to be `-nan`.

The second test expects negation of `nan` to be `nan:canonical`.

So `nan` should be equal to `nan:canonical` for these tests to pass.

When I run the test file with two tests shown above with the reference interpreter it doesn't report any failures.

Is this expected? My understanding from https://webassembly.github.io/spec/core/syntax/values.html and https://webassembly.github.io/spec/core/text/values.html#floating-point is `nan` and `nan:canonical` do not need to be represented as the same value.

**Comment by osa1** [comment]
I think the problem is the f64x2_neg_canon test. It expects negation of an arbitrary nan value to be `nan:canonical`.

**Comment by rossberg** [comment]
Note that `nan:canonical` is a _pattern_, not a singular value. Specifically, it covers both `nan` and `-nan`.

**Comment by osa1** [comment]
But `nan:canonical` has a specific payload, while `nan` doesn't, no? For an operation on `nan` to return canonical nan, the operation needs to modify the payload, which I think generally is not the case elsewhere in Wasm spec. For example `f32.neg` tests do not check this.

To be concrete, here are some positive `nan` values:

- 0b0_11111111_10000000000000000000000 (canonical nan)
- 0b0_11111111_10001110000000000000000
- 0b0_11111111_10001110000000000011100

`nan:canonical` is one of

- 0b0_11111111_10000000000000000000000
- 0b1_11111111_10000000000000000000000

In the test, we expect negation of any of these `nan` values to be `nan:canonical`. That means negation is expected to canonicalize the payload.

**Comment by osa1** [comment]
If we expect negation to canonicalize the payload then I think this test should fail: https://github.com/WebAssembly/spec/blob/8a352708cffeb71206ca49a0f743bdc57269fb1a/test/core/simd/simd_f64x2_arith.wast#L5221-L5222

**Comment by rossberg** [comment]
No, `nan` denotes the positive canonical NaN, while `-nan` is the negative one. For all others, Wasm syntax requires you to write out the payload with `nan:0x....`, see [here](https://webassembly.github.io/spec/core/text/values.html#floating-point).

**Comment by osa1** [comment]
OK, thanks.

So in summary:

- `nan` is positive canonical nan, and can appear in argument position in tests.
- `-nan` is negative canonical nan, and can appear in argument position in tests.
- `nan:canonical` is a pattern that matches `nan` and `-nan` and nothing else.
-  Since `nan:canonical` is a pattern, it can't appear in argument position in tests. It can appear in expected output position.

**Comment by rossberg** [comment]
Correct. Admittedly, the syntax does not make that super-obvious. It grew somewhat organically. :)
