### ISSUE TITLE
Initialization of externref-type tables by an element segment

### ISSUE THREAD

**Issue by keithw** [WebAssembly/spec#1543]
The spec says, "In the current version of WebAssembly, only tables of element type funcref can be initialized with an element segment. This limitation may be lifted in the future." (https://webassembly.github.io/spec/core/syntax/modules.html#element-segments)

I'm confused how to interpret this. E.g., the below test seems to demonstrate initializing a table of element type externref from an element segment. It passes in the reference interpreter, but fails in WABT and maybe elsewhere. (I don't think there are any nonempty externref-type element segments in the current core testsuite, either valid or invalid.) What's the intended behavior?

```wast
(module $m
	(table $t (export "table") 2 externref)
	(func (export "get") (param $i i32) (result externref)
	      (table.get $t (local.get $i)))
	(func (export "set") (param $i i32) (param $x externref)
	      (table.set $t (local.get $i) (local.get $x))))

(register "exporter" $m)

(assert_return (invoke $m "get" (i32.const 0)) (ref.null extern))
(assert_return (invoke $m "get" (i32.const 1)) (ref.null extern))

(assert_return (invoke $m "set" (i32.const 0) (ref.extern 42)))
(assert_return (invoke $m "set" (i32.const 1) (ref.extern 137)))

(assert_return (invoke $m "get" (i32.const 0)) (ref.extern 42))
(assert_return (invoke $m "get" (i32.const 1)) (ref.extern 137))

;; The table (of element type externref) can
;; be initialized with an element segment,
;; which seems to contradict the note at
;; https://webassembly.github.io/spec/core/syntax/modules.html#element-segments

(module
 (import "exporter" "table" (table $t 2 externref))
 (elem (i32.const 0) externref (ref.null extern)))

(assert_return (invoke $m "get" (i32.const 0)) (ref.null extern))
(assert_return (invoke $m "get" (i32.const 1)) (ref.extern 137))
```

**Comment by rossberg** [comment]
You are right, this note is wrong, see #1545. (I don't remember where it came from, perhaps because we didn't have the generalised element syntax at first.)

**Comment by keithw** [comment]
Thanks much. If this is the case, though, I think the spec should definitely have tests for:
- nonempty element segments of type externref (valid)
- attempts to initialize a funcref-typed table with an externref-typed element segment or vice versa (invalid)

I don't think it has either right now.

**Comment by rossberg** [comment]
Well, happy to take a PR. ;)
