### ISSUE TITLE
Binary format issues

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/spec#1551]
In binary format under modules it says [here](https://github.com/WebAssembly/spec/blame/main/document/core/binary/modules.rst#L502)

> All sections can be empty.

It might seem to refer that sections like `code` or `elem` could be seen as vectors. However, there is an outlier — the `start` section, which is explicitly one element. Thus it cannot be empty.

Also, the binary format in the formal notation [indicates](https://webassembly.github.io/spec/core/binary/modules.html#binary-module) that there could be several sections of one kind (again, except for the `start` section). I assume that they are intended to be concatenated probably to serve linking purposes. However, the prose part of the specification specifically states 

> other [non-custom] sections must occur at most once

Am I missing anything? Which is it in the end?

**Comment by rossberg** [comment]
Ah, "empty" here refers to producing the empty byte sequence for a grammar symbol, which is possible for all section symbols, including startsec (and datacountsec, which is of a similar nature). The remark is supposed to point out that even a module where all sections are absent is allowed.

Can you elaborate how you derive that sections (other than custom) can be repeated? The grammar contains each of those sections exactly once.

**Comment by pepyakin** [comment]
> Ah, "empty" here refers to producing the empty byte sequence for a grammar symbol, which is possible for all section symbols, including startsec (and datacountsec, which is of a similar nature). The remark is supposed to point out that even a module where all sections are absent is allowed.

Ah, clear!

And I think I have an answer for my second issue. I interpreted the notation, e.g., `global*: globalsec` to allow 0-N global sections, but now I see that it's the result of that term is a vector of globals.

Thanks!
