### ISSUE TITLE
Phase 4 entry requirements have vauge/unclear wording

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/spec#1556]
From phase 4 entry requirements: https://github.com/WebAssembly/meetings/blob/main/process/phases.md#4-standardize-the-feature-working-group

```
The formalization and the reference interpreter are usually updated (though
these two can be done as part of step 3 at the Working Group chair's discretion).
```

Do we really want to have the word `usually` here?

Is `can be done as part of step 3` typo?  Seems like maybe this should say `phase 4` instead of `step 3`?

**Comment by tlively** [comment]
I'm not sure what "step 3" is referring to there. Changing it to say "phase 4" would make sense to me, but I'd also be ok with removing the exception and making this an unconditional requirement. I believe that's how we've been treating it in practice.

**Comment by rossberg** [comment]
I'd also have a preference for removing the exception.

**Comment by sunfishcode** [comment]
The text in question was replaced in https://github.com/WebAssembly/meetings/pull/1232, and the "usually" is no longer present. See [here](https://github.com/WebAssembly/meetings/blob/main/process/phases.md#4-standardize-the-feature-working-group) for the new text.
