### ISSUE TITLE
Clarify subgroups can have different process rules (e.g. WASI)

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/spec#1559]
I only today found that the proposal rules for WASI are different and arguably incompatible with the rules of WebAssembly.

Notably to advance to stage 4 is different in ways most notably adoption
* WebAssembly requires two or more "Web VMs" to implement
* WASI requires two "independent implementations" *and* two "cloud providers", as well Windows, Linux and MacOS support

I only noticed this in the recent [kv spec](https://github.com/WebAssembly/wasi-kv-store/blob/e0830360a0f0184b991aeb0eb7e6b342ad385e15/README.md#phase-4-advancement-criteria), and I'm not really sure where the rest of the process is defined.

Since WASI is a subgroup, the above implies that subgroups can have different rules. Since WASI hasn't produced a web standard, it is I suppose also relevant to clarify subgroups may create their own non-web standards track standards.

There's a larger question of why WASI is a subgroup instead of independent, and why it is even in W3C, but please don't get distracted by this. The focus of my issue is to make the process here transparent:

I think it is reasonable to have process documentation clarify that subgroups are free to make their own process. I was shocked and I think I wouldn't have been if this were transparent vs a tacit understanding. I think this shouldn't be something left unsaid, in other words, as people make long term decisions based on processes.

**Comment by codefromthecrypt** [comment]
ps feel free to move this if you think it should be in the repo that defines proposal process. I raised it here because I'm not sure where things about subgroups should be.. that the proposal process different is a side-effect of a subgroup having a different standards culture. https://github.com/WebAssembly/meetings/blob/main/process/phases.md

**Comment by penzn** [comment]
Good question. I think the reason why this discrepancy exists is because WASI subgroup is not producing additions to Wasm standard, which is why it is OK for it to have different rules. Other examples of this are Component Model and C API. AFAIK W3C rules allow for production of artifacts outside of core spec under somewhat relaxed process, but I am not sure to what extent this applies to official subgroups.

**Comment by conrad-watt** [comment]
Yes, the Community Group can curate documents that are outside the scope of the W3C-published standard. The [C API](https://github.com/WebAssembly/wasm-c-api) and [tool conventions](https://github.com/WebAssembly/tool-conventions) repos are other examples. I agree that we should clarify (probably in our [subgroup](https://github.com/WebAssembly/meetings/blob/main/process/subgroups.md) document) that subgroups can have a process for developing these documents that is separate from the main Web standards track, although I think it should already be somewhat clear that the main CG process only applies to things that will end up being considered by the WG for W3C publication, given [phase 5](https://github.com/WebAssembly/meetings/blob/main/process/phases.md#5-the-feature-is-standardized-working-group).

**Comment by codefromthecrypt** [comment]
I didn't realize Component Model was not standards track, so you headed off my next question @penzn, thanks.

I think in general folks should refrain from using "standard" jargon in these subgroups, and lean into words like "specification" especially when there is a process around them that is squinty similar to that which results in a standard with a capital S. In marketing it is very easy to mistake every specification done inside the wasm umbrella as a standard even it it is easier for people to understand things like libraries or ad-hoc advice isn't one. Make sense?

**Comment by penzn** [comment]
@codefromthecrypt, actually, I have to walk that back. Even though Component Model introduces things outside the spec, it is a [proposal](https://github.com/WebAssembly/proposals#phase-1---feature-proposal-cg). The difference from the other examples is that it tries to add another specification on top of core spec, that would be standardized. It would have to follow the same path to get to phase 5 as everything else. What was the question you had? 😃

**Comment by codefromthecrypt** [comment]
@penzn my question was if component model was aiming to be a web standard or not (REC), considering its main user WASI isn't aiming there. Since it seems it is I guess it may be meeting both requirements... e.g. the browser side and the cloud side!

Ideal case, is we could have a landscape doc where folks know what is going to be a REC and what never will. Sounds right now that basically WASI is a special case, and other things "proposal" are proposals to end up in a standard.

FWIW I don't think REC/standard does anything magical to make specifications better, but it is clarifying about process.

**Comment by conrad-watt** [comment]
> The Wasm CG currently maintains three documents: the core spec, the JS API, and the Web API

Just to add, documents like the tool conventions repo are also maintained by the CG, and we've [taken votes](https://github.com/WebAssembly/meetings/blob/main/main/2020/CG-04-28.md) on things like the safe C API before. I agree that the final form of WASI doesn't _have_ to be like one of these documents, but I think the high-level point is that it would be business as usual for the CG to host the development of WASI even if it were never to aim for W3C publication.

I think the point of confusion in the OP is that the WASI subgroup is reusing the "phase" language for their own internal "API proposals", which are not CG-level proposals. I personally don't see a major issue with this since we have the canonical list of CG proposals [here](https://github.com/WebAssembly/proposals), but it might be worth a sentence of clarification somewhere.

**Comment by sunfishcode** [comment]
Closing, as the original question here appears answered. Documentation about subgroups or process lives [here](https://github.com/WebAssembly/meetings/tree/main/process), so if anyone has any further questions or concerns, please raise them in [the associated issue tracker](https://github.com/WebAssembly/meetings/issues).
