### ISSUE TITLE
webassembly.github.io links all 404

### ISSUE THREAD

**Issue by hamishwillee** [WebAssembly/spec#1568]
Other than https://webassembly.github.io/spec/ most links appear to be broken. This is what MDN links to when needed. What is the right thing to use instead, or will this be fixed?

The only alternative I'm finding on google search is https://www.w3.org/TR/wasm-core-2/ - most links go to webassembly.github.io

This came up in https://github.com/mdn/content/issues/22908

**Comment by rossberg** [comment]
The site usually works, but apparently, it was accidentally wiped by @ngzhian's [commit](https://github.com/WebAssembly/spec/commit/6127959fd389cbd00a81599e0c90a1653fd65d86) from a few hours ago. I reran CI and is now up again.

Please reopen if you still see problems. Thanks for pointing out!

**Comment by ngzhian** [comment]
Thanks, I think i ran `make deploy` thinking that it will push to my remote.

**Comment by rossberg** [comment]
Yeah, I believe the deploy script is pushing to the `origin` repo by default.

**Comment by hamishwillee** [comment]
Phew! Thanks very much for your quick response.
