### ISSUE TITLE
[text format] Should `else id? instr*` be optional in `if` instructions?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/spec#1569]
The `else` branch is optional in the folded abbreviation and even in the binary format, but surprisingly it appears to be mandatory in the unabbreviated text format.

**Comment by rossberg** [comment]
The optional form is allowed, but defined as an [abbreviation](https://webassembly.github.io/spec/core/text/instructions.html#abbreviations) below, since the abstract syntax does not treat that case specially.

**Comment by tlively** [comment]
Ah, I missed that abbreviation. Thanks!
