### ISSUE TITLE
Load/store default alignment?

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/spec#158]
I can't find anything in the spec interpreter that defines the default alignment of loads/stores. If an `align=` attribute is omitted, then the memop's align member is `None`, and the evaluator just ignores the alignment. Can it be made more explicit what the default alignment is?

**Comment by lukewagner** [comment]
The evaluator *always* [ignores](https://github.com/WebAssembly/spec/blob/9beff6185524b923664fba23dcab9aba3732c37c/ml-proto/spec/eval.ml#L194) alignment. The intention is that `None` means "no hint" and therefore natural alignment.  But I guess I can see confusion with `None` meaning "completely unaligned" (i.e., `align=1`), so it'd be just as well to remove the `option` and make `align` an `int` that `parser.mly` fills in when missing.

**Comment by jcbeyler** [comment]
Plus we should perhaps define this in the design no? I looked quickly and did not see much information about the lack of information on alignment and what it implied.

**Comment by lukewagner** [comment]
If we keep alignment an `option`, then yes, it'd make sense for AstSemantics.md to say the hint is optional and, when not present, natural alignment should be assumed.  If the alignment is changed to a non-`optional` int, then it's a syntactic sugar detail of the sexpr language that the `align` immediate is optional.

**Comment by jcbeyler** [comment]
Seems bizarre to me to say that we have to do align for a load but the immediate is optional.

(i32.load align (i32.const 0)) seems just overkill. I really think that the default should be that it is optional and if not there, it is defined in the AstSemantics.md as then meaning the load is of natural alignment.

**Comment by titzer** [comment]
I think Luke was suggesting that the hint missing means that the access is
assumed to be aligned.

So:

(i32.load (i32.const 0))

and

(i32.load unaligned (i32.const 1))

?

**Comment by lukewagner** [comment]
The s-expr language offers a variety of syntactic sugar wherein you can omit things and the obvious default AST node is generated.  Having a missing `align` attribute imply natural alignment seems to be no different.  Thus, `(i32.load (i32.const 0))` would imply `align=4`.  From AstSemantics.md POV (as it is currently written), there is always an alignment immediate, so no need to mention it as optional or say what the default is.  However, as I said above, we could change AstSemantics.md to say "alignment is optional, when missing natural alignment is assumed".  I think it's all just a matter of subjective preference until we get to the binary encoding.

**Comment by rossberg-chromium** [comment]
This has been resolved.
