### ISSUE TITLE
Is this explained in detail in spec?  (in the prescribed order)

### ISSUE THREAD

**Issue by 1046102779** [WebAssembly/spec#1600]
https://www.w3.org/TR/wasm-core-2/binary/modules.html#binary-module

The preamble is followed by a sequence of [sections](https://www.w3.org/TR/wasm-core-2/binary/modules.html#binary-section). [Custom sections](https://www.w3.org/TR/wasm-core-2/binary/modules.html#binary-customsec) may be inserted at any place in this sequence, while other sections must occur at most once and **in the prescribed order**. All sections can be empty.

I don't see a relevant specific order requirement in the specification?

**Comment by rossberg** [comment]
The actual order is given by the grammar that follows this explanation.

**Comment by 1046102779** [comment]
> The actual order is given by the grammar that follows this explanation.

If there is no spec and it is up to the implementer to interpret it, then all implementers will follow the broadest spec (that is, there is no order), otherwise there may be incompatibility.

**Comment by rossberg** [comment]
Sorry, I may not have been clear, the grammar normative, so it _is_ the specification.

**Comment by 1046102779** [comment]
In addition to custom `section`, other `sections` must strictly increase in accordance with the `section` id.

**Comment by rossberg** [comment]
Yes, this is also a consequence of the specified binary grammar and the order in which the different sections appear in it. Can you clarify what you think is left undetermined by the grammar?

**Comment by tlively** [comment]
There may be some confusion about what @rossberg means by "grammar." He's not referring to the English language grammar, but rather the technical grammar given for the WebAssembly language.

**Comment by 1046102779** [comment]
When we implement the WebAssembly bytecode interpreter, must we read and parse it in the order of mandatory increment of section id?

For example: when the import section with `section id`=2 is read sequentially, must the next section ID read be 3 (`Function Section`) instead of other section IDs?

Also when encoding, must we serialize and write bytecodes in the strict increasing order of WebAssembly bytecode segment IDs?

**Comment by rossberg** [comment]
Closing as answered.
