### ISSUE TITLE
Incorrect reduction rule for exiting a block normally

### ISSUE THREAD

**Issue by HMPerson1** [WebAssembly/spec#1605]
The spec currently lists a [reduction rule](https://webassembly.github.io/spec/core/exec/instructions.html#exiting-xref-syntax-instructions-syntax-instr-mathit-instr-ast-with-label-l): https://github.com/WebAssembly/spec/blob/51ff50a1f4f580e8d3bc185fd83479fdbb62ca7a/document/core/exec/instructions.rst#L2878 (i.e. there *must* be exactly `n` values on the stack)
This line was recently changed in #1564.

In the WebAssembly paper (Bringing the Web up to Speed with WebAssembly), this rule is listed as:
![image](https://user-images.githubusercontent.com/2219904/219846003-cb2aaa18-08e9-435d-9cbb-42a4467b7910.png)
(i.e. leave stack untouched)
(This matches the copy of this rule in the runtime section (#1152) and in both formalizations of the spec ([coq](https://github.com/WasmCert/WasmCert-Coq/blob/df58f3517170fa3cf8b9206ec86f8d7ce66a57d2/theories/opsem.v#L108), [isabelle](https://github.com/WasmCert/WasmCert-Isabelle/blob/f61ec8eab5d551347a268e858e83b7ac7da0d8b5/WebAssembly/Wasm.thy#L168)))

My understanding is that the arity of a `label` describes the number of values that should be kept on the stack when *breaking*, not when exiting normally, since a `loop` [reduces to](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-loop-xref-syntax-instructions-syntax-blocktype-mathit-blocktype-xref-syntax-instructions-syntax-instr-mathit-instr-ast-xref-syntax-instructions-syntax-instr-control-mathsf-end) a `label` whose arity is the `loop`'s *input* value count.

This is the same conclusion reached in:
- #608
  - #609

**Comment by rossberg** [comment]
The arity must of course be maintained on every exit from the block, including reaching the end regularly. But soundness of the type system ensures that there are exactly n values in that case. So the formulation of this rule doesn't matter one way or the other. I've gone a bit back and forth on which version I prefer, thus the differences. :)

**Comment by HMPerson1** [comment]
This program
```wast
(loop (result i32) (i32.const 7))
```
[reduces to](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-loop-xref-syntax-instructions-syntax-blocktype-mathit-blocktype-xref-syntax-instructions-syntax-instr-mathit-instr-ast-xref-syntax-instructions-syntax-instr-control-mathsf-end) (m=0, n=1)
```wast
(label_0 {(loop (result i32) (i32.const 7))} (i32.const 7))
```
According to the spec as currently written, this program is now stuck: there is 1 value on the stack but the `label`'s arity is 0.

**Comment by conrad-watt** [comment]
Oops, I agree the current spec text isn't right and I probably should have caught this change in https://github.com/WebAssembly/spec/pull/1564.

**Comment by rossberg** [comment]
Ouch, you are right, I missed that. Will fix.
