### ISSUE TITLE
wasm-js-api-2-fork-exception-handling redefines a bunch of wasm-js-api-2 terms

### ISSUE THREAD

**Issue by tabatkins** [WebAssembly/spec#1611]
I'm not sure what the relative status of these two documents is, but they both claim to be the definition of a bunch of terms, and they're both picked up by WebRef so Bikeshedded specs get linking errors when they link into any of these terms. (I noticed this while building WebIDL, which references `Memory/buffer`.)

Which is definitive? Should we remove one of these from WebRef?

**Comment by dtig** [comment]
I'm not familiar with WebRef, my first guess would be that wasm-js-api-2-fork-exception-handling shouldn't be picked up by WebRef. More details/links would be helpful - is there a published Web spec that runs into linking errors? How does WebRef pick up specs?

**Comment by tabatkins** [comment]
Yes, as I said WebIDL was referencing terms from the spec and had an error as a result.

[WebRef](https://github.com/w3c/webref) relies on the [browser-specs](https://github.com/w3c/browser-specs) project to determine what specs are "relevant for the web" and thus should be crawled for definitions. In this case, <https://webassembly.github.io/exception-handling/js-api/> is the "fork" spec that's duplicating definitions from <https://webassembly.github.io/spec/js-api/>, which is presumably the "core" spec?

Should we ignore one of those?

**Comment by dtig** [comment]
IMO, we should ignore forks for Wasm specs, and only link to the published spec on the main branch. I've filed an issue on the browser-specs repo. Also +@Ms2ger as the author of the linked specs.

**Comment by Ms2ger** [comment]
Hmm, I guess the optimal situation would be that "outside" specs reference the base specs at https://webassembly.github.io/spec/js-api/ / https://webassembly.github.io/spec/web-api/ by default, but proposal-X/web-api should refer to proposal-X/js-api. Not sure if that's easy to do.

**Comment by tabatkins** [comment]
> but proposal-X/web-api should refer to proposal-X/js-api. Not sure if that's easy to do.

It's not, at least currently.

**Comment by tidoust** [comment]
> Which is definitive? Should we remove one of these from WebRef?

See comment in https://github.com/w3c/browser-specs/issues/891#issuecomment-1441931224. The spec is flagged with `"seriesComposition": "fork"` and `"forkOf": "wasm-js-api-2"` properties in browser-specs to make it clear that it a fork. These properties are [copied to the `ed/index.json` file](https://github.com/w3c/webref/blob/1f4188fc2cc36b006c1fa93f4a32f08aac760ca8/ed/index.json#L8537) in Webref as well, and could be used to filter the spec out (or only consider definitions that are new) when building the cross-referencing database
