### ISSUE TITLE
Confusion about the word "canonical" for NaNs

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#1613]
The Wasm spec uses the word ["canonical"](https://webassembly.github.io/spec/core/syntax/values.html#canonical-nan) to describe NaNs in a particular form. I recently spoke with someone who was confused because IEEE 754 also has a concept of a "canonical" representation for a NaN, and it's not the same as the Wasm spec's.

Please consider adding a note to the spec mentioning that IEEE 754's "canonical" and Wasm's "canonical" are different things.

**Comment by rossberg** [comment]
If I read IEEE correctly, then it defines canonical NaN only for decimal formats. Hope #1614 makes sense. @sunfishcode, PTAL.
