### ISSUE TITLE
Is "large" test required for compliance?

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/spec#1619]
Is the br_table "large" test required? Some platforms (e.g. JVM bytecode) simply do not support jump tables that large.

**Comment by sunfishcode** [comment]
I would propose considering it required. It appears to contain 25340 entries, which is large, but not unreasonably large in contexts like binary decoding or lookup tables. Large jump tables can be split up into small jump tables by using eg. binary search with comparisons and branches to split the range into ranges small enough to be encoded.

**Comment by rossberg** [comment]
What would be the max number of entries that you can handle without splitting up the function?

**Comment by SoniEx2** [comment]
less than 16380 (tho at 16380 there wouldn't be space for anything else)

**Comment by rossberg** [comment]
Well, thus my question earlier. Can you find out?

**Comment by SoniEx2** [comment]
looks like we need to optimize wasm2kotlin codegen. it's currently having an overhead of 4 extra bytes per branch - so it only fits about 8190 entries instead of the theoretical 16380. it should be able to do at least 16370 (there's still gonna be a bit of overhead) once we fix this.

will check back in once we have that done.

**Comment by ericprud** [comment]
At some point, we discussed a base conformance plus a small number of features, e.g. "2.0 + FwSimd + TailCall". Would it be useful to consumers to have a sense of the size of the jump table they could expect an implementation to handle? (Also, would it be nice to have a tool that read a .wasm and estimate the features required to execute it?

**Comment by SoniEx2** [comment]
we have managed to compile it with 16148 cases

(kotlinc 1.8 appears to have a bug, where it unnecessarily generates some extra branches, so it does eat at the max a little. kotlin 2.0 (experimental) gets us to 16352.)
