### ISSUE TITLE
return?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/spec#164]
The `exports.wast` testcase has a "return" opcode. Is that part of the spec?

**Comment by kg** [comment]
Hm, it's not in AstSemantics. I think it was before - but there have also been discussions of removing ```return``` in favor of ```break```-with-value, so maybe that was finalized?

**Comment by drom** [comment]
Strange, I can see it in https://github.com/WebAssembly/design/blob/master/AstSemantics.md#control-flow-structures

**Comment by kg** [comment]
Yeah, there it is. I guess GitHub repository search doesn't actually work. :|

**Comment by kripken** [comment]
Ah, I thought a previous discussion said we didn't have it anymore, I must have misunderstood. I guess we were just considering removing it.

**Comment by titzer** [comment]
I actually went all the way and removed it from v8-native, since
break-with-value subsumes it. However, in terms of usability, return is
really nice, so I kind of miss it.

**Comment by jcbeyler** [comment]
Forget usability and say "readability". I have currently left it in my wasm-to-llvm prototype because I find it so much easier to read :)

**Comment by titzer** [comment]
It is also still in the design repo, so I plan to add it back to v8-native.

**Comment by sunfishcode** [comment]
I don't have an opinion yet, but a few observations:

It's in the design repo, but only because it predates statements=expressions, and the design hasn't been updated for that change in general.

Return is non-compositional, for what that's worth.

If the goal is just to make code more readable, an only slightly weaker effect could be achieved by using the existing label name syntax sugar and naming the return label "$return". Disassemblers could do this automatically if they wantef

**Comment by titzer** [comment]
My experience has been that expressing break as return from the outermost
block has been quite tricky. It'd be less of a burden if we were to specify
that every function body is wrapped in an implicit block from which one can
break, but it's still uncomfortably error-prone. Return is
non-compositional across inlining, but still composable within a function
body (i.e. moving an AST that contains a return within a function doesn't
require updating the return). Viewed as labels, return implicitly binds to
the topmost label of the function, and thus is not a free label variable.

**Comment by rossberg-chromium** [comment]
Return stays, closing.

**Comment by sunfishcode** [comment]
For the record, I don't feel this is really settled yet; it's just something we're not really ready to explore while we have so many open questions about the nature of the text format(s).

**Comment by rossberg-chromium** [comment]
@sunfishcode, fair enough. I interpret this specific bug as being about the divergence between spec repo and design doc, which seems resolved for the time being.
