### ISSUE TITLE
Inline element segment abbreviations omit necessary reftype

### ISSUE THREAD

**Issue by tomstuart** [WebAssembly/spec#1656]
Both cases of a table definition’s [inline element segment](https://webassembly.github.io/spec/core/text/modules.html#text-table-abbrev) abbreviation produce syntactically invalid element lists.

### Problem

e.g. `(table $t funcref (elem (ref.func $f) (ref.null func) (ref.func $g)))` (from [elem.wast](https://github.com/WebAssembly/spec/blob/2e8912e88a3118a46b90e8ccb659e24b4e8f3c23/test/core/elem.wast#L84)) is allowed, but the inline element segment abbreviation would rewrite it into `(table $t 3 3 funcref) (elem (table $t) (i32.const 0) (ref.func $f) (ref.null func) (ref.func $g))`, which is a syntax error. The rewritten element list is [missing a `reftype`](https://webassembly.github.io/spec/core/text/modules.html#text-elemlist).

### Solution

Update the expanded syntax to prefix the element list with the `reftype` from the abbreviation syntax. The rewritten result for the above example is then `(table $t 3 3 funcref) (elem (table $t) (i32.const 0) funcref (ref.func $f) (ref.null func) (ref.func $g))`.

### Problem

e.g. `(table $t1 funcref (elem $f $g))` (from [call_indirect.wast](https://github.com/WebAssembly/spec/blob/2e8912e88a3118a46b90e8ccb659e24b4e8f3c23/test/core/call_indirect.wast#L626)) is allowed, but the inline element segment abbreviation would rewrite it into `(table $t1 2 2 funcref) (elem (table $t) (i32.const 0) $f $g)`, which is a syntax error.

The rewritten element list is missing the ‘`func`’ keyword; when an element list is [written as a sequence of function indices](https://github.com/WebAssembly/spec/blob/2e8912e88a3118a46b90e8ccb659e24b4e8f3c23/document/core/text/modules.rst?plain=1#L541-L548), it must generally be preceded by ‘`func`’.

Element segment syntax may [allow ‘`func`’ to be omitted](https://github.com/WebAssembly/spec/blob/2e8912e88a3118a46b90e8ccb659e24b4e8f3c23/document/core/text/modules.rst?plain=1#L550-L561) (“for backwards compatibility with earlier versions of WebAssembly”) only if the table use is also omitted, but the table use is present in this case.

(A minor point is that in this case it also doesn’t make sense for the abbreviation syntax to use the `reftype` production. While an element list consisting of a vector of element expressions can use either ‘`funcref`’ or ‘`externref`’ as its reference type, an element list consisting of a vector of function indices [always uses ‘`funcref`’](https://github.com/WebAssembly/spec/blob/2e8912e88a3118a46b90e8ccb659e24b4e8f3c23/document/core/text/modules.rst?plain=1#L541-L548), so ‘`externref`’ can never occur here.)

### Solution

Update the abbreviation syntax to only allow the ‘`funcref`’ keyword as the reference type instead of the `reftype` production. Update the expanded syntax to prefix the element list with the ‘`func`’ keyword. The rewritten result for the above example is then `(table $t1 2 2 funcref) (elem (table $t) (i32.const 0) func $f $g)`.

**Comment by rossberg** [comment]
Ah, yes, likely a leftover from Wasm 1.0, when the kernel syntax for element segments was different.
