### ISSUE TITLE
Missing `id?` in func specification.

### ISSUE THREAD

**Issue by ht-thomas** [WebAssembly/spec#1661]
This is how the spec defines functions in text format:

functype ::= '(' 'func' t1*:vec(param) t2*:vec(result) ')'

It should be like:

functype ::= '(' 'func' id? t1*:vec(param) t2*:vec(result) ')'

To show that functions can be named as well.

[funcdef](https://webassembly.github.io/spec/core/text/types.html#function-types)

**Comment by rossberg** [comment]
That is the grammar for function _types_. The grammar for functions is [here](https://webassembly.github.io/spec/core/text/modules.html#functions).
