### ISSUE TITLE
Shared memory?

### ISSUE THREAD

**Issue by blitz-research** [WebAssembly/spec#1669]
Hi,

I am using wasm-objdump to view a wasm file generated by emscripten and there seems to be a flag in the 'memory' import for specifying shared memory that doesn't appear to be docced. For example, the output of the memory import generated by emscripten is:

- memory[0] pages: initial=2 max=2 shared <- env.memory

However, the docs for memory limits only mention a single flag indicating the presence of the 'maximum' field:

https://webassembly.github.io/spec/core/binary/types.html#memory-types

Looking at a hex dump, the shared flag appears to be bit 1 of the first byte of the memory import (bit 0 controls the maximum field) and indeed setting this bit does appear to work, but what's the deal here, is 'shared' safe to use? I believe I need to use it if I want multithreading (which I do) but I'm a little nervous about the lack of docs.

One other quicky: what does the lack of a memory maximum mean? Memory can grow as large as it wants, or maximum == minimum?

Bye!
Mark

**Comment by ia0** [comment]
[This](https://github.com/webassembly/threads) is not yet standard but a [proposal](https://github.com/WebAssembly/proposals) in Phase 3, see https://webassembly.github.io/threads/core/binary/types.html#memory-types for the proposed memory type.

**Comment by rossberg** [comment]
To your other question: absence of maximum means no limit (or rather, 2^16).

Closing as answered.
