### ISSUE TITLE
build.py doesn't build tests in subdirectories

### ISSUE THREAD

**Issue by foolip** [WebAssembly/spec#1687]
The tests in https://github.com/WebAssembly/gc/tree/main/test/core/gc aren't build by the `build.py`, which only looks for *.wast files in test/core/:

https://github.com/WebAssembly/gc/blob/ec57b2a506a7e220a1cdb980adc7fdcca8b31d05/test/build.py#L70

Are these tests not being run yet, or should they be moved to the parent directory when they are complete?

**Comment by rossberg** [comment]
That seems to be an oversight. It should probably have been changed in the same way as test/run.py back when SIMD tests where written or merged. I don't know who owns or uses this script.

@eqrion, @Ms2ger, @gahaas, you seem to have touched it last. Any ideas?

**Comment by eqrion** [comment]
I think I touched it just to tweak error reporting. We don't use this script anymore though and have a custom way we run the spec tests in SM.

**Comment by gahaas** [comment]
We are also not using this script in V8. The script should be easy to fix, though, and I think there is value in having this script. I put it on my TODO list to fix it eventually.
