### ISSUE TITLE
[Question] Why we have to push a dummy frame when invoking a function?

### ISSUE THREAD

**Issue by RI5255** [WebAssembly/spec#1690]
The [spec](https://webassembly.github.io/spec/core/exec/modules.html#invocation) says to push a "dummy frame" onto the stack when invoking a function, but I don't see the need for this.

This frame doesn't seem to be used or popped anywhere. Am I missing something?

![Invocation](https://github.com/WebAssembly/spec/assets/92210252/5a506c8e-2fc5-4b68-aa32-cabeab6f5f8b)

**Comment by conrad-watt** [comment]
The WebAssembly spec assumes that _every_ instruction executes inside some frame, even if that instruction (in the case of `invoke`) immediately creates an inner frame where the "real" execution is done. This means that we can treat `invoke` uniformly whether it occur at the top level or within a nested function call. We could relax this assumption to avoid the need for a dummy frame, but this would make the spec less regular in other places.

**Comment by RI5255** [comment]
Thanks for the reply!

I understood that the dummy frame is needed to execute the invoke instruction in the frame.

Then why is there no statement like "pop the dummy frame from the stack" at the end of Invocation , as well as [Instantiation?](https://webassembly.github.io/spec/core/exec/modules.html#instantiation)

![instantiation](https://github.com/WebAssembly/spec/assets/92210252/f98561f0-94ca-44ae-9d5e-5865264b8fa8)

**Comment by conrad-watt** [comment]
I wouldn't be against adding a "pop the dummy frame from the stack" line to Invocation for consistency.

@rossberg just to double-check, would this make sense?

**Comment by rossberg** [comment]
Sounds fine to me. @RI5255, do you want to  do a PR?

**Comment by RI5255** [comment]
Yes I do.  I will do it later.
