### ISSUE TITLE
Activation frames: where's the return arity?

### ISSUE THREAD

**Issue by RobertBaruch** [WebAssembly/spec#1693]
According to the section on Activation Frames:

![image](https://github.com/WebAssembly/spec/assets/1783950/ee435e69-0afc-44f0-b522-17cad4c99d02)

"Activation frames carry the return arity _n_ of the respective function..."

However, the definition of the frame given there doesn't mention _n_ at all.

**Comment by rossberg** [comment]
Ah, good point. That is an oversight from some refactoring long ago. I'll fix it.
