### ISSUE TITLE
Does it differ when I compile codes using `neon` SIMD or `x86` SIMD symbols?

### ISSUE THREAD

**Issue by ryuujo1573** [WebAssembly/spec#1707]
I have some code base with SIMD support via conditional compilation. Do I need to compile them into two different `.wasm` files with sse/neon support?

Or it's better to port existing code to wasm_simd so as to provide maximal boost?

Thanks in advance!

**Comment by rossberg** [comment]
This isn't the right forum for questions like this, but unless you expect your code to run on hardware without vector instructions (where SIMD is likely slower), I'd suggest to simply ship only the SIMD version.
