### ISSUE TITLE
Question about validation of {element, data} segments 

### ISSUE THREAD

**Issue by r1ru** [WebAssembly/spec#1711]
The [spec](https://webassembly.github.io/spec/core/valid/modules.html#valid-module) tells that we have to validate element and data segments under context C' defined as follows.

![context_C](https://github.com/WebAssembly/spec/assets/92210252/bfb73853-308b-478f-9b83-9275f9dfe453)

However, that means the active element and data segments are always invalid, because C'.tables and C'.mems are always empty. Is this a specification error? Or am I missing something?

![validate_elemet_segment](https://github.com/WebAssembly/spec/assets/92210252/39de24f5-5c41-4b5e-9a9f-801da5019a73)

![validate_data](https://github.com/WebAssembly/spec/assets/92210252/efd4e44a-d1dd-451b-bebd-cc9ab779b2c1)

**Comment by rossberg** [comment]
Thanks, that's definitely a bug. Please see #1712 for a fix.
