### ISSUE TITLE
Wrong test cases in memory_init.wast

### ISSUE THREAD

**Issue by RI5255** [WebAssembly/spec#1713]
The following two test cases exist in memory_init.wast

![unknown-data-segment](https://github.com/WebAssembly/spec/assets/92210252/c8b3c8ec-79f9-4513-a818-77a3f7f25282)

![unknown-memory](https://github.com/WebAssembly/spec/assets/92210252/ec850560-789b-46d4-b0f4-ef8b6606fc4d)

https://github.com/WebAssembly/spec/blob/main/test/core/memory_init.wast#L189-L193
https://github.com/WebAssembly/spec/blob/main/test/core/memory_init.wast#L226-L230

However, what is expected in these tests is not consistent with what is expected in binary.wast below.

![datacountsection_required](https://github.com/WebAssembly/spec/assets/92210252/d0bb8934-44f2-4db9-a687-47d26f4d991a)

https://github.com/WebAssembly/spec/blob/main/test/core/binary.wast#L472-L511

These two tests should also fail at the decoding stage because the data count section is not defined.
Therefore, these tests should be modified or deleted.

**Comment by rossberg** [comment]
Hm, I'm confused, can you elaborate what is inconsistent? (Note that the text format has no explicit representation of the data count section, it is implied when there is a non-zero number of data segments.)

**Comment by RI5255** [comment]
Okay, then this is my mistake.
I thoght it is inconsistent because when I input the above memory_init.wast into [wast2json](https://github.com/WebAssembly/wabt/blob/main/docs/wast2json.md), it outputs wasm binaries without the data count section. Probably this is a bug of wasm2json. Sorry.

**Comment by rossberg** [comment]
Well, strictly speaking, the spec requires a data count section iff there is at least one occurrence of a data index in the program, which is the case in the first example. But that also has no data segment, hence it is invalid either way. In practical terms, it doesn't really matter what a tool does in the case of invalid input, so I'm not sure I would necessarily count it as a bug.
