### ISSUE TITLE
test case `as-load-operand` have an error

### ISSUE THREAD

**Issue by ofzo** [WebAssembly/spec#1714]
There seems to be an error in this test case, calling the **as-load-operand** function in Chrome gives a result of 0, whereas the expected value in the test case is 1

https://github.com/WebAssembly/spec/blob/c7eef192b77125b88a4ab3ae7a944d10c0860f55/test/core/block.wast#L392C1-L392C57
```wast
(assert_return (invoke "as-load-operand") (i32.const 1))
```

<img width="688" alt="image" src="https://github.com/WebAssembly/spec/assets/18000037/1e219982-37d1-45b8-a653-08f41e65083a">

**Comment by rossberg** [comment]
Tests are scripts that have to be executed sequentially. In particular, this test invokes `as-store-first` prior to calling this function, which mutates the memory accordingly. Hence everything is working as expected.
