### ISSUE TITLE
[core] SIMD Compare instructions link to the wrong "execution"/"validation" sections

### ISSUE THREAD

**Issue by alimpfard** [WebAssembly/spec#1731]
e.g. `i8x16.eq` links to `vbinop`, but the correct target is `vrelop`.

https://github.com/WebAssembly/spec/blob/360141b009b5b498e02d7f672ee82e7d7bc90937/document/core/appendix/index-instructions.py#L376

**Comment by rossberg** [comment]
Please see #1735.
