### ISSUE TITLE
Test extreme alignments

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/spec#1749]
Currently tests only test alignment slightly greater than usual. It would be useful to test extreme alignments like 9223372036854775808, we think. These can often fail in UBSAN.

**Comment by rossberg** [comment]
Alignments larger than the accessed data width are [invalid](https://webassembly.github.io/spec/core/valid/instructions.html#t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-load-xref-syntax-instructions-syntax-memarg-mathit-memarg). But feel free to create a PR with negative tests.

**Comment by SoniEx2** [comment]
Yes. Check WebAssembly/wabt#2411 for context.
