### ISSUE TITLE
Missing LICENSE file in the document directory

### ISSUE THREAD

**Issue by Moxinilian** [WebAssembly/spec#1758]
The root license file advertises that the specification documents are licensed under W3C Software and Document license, for which more details should be found in a LICENSE file under the `document` directory. However, the file is missing.

I am currently integrating snippets of the specification in the documentation of a WebAssembly runtime I am writing, and details on what the terms of the license are would be much appreciated (in particular, which version of the W3C Software and Document license it is licensed under, and the copyright notice), as this license seems quite complex to abide by.

**Comment by dschuff** [comment]
The W3C-formatted version of our drafts published on Github (https://webassembly.github.io/spec/core/bikeshed/) and on the W3C site (https://www.w3.org/TR/wasm-core-2/) have links to the document license (https://www.w3.org/copyright/software-license-2023/). I agree that this is also worth fixing in the sources though.
