### ISSUE TITLE
[bikeshed] Some potential issues in js-api spec

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/spec#1767]
Running bikeshed on this spec give rise to some errors:

LINK ERROR: No 'idl' refs found for '@@iterator'.
{{@@iterator}}
LINK ERROR: No 'abstract-op' refs found for 'CreateMethodProperty'.
[$CreateMethodProperty$]
Unexported dfn that's not referenced locally - did you mean to export it?
<dfn bs-line-number="744" data-dfn-type="dfn" id="abstract-operation-hostresizearraybuffer" data-lt="abstract operation HostResizeArrayBuffer" data-noexport="by-default" class="dfn-paneled">abstract operation <a data-link-type="dfn" bs-autolink-syntax="[=HostResizeArrayBuffer=]" bs-line-number="~744" data-lt="HostResizeArrayBuffer" href="https://tc39.es/proposal-resizablearraybuffer/#sec-hostresizearraybuffer" id="ref-for-sec-hostresizearraybuffer①" data-silently-dedup="">HostResizeArrayBuffer</a></dfn>

According to the current ecmascript spec, we should be using %Symbol.iterator% instead of @@iterator.

The second may be a typo: perhaps it should be CreateDataProperty. There is no CreateMethodProperty procedure in es262 that I can find.

The third speaks for itself ...

**Comment by Ms2ger** [comment]
> Running bikeshed on this spec give rise to some errors:
> 
> LINK ERROR: No 'idl' refs found for '@@iterator'. {{@@iterator}} LINK ERROR: No 'abstract-op' refs found for 'CreateMethodProperty'. [$CreateMethodProperty$] Unexported dfn that's not referenced locally - did you mean to export it? abstract operation [HostResizeArrayBuffer](https://tc39.es/proposal-resizablearraybuffer/#sec-hostresizearraybuffer)
> 
> According to the current ecmascript spec, we should be using %Symbol.iterator% instead of @@iterator.

https://github.com/tc39/ecma262/pull/1314

> The second may be a typo: perhaps it should be CreateDataProperty. There is no CreateMethodProperty procedure in es262 that I can find.

https://github.com/tc39/ecma262/pull/3279
