### ISSUE TITLE
[js-api] Bikeshed issues on wasm-3.0 branch

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#1770]
The wasm-3.0 branch is the current staging ground for merging phase 4/5 proposals. But after merging multiple proposals, the JS-API build is currently [broken](https://github.com/WebAssembly/spec/actions/runs/10057189453/job/27797623262#step:4:43). Unfortunately, I don't understand why the errors in question show up here when they don't in the originating repos.

Any help from people knowledgeable with Bikeshed would be appreciated.

@Ms2ger, @ajklein

**Comment by Ms2ger** [comment]
The reason for the hard error was a missing `</div>`; the other warnings seem to have been present in the proposal repos.

**Comment by rossberg** [comment]
Thanks a lot!
