### ISSUE TITLE
Possibly incorrect encoding in WAST->JS conversion for elem.wast in wasm-3.0 branch

### ISSUE THREAD

**Issue by ddegazio** [WebAssembly/spec#1776]
I've built the latest wasm-3.0 spec tests as follows:
 - Checkout wasm-3.0 branch (specifically commit 9b20411).
 - Generate JavaScript from tests (`cd test && ./build.py --js out`).

Looking at the generated `out/elem.wast.js`, I'm seeing this line:
```js
// elem.wast:516
assert_invalid("\x00\x61\x73\x6d\x01\x00\x00\x00\x01\x84\x80\x80\x80\x00\x01\x60\x00\x00\x03\x82\x80\x80\x80\x00\x01\x00\x04\x8a\x80\x80\x80\x00\x01\x40\x00\x64\x70\x00\x01\xd2\x00\x0b\x09\x89\x80\x80\x80\x00\x01\x04\x41\x00\x0b\x01\xd2\x00\x0b\x0a\x88\x80\x80\x80\x00\x01\x82\x80\x80\x80\x00\x00\x0b");
```
...which is based on 
```wast
(assert_invalid
  (module
    (func)
    (table 1 (ref func) (ref.func 0))
    (elem (i32.const 0) funcref (ref.func 0))
  )
  "type mismatch"
)
```
As far as I can tell, by specifying `funcref` in this test's element section, it should be encoded using binary format 6:
```
|  6:u32 x:tableidx e:expr et:reftype el*:vec(expr)
=> { type et, init el*, mode active { table x, offset e } }
```
But instead, breaking down the element section in the above binary...
```
\x09                  ;; element section id
\x89\x80\x80\x80\x00  ;; 9 bytes
\x01                  ;; one element
  \x04                ;; element format 4
    \x41\x00\x0b      ;; e:expr = (i32.const 0)
    \x01              ;; el*:vec(expr) size = 1
      \xd2\x00\x0b    ;; el*[0] = (ref.func 0)
```
...it seems we are actually using binary format 4:
```
|  4:u32 e:expr el*:vec(expr)
=> { type (ref func), init el*, mode active { table 0, offset e } }
```
In earlier versions of the spec when format 4 assumed `type funcref` instead of `type (ref func)`, I think this transformation would have been valid. But now, it seems like we need to explicitly encode `funcref`, otherwise we assume the element section's type is non-nullable `(ref func)` - which actually makes this module valid, failing the test.

So this looks to me like there might be an issue with the binary generation of the spec interpreter? Where previously we would've been able to use format 4 as a space optimization, due to a different assumed type we no longer can for this case.

**Comment by rossberg** [comment]
Actually, I think this is a typo in the spec. Format 4 should still expand to funcref = (ref null func). It would be a breaking change if it didn't anymore, because the expression list can legally contain nulls in 2.0.

**Comment by rossberg** [comment]
Should be fixed now.

**Comment by ddegazio** [comment]
Thanks! I think that all makes sense, I'll make sure our implementation agrees. :)
