### ISSUE TITLE
[reference-types] behavior of out-of-bound in table.fill 

### ISSUE THREAD

**Issue by 12101111** [WebAssembly/spec#1779]
https://github.com/WebAssembly/spec/blob/main/proposals/reference-types/Overview.md

> `table.fill` traps when range+length > size of the table, but only after filling range up to size (analoguous to `memory.fill`)

I think the documentation corresponds to the old behavior and has not been updated after https://github.com/WebAssembly/bulk-memory-operations/issues/111

**Comment by rossberg** [comment]
Please see the [README](https://github.com/WebAssembly/spec/blob/main/proposals/README.md): the proposal directory contains archived historical documents that are not updated. The only relevant source of truth is the spec itself, which [specifies](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-table-mathsf-table-fill-x) a bounds check before any write.
