### ISSUE TITLE
Should there be a special case in assert_return for ref.null in the JS spec harness?

### ISSUE THREAD

**Issue by ddegazio** [WebAssembly/spec#1787]
On the wasm-3.0 branch, there's a few cases in the spec tests where an `assert_return` expects to get a `ref.null`, like in [this test from select.wast](https://github.com/WebAssembly/spec/blob/wasm-3.0%2Bannot/test/core/select.wast#L280C1-L280C66):
```wast
(assert_return (invoke "join-funcnull" (i32.const 0)) (ref.null))
``` 
Compiling to JS, this produces:
```js
assert_return(() => call($1, "join-funcnull", [0]), "ref.null");
```
Other special patterns, like NaNs or `"ref.func"`, have [special handling in the test harness](https://github.com/WebAssembly/spec/blob/wasm-3.0%2Bannot/test/harness/sync_index.js#L370-L382) so that we don't literally compare against the string `"ref.func"` or otherwise. For `"ref.null"` though, there is no such case, so returning JS `null` from `join-funcnull` (which as far as I can tell is correct per the JS API spec?) seems to fail the test. Is this intended somehow? Or is the harness just missing another case that checks for JS null values?

**Comment by rossberg** [comment]
Yes, this appears to be an oversight. Would you be interested in creating a PR to fix it?

**Comment by rossberg** [comment]
Okay, I ported the internal test harness to sync/async, which had been out of date. This should work now, please let me know if there still are problems.
