### ISSUE TITLE
[js-api] Memory and table allocation pre-conditions not validated

### ISSUE THREAD

**Issue by bvisness** [WebAssembly/spec#1792]
The [mem_alloc](https://webassembly.github.io/spec/core/appendix/embedding.html#mathrm-mem-alloc-xref-exec-runtime-syntax-store-mathit-store-xref-syntax-types-syntax-memtype-mathit-memtype-xref-exec-runtime-syntax-store-mathit-store-xref-exec-runtime-syntax-memaddr-mathit-memaddr) and [table_alloc](https://webassembly.github.io/spec/core/appendix/embedding.html#mathrm-table-alloc-xref-exec-runtime-syntax-store-mathit-store-xref-syntax-types-syntax-tabletype-mathit-tabletype-xref-exec-runtime-syntax-ref-mathit-ref-xref-exec-runtime-syntax-store-mathit-store-xref-exec-runtime-syntax-tableaddr-mathit-tableaddr) operations in the wasm embedding spec have pre-conditions asserting that the memory and table types are valid. The JS API spec does not actually ensure that these pre-conditions are met, which means that it is not clear which kind of error should be thrown if the type is invalid.

For example, mem_alloc has a pre-condition that the memtype is valid, which means that the limits must be valid within range 2^16. The JS API definition for [`Memory(descriptor)`](https://webassembly.github.io/spec/js-api/index.html#dom-memory-memory) asserts that initial <= maximum, but not that initial <= 2^16 and maximum <= 2^16. What type of error should be thrown if the given memory type is invalid?

(table_alloc technically has the same problem, although EnforceRange makes it impossible to express an out-of-bounds size.)

**Comment by Ms2ger** [comment]
Thanks for pointing this out. Have you tested what browsers do?

**Comment by bvisness** [comment]
Chrome, Firefox, and Safari all seem to throw RangeError, so I guess the best course of action would just be to add a line explicitly stating this in the JS API spec. I should be able to make a PR for this fairly easily in the next few days.

**Comment by Ms2ger** [comment]
Thanks!
