### ISSUE TITLE
Imports tag definition typo?

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/spec#1802]
In section 2.5.12 Imports, the `| tag tagtype` suppose to be `| tag typeidx` I believe.

**Comment by rossberg** [comment]
Can you clarify which document you are looking at? The one in the wasm-3.0 branch of this repo has typeidx there, AFAICS.

**Comment by verbessern** [comment]
WebAssembly 2.0 2024.07.24 PDF

**Comment by rossberg** [comment]
Presumably, that was downloaded from the EH repo, not this one?

That was already fixed in the 3.0 staging branch of this repo, but I just upstreamed the fix to avoid confusion.

**Comment by verbessern** [comment]
I think from https://webassembly.github.io/spec/core/.

**Comment by verbessern** [comment]
Yes, the first page does not contain the node about the EH, and so I have issued it here. Often the first page has a node about the the proposal.

**Comment by rossberg** [comment]
Yeah, it seems like somebody forgot to add the proposal name to the spec config in the EH repo. I just did, for future clarity.
