### ISSUE TITLE
wasm-core-2 Spec 5.5.12. Element Section decoding funcref/func types do not match elem.wast or 3.0 Spec

### ISSUE THREAD

**Issue by kelnishi** [WebAssembly/spec#1854]
When decoding an element section according to [5.5.12. Element Section](https://webassembly.github.io/gc/core/bikeshed/index.html#element-section①), the segment type is incorrectly listed as _func_ `(ref func)` for case 4. This is covered under **elem.wast** and should be  `(ref null func)` like in the 3.0 draft spec. Posted versions of the core 2.0 spec also have a similar discrepancy where both decode case 0 and case 4 are listed as _funcref_ `(ref null func)`. According to **elem.wast** testing, the types of case 0 and case 4 differ and should be `(ref func)` and `(ref null func)`, respectively.

**Comment by rossberg** [comment]
The GC proposal has been merged into the main repo's Wasm 3.0 branch, so the gc repo generally isn't updated with upstream changes anymore. It is correct in the [Wasm 3.0 draft](https://webassembly.github.io/spec/versions/core/WebAssembly-3.0-draft.pdf).

**Comment by rossberg** [comment]
As for the 2.0 spec, that is correct as is, since non-nullable references do not exist in 2.0 yet. The change in 3.0 (and according tests) is a backwards-compatible refinement.

**Comment by kelnishi** [comment]
Thank you for the explanation. I've been building against the gc spec and testing with the gc test suite. Maybe I missed it, but I did not see any information on where to find the appropriate spec for a given test suite. I had just assumed that the test suite from gc would have matched the spec that was also it linked in the gc repo's readme.
