### ISSUE TITLE
runtests.py errors on Linux

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/spec#19]
Running runtests.py produces the following output:
```
// building main.native
SANITIZE: a total of 54 files that should probably not be in your source tree
  has been found. A script shell file
  "/moz/wasm/spec/ml-proto/src/_build/sanitize.sh" is being created. Check
  this script and run it to remove unwanted files or use other options (such
  as defining hygiene exceptions or using the -no-hygiene option).
IMPORTANT: I cannot work with leftover compiled files.
ERROR: Leftover ocamllex-generated files:
  Files lexer.mll and lexer.ml should not be together in .
ERROR: Leftover ocamlyacc-generated files:
  Files parser.mly and parser.ml should not be together in .
  Files parser.mly and parser.mli should not be together in .
ERROR: Leftover object files:
  File memory.o in . has suffix .o
  File arithmetic.o in . has suffix .o
  File parser.o in . has suffix .o
  File script.o in . has suffix .o
  File source.o in . has suffix .o
  File main.o in . has suffix .o
  File print.o in . has suffix .o
  File eval.o in . has suffix .o
  File flags.o in . has suffix .o
  File lib.o in . has suffix .o
  File values.o in . has suffix .o
  File check.o in . has suffix .o
  File error.o in . has suffix .o
  File ast.o in . has suffix .o
  File lexer.o in . has suffix .o
  File types.o in . has suffix .o
ERROR: Leftover OCaml compilation files:
  File types.cmo in . has suffix .cmo
  File values.cmo in . has suffix .cmo
  File ast.cmo in . has suffix .cmo
  File memory.cmi in . has suffix .cmi
  File main.cmi in . has suffix .cmi
  File lexer.cmi in . has suffix .cmi
  File values.cmi in . has suffix .cmi
  File check.cmi in . has suffix .cmi
  File error.cmi in . has suffix .cmi
  File flags.cmi in . has suffix .cmi
  File script.cmi in . has suffix .cmi
  File arithmetic.cmi in . has suffix .cmi
  File eval.cmi in . has suffix .cmi
  File ast.cmi in . has suffix .cmi
  File source.cmi in . has suffix .cmi
  File parser.cmi in . has suffix .cmi
  File lib.cmi in . has suffix .cmi
  File print.cmi in . has suffix .cmi
  File types.cmi in . has suffix .cmi
  File parser.cmx in . has suffix .cmx
  File lexer.cmx in . has suffix .cmx
  File values.cmx in . has suffix .cmx
  File arithmetic.cmx in . has suffix .cmx
  File source.cmx in . has suffix .cmx
  File eval.cmx in . has suffix .cmx
  File flags.cmx in . has suffix .cmx
  File check.cmx in . has suffix .cmx
  File error.cmx in . has suffix .cmx
  File script.cmx in . has suffix .cmx
  File memory.cmx in . has suffix .cmx
  File ast.cmx in . has suffix .cmx
  File print.cmx in . has suffix .cmx
  File lib.cmx in . has suffix .cmx
  File main.cmx in . has suffix .cmx
  File types.cmx in . has suffix .cmx
Exiting due to hygiene violations.
Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
Traceback (most recent call last):
  File "runtests.py", line 67, in <module>
    interpreterPath = rebuild_interpreter()
  File "runtests.py", line 57, in rebuild_interpreter
    raise Exception("ocamlbuild failed with exit code %i" % exitCode)
Exception: ocamlbuild failed with exit code 1
```
Performing `make clean` and then running produces a different set of errors:
```
// building main.native
SANITIZE: a total of 3 files that should probably not be in your source tree
  has been found. A script shell file
  "/moz/wasm/spec/ml-proto/src/_build/sanitize.sh" is being created. Check
  this script and run it to remove unwanted files or use other options (such
  as defining hygiene exceptions or using the -no-hygiene option).
IMPORTANT: I cannot work with leftover compiled files.
ERROR: Leftover ocamllex-generated files:
  Files lexer.mll and lexer.ml should not be together in .
ERROR: Leftover ocamlyacc-generated files:
  Files parser.mly and parser.ml should not be together in .
  Files parser.mly and parser.mli should not be together in .
Exiting due to hygiene violations.
Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
Traceback (most recent call last):
  File "runtests.py", line 67, in <module>
    interpreterPath = rebuild_interpreter()
  File "runtests.py", line 57, in rebuild_interpreter
    raise Exception("ocamlbuild failed with exit code %i" % exitCode)
Exception: ocamlbuild failed with exit code 1
```

**Comment by kg** [comment]
I can't reproduce this. How are you running runtests.py? What versions of python and ocaml?

**Comment by rossberg-chromium** [comment]
On 21 August 2015 at 19:50, Luke Wagner <notifications@github.com> wrote:

> Running runtests.py produces the following output:
>
> // building main.native
> SANITIZE: a total of 54 files that should probably not be in your source tree
>   has been found. A script shell file
>   "/moz/wasm/spec/ml-proto/src/_build/sanitize.sh" is being created. Check
>   this script and run it to remove unwanted files or use other options (such
>   as defining hygiene exceptions or using the -no-hygiene option).
> IMPORTANT: I cannot work with leftover compiled files.
> ERROR: Leftover ocamllex-generated files:
>   Files lexer.mll and lexer.ml should not be together in .
> ERROR: Leftover ocamlyacc-generated files:
>   Files parser.mly and parser.ml should not be together in .
>   Files parser.mly and parser.mli should not be together in .
> ERROR: Leftover object files:
>   File memory.o in . has suffix .o
>   File arithmetic.o in . has suffix .o
>   File parser.o in . has suffix .o
>   File script.o in . has suffix .o
>   File source.o in . has suffix .o
>   File main.o in . has suffix .o
>   File print.o in . has suffix .o
>   File eval.o in . has suffix .o
>   File flags.o in . has suffix .o
>   File lib.o in . has suffix .o
>   File values.o in . has suffix .o
>   File check.o in . has suffix .o
>   File error.o in . has suffix .o
>   File ast.o in . has suffix .o
>   File lexer.o in . has suffix .o
>   File types.o in . has suffix .o
> ERROR: Leftover OCaml compilation files:
>   File types.cmo in . has suffix .cmo
>   File values.cmo in . has suffix .cmo
>   File ast.cmo in . has suffix .cmo
>   File memory.cmi in . has suffix .cmi
>   File main.cmi in . has suffix .cmi
>   File lexer.cmi in . has suffix .cmi
>   File values.cmi in . has suffix .cmi
>   File check.cmi in . has suffix .cmi
>   File error.cmi in . has suffix .cmi
>   File flags.cmi in . has suffix .cmi
>   File script.cmi in . has suffix .cmi
>   File arithmetic.cmi in . has suffix .cmi
>   File eval.cmi in . has suffix .cmi
>   File ast.cmi in . has suffix .cmi
>   File source.cmi in . has suffix .cmi
>   File parser.cmi in . has suffix .cmi
>   File lib.cmi in . has suffix .cmi
>   File print.cmi in . has suffix .cmi
>   File types.cmi in . has suffix .cmi
>   File parser.cmx in . has suffix .cmx
>   File lexer.cmx in . has suffix .cmx
>   File values.cmx in . has suffix .cmx
>   File arithmetic.cmx in . has suffix .cmx
>   File source.cmx in . has suffix .cmx
>   File eval.cmx in . has suffix .cmx
>   File flags.cmx in . has suffix .cmx
>   File check.cmx in . has suffix .cmx
>   File error.cmx in . has suffix .cmx
>   File script.cmx in . has suffix .cmx
>   File memory.cmx in . has suffix .cmx
>   File ast.cmx in . has suffix .cmx
>   File print.cmx in . has suffix .cmx
>   File lib.cmx in . has suffix .cmx
>   File main.cmx in . has suffix .cmx
>   File types.cmx in . has suffix .cmx
> Exiting due to hygiene violations.
> Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
> Traceback (most recent call last):
>   File "runtests.py", line 67, in <module>
>     interpreterPath = rebuild_interpreter()
>   File "runtests.py", line 57, in rebuild_interpreter
>     raise Exception("ocamlbuild failed with exit code %i" % exitCode)
> Exception: ocamlbuild failed with exit code 1
>
> Performing make clean and then running produces a different set of errors:
>
> // building main.native
> SANITIZE: a total of 3 files that should probably not be in your source tree
>   has been found. A script shell file
>   "/moz/wasm/spec/ml-proto/src/_build/sanitize.sh" is being created. Check
>   this script and run it to remove unwanted files or use other options (such
>   as defining hygiene exceptions or using the -no-hygiene option).
> IMPORTANT: I cannot work with leftover compiled files.
> ERROR: Leftover ocamllex-generated files:
>   Files lexer.mll and lexer.ml should not be together in .
> ERROR: Leftover ocamlyacc-generated files:
>   Files parser.mly and parser.ml should not be together in .
>   Files parser.mly and parser.mli should not be together in .
> Exiting due to hygiene violations.
> Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
> Traceback (most recent call last):
>   File "runtests.py", line 67, in <module>
>     interpreterPath = rebuild_interpreter()
>   File "runtests.py", line 57, in rebuild_interpreter
>     raise Exception("ocamlbuild failed with exit code %i" % exitCode)
> Exception: ocamlbuild failed with exit code 1
>
>
You need to do `make distclean`. Ocamlbuild is pretty pedantic about build
artefacts in the src tree, including generated ML files.

**Comment by lukewagner** [comment]
Thanks!
