### ISSUE TITLE
expected binary form for the testsuite

### ISSUE THREAD

**Issue by drom** [WebAssembly/spec#211]
@sunfishcode thank you for maintaining `WebAssembly/testsuite` `*.wast` files . How about releasing expected binary `*.wasm` files to test conversion to from binary format?

**Comment by jfbastien** [comment]
Check out the waterfall:
https://build.chromium.org/p/client.wasm.llvm/console

Click on a green build, [download] link for "Assemble LLVM Torture with s2wasm-sexpr-wasm" (such as for [build #2189](https://storage.googleapis.com/wasm-llvm/builds/git/wasm-torture-s2wasm-sexpr-wasm-2189.tbz2)).

**Comment by sunfishcode** [comment]
@drom The spec does not yet have a definition of the binary format. When it does, I'll add the binary images associated with it to the testsuite repository.

Until then, there are a variety of unofficial collections of .wasm files floating around, however please be aware that the official binary format is still being designed and is likely to have differences from the current prototypes.

**Comment by drom** [comment]
Thank you, @jfbastien @sunfishcode 
Will check other projects, and will wait for more official binary format.

**Comment by titzer** [comment]
Agree with @sunfishcode. We should probably avoid storing .wasm files on disk in any official manner in any of the mainline repositories until it becomes a stable thing.
