### ISSUE TITLE
Add a link to a readable online specification.

### ISSUE THREAD

**Issue by retromodular** [WebAssembly/spec#212]
Despite looking through most of the [WebAssembly repositories](https://github.com/WebAssembly) and related [W3C group](https://www.w3.org/community/webassembly/) documents, I am still unable to locate the WebAssembly specification in a readable form online.

If such as thing exists, could someone please include a link in this repositories README file.

Thanks in advance.

**Comment by JSStats** [comment]
Watch https://github.com/WebAssembly/design/pull/520 which is landing a detailed readable specification for the binary encoding.
