### ISSUE TITLE
Strings - Unicode or C

### ISSUE THREAD

**Issue by fmccabe** [WebAssembly/spec#213]
I cannot locate any specification within the spec regarding strings. So, my questions are:

1. Is the zero-terminated string baked into wasm? (If so, why?)
2. What about Unicode? What is the semantics of a string literal, of a block of memory interpreted as a string?

If this question has already been answered, please point me to the spec.

**Comment by binji** [comment]
Do you mean the string literals in the .wast files? This was discussed in #64 some.

**Comment by fmccabe** [comment]
Thanks. This is part of an answer.
FWIW I believe that the wasm text format MUST define a proper semantics for string literals, and that zero-terminated strings SHOULD NOT be encouraged. (My guess would be that the latter is a losing battle, but most modern programming languages do not expose the layout of string literals directly.)
BTW. At least one of the tests in the test suite bakes in the zero-termination semantics.

**Comment by kg** [comment]
At present the only "strings" formally in wasm are things like import/export names. Those are currently null-terminated. Applications will be able to use whatever string representation they want internally.

**Comment by fmccabe** [comment]
Why are import/export names null-terminated?

**Comment by JSStats** [comment]
@fmccabe Had the same question. Why not use a leb128 to give their length - it would be one byte too for most cases and would not constrain the content. Perhaps it does not compress quite so well, but the imports/exports are not expected to be too large.

**Comment by kg** [comment]
Null terminated strings are smaller, even after stream compression. However, that really only matters if you have a bunch of them. So it would be perfectly reasonable to encode length values for import/export names and most other names in a module.

**Comment by fmccabe** [comment]
If imports/exports have null termination, this must be only a property of the binary encoding of wasm files. 

However, I have seen at least one unit test (https://github.com/WebAssembly/testsuite/blob/master/address.wast) where there are string literals in main code; and the assumption that it was ASCII (i.e., one byte/char) and null-terminated is part of the test.

Either strings *are* permitted in wasm files’ memory sections, in which case string representation *must* be decided, or they should *not* be permitted. There is no middle ground here.

Personally, I can see arguments on all sides. As it happens, I think that a ‘common’ string format is more-or-less inevitable; so it would be better to get in front of that issue.

**Comment by kg** [comment]
That's a misunderstanding of the test case, so thanks for citing the example: The strings in that test case are not null-terminated. The test case defines the size of the heap and then initializes the *start* of the heap with a string literal. The remainder of the heap remains zero-filled as it would if it had no initializer data whatsoever.

So the string isn't terminated at all, it just happens to be followed by zeroes.

**Comment by fmccabe** [comment]
It is still one char/byte though.

**Comment by kg** [comment]
UTF8

**Comment by JSStats** [comment]
@fmccabe The imported `print` function is not part of the wasm standard, so the interpretation it makes of the memory bytes and characters is just a matter of the particular runtime used here for testing.

**Comment by rossberg-chromium** [comment]
Just to clarify what others already said: the S-expression format intentionally is completely agnostic to any specific interpretation of string literals. As far as the implementation is concerned, it's just a sequence of random bytes, including 0-bytes, enclosed in ASCII quotes (and with a special meaning assigned to ASCII backslash values). No 0-byte is implicitly appended. The host can interpret these byte sequences in whatever way it sees fit, be it ASCII or Unicode or EBCDIC.

The `print` function cannot actually print strings, only ints or floats. So not even that currently commits to any specific interpretation.

**Comment by titzer** [comment]
For the binary format, I just did the simplest thing, which was
null-terminated strings. I think we should take the suggestion from
@JSStats to use an LEB128-encoding length first. Then strings can be
uninterpreted sequences of bytes from the point of view of the
decoder/engine.

On Fri, Jan 22, 2016 at 2:14 PM, rossberg-chromium <notifications@github.com

**Comment by rossberg-chromium** [comment]
We decided that the binary format should have leb128 length for strings, no zero terminator.
