### ISSUE TITLE
Formalize S-Expression Syntax grammar. 

### ISSUE THREAD

**Issue by mbebenita** [WebAssembly/spec#218]
I've been prototyping a Bison grammar (which is LR(1)) for the S-Expression Syntax. As far as I can tell, there are situations when the current informal grammar is not LR(1) and needs two tokens of lookahead. For instance, sequences of optional lists of non-terminals cause problems. Here is a snippet of the grammar:

```
local
  : '(' LOCAL type_list ')'
  | '(' LOCAL NAME type ')'
  ;

local_list
  : local
  | local_list local
  ;

local_list_option
  : /* Nothing */
  | local_list
  ;

expression
  : '(' NOP ')'
  ;

expression_list
  : expression
  | expression_list expression
  ;

expression_list_option
  : /* Nothing */
  | expression_list
  ;

func
  : '(' FUNC name_option type_name_option param_list_option 
    result_option local_list_option expression_list_option ')'
                  ^
  ;
```

When the parser is at the `^` location above, it can't determine whether the look-ahead token, `(` in this case, is part of the optional local_list or the expression_list. The parser can either shift and drop down into the `local_list` rule, or reduce `local_list_option` to `Nothing` and move on to `expression_list_option`, thus leading to a shift/reduce error.

In my opinion the AST text format should be really easy to parse and write grammars for. I'm not quite sure how to fix this. One way would be to make the tokens include their opening parenthesis, so `(LOCAL` would be just one token, instead of two `(` and `LOCAL`. This makes the grammar kind of ugly, but would fix a lot of the shift/reduce errors. The other approach would be to avoid optional non-terminals, or include delimiters of some sort.

Ideas?

**Comment by JSStats** [comment]
Could you give an example of the forms that cause problem?

Fwiw I find the function declarations a burden to work with, see my thought at https://github.com/wllang/wll/blob/master/wasm.lisp#L341  The WLL rewrites these when importing wast. For example:

```
(func $_strcmp (($i1 i32) ($i2 i32)) (i32)
  (let (($i3 i32) ($i4 i32) ($i5 i32) ($i6 i32))
      ...
```

This puts the arguments and the results in a fix position and groups them. A function with no arguments or results has empty lists `(func $f1 () () ...)`, and it also groups the local variables although the `let` is omitted if there are none. the `let` will be used for block local variables too.

Given that the wast is temporary it did not seem worth burdening the list with a change request, and there are probably may subjective opinions.

**Comment by mbebenita** [comment]
This is actually a good description of the [problem](https://books.google.com/books?id=nYUkAAAAQBAJ&pg=PA191&lpg=PA191&dq=statement:+command+optional_keyword+%27(%27+identifier_list+%27)%27&source=bl&ots=VV7zqi4B5p&sig=UzH37V6X39bDgeDcrItj9uiEBfw&hl=en&sa=X&ved=0ahUKEwid-cXghcfKAhXByIMKHWbFBk0Q6AEIHzAA#v=onepage&q=statement%3A%20command%20optional_keyword%20'('%20identifier_list%20')'&f=false):

From the example in the book:
```
statement
  : command optional_keyword '(' identifier_list ')'  // Rule 0
  ;

optional_keyword
  : /* blank / epsilon */ // Rule 1
  | '(' keyword ')'       // Rule 2
```

With one token of look-ahead `(`, you can't tell if you should take Rule 1 (since you are now seeing the `(` token before the identifier_list) or Rule 2 because it's the beginning of the optional_keyword production.

Bison usually picks either to reduce or shift if there is a conflict, however left unresolved this usually confuses the parser. For example, it can't parse:

```
(module
  (func (param $i i32))
)
```

I think adjusting the grammar to fix and group the position of optional non-terminals would solve this problem.

**Comment by rossberg-chromium** [comment]
I'm not sure I understand the problem. Parsing S-expressions _is already_ implemented using Yacc in ML proto, see the grammar starting here:

https://github.com/WebAssembly/spec/blob/master/ml-proto/host/parser.mly#L133

Other than a single use of `%prec` (which could be avoided by a simple grammar transformation) there is nothing magical about this grammar. Why can't you just copy it?

@jfbastien, the motivation for the somewhat verbose function parameter syntax is the desire to avoid untagged S-expression nodes, which are kind of problematic.

**Comment by kg** [comment]
> Other than a single use of %prec (which could be avoided by a simple grammar transformation) there is nothing magical about this grammar. Why can't you just copy it?

@mbebenita's grammar appears to be much simpler than our mlyacc grammar, which is a pretty useful trait to have. Our sexpr grammar is a monster and will only get worse as time passes.

Is the ocamlyacc grammar used in ml-proto compatible with other yacc implementations? If it's not, addressing that would be one way to promote reuse.

**Comment by rossberg-chromium** [comment]
@kg, yes, the grammar mechanism (and even syntax) of ocamlyacc is exactly the same as for C Yacc.

I haven't seen @mbebenita's grammar, but the snippet above looks pretty similar to what we have. I don't think there is much room to simplify. The size of the grammar reflects the size of Wasm.

**Comment by kg** [comment]
> @kg, yes, the grammar mechanism (and even syntax) of ocamlyacc is exactly the same as for C Yacc.

Maybe I wasn't specific; I was asking whether @mbebenita could actually just lift our existing grammar wholesale and use it. I see a bunch of ML inside the grammar, so I'm not sure how you would use it in C or some other environment.

> I don't think there is much room to simplify. The size of the grammar reflects the size of Wasm.

Need the size of our grammar scale with the number of opcodes and AST primitives we introduce? To name two examples, CSS and XML have fairly general grammars. It's a reasonable compromise/shortcut to bake so many opcode-specific rules and so much parsing logic into our ocamlyacc grammar, but I don't think it's a given that our grammar has to be as complicated as it is.

The sexpr grammar as currently defined is not something you can round-trip in a developer tool unless you've implemented every opcode. It's unfortunate if we can't avoid that.

**Comment by rossberg-chromium** [comment]
@kg, that's apples vs oranges. Of course, a generic S-expression grammar or parser would be smaller, but it's not sufficient. You'd only be moving the complexity to a second pass that actually interprets and restricts the generic S-expression node tree into a syntactically valid Wasm AST. (FWIW, that's how I started out the implementation of ml-proto. But since that second pass is effectively a hand-coded parser, it turned out to be far more monstrous than using yacc properly.)

**Comment by mbebenita** [comment]
Actually I hadn't noticed the Yacc in ML grammar, so I should have looked there first. My main motivation for doing this was to document and clarify the grammar as written in https://github.com/WebAssembly/spec/tree/master/ml-proto/README.md since it looked incomplete and wrong in some cases.

Now, looking at the ML grammar, it looks like the problem I was describing above is solved by accepting any interleaving of `func_fields` (https://github.com/WebAssembly/spec/blob/master/ml-proto/host/parser.mly#L293), so both of these function definitions parse.

```
(func (result i32) (param $i i32))
(func (param $i i32) (result i32))
```

**Comment by binji** [comment]
You may also want to take a look at the bison parser in sexpr-wasm. It doesn't match the spec interpreter's parser exactly, as I've changed most of the right recursion into left recursion. This made it easier to append values to a dynamic array as opposed to prepending everything (the spec interpreter uses singly-linked lists for most things).

One unfortunate side-effect is that I had to explode the combinations of optional func fields (see https://github.com/WebAssembly/sexpr-wasm-prototype/blob/master/src/wasm-parser.y#L618).

**Comment by rossberg-chromium** [comment]
This seems to be resolved, closing.
