### ISSUE TITLE
Improve error message for `arity mismatch`

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/spec#230]
I'm running test pr44942.c.s.wast from https://storage.googleapis.com/wasm-llvm/builds/git/wasm-torture-s2wasm-2718.tbz2 and the error message is just `arity mismatch`. It would be nice to also know which function (`test1` in this case) and the declared parameter count versus how many arguments were given.

That's a bug in the toolchain, I'll fix it :-)

FWIW I just did something similar here:
https://github.com/WebAssembly/binaryen/commit/4044cbd8fe593a118456079eaddfb393c84b9e76
But ocaml makes me sad :)

**Comment by rossberg-chromium** [comment]
That behaviour has been gone for some time.
