### ISSUE TITLE
Add `--entry` command line parameter

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/spec#231]
I'd like to be able to invoke `wasm.opt awesome.wast --entry main` and automatically get `main` invoked (as if `awesome.wast` had `(invoke main ...)`). This is desirable because I already have valid `.wast` files (and create `.wasm` binaries with them), and `invoke` is an extra for spec's convenience which isn't valid `.wast`. It's similar to how C programs by default have `main` as an entry point and UNIX-y environments `_start` (which then calls `main`).

binaryen's interpreter supports a similar option, and automatically figure out the number of parameters for main (because the export sometimes has 0, 1, or 2 parameters):
https://github.com/WebAssembly/binaryen/commit/c0c40ceaf1c5e2c4fc966b36ec04592e6c67979f

**Comment by haxxpop** [comment]
lgtm

**Comment by sunfishcode** [comment]
How does this relate to https://github.com/WebAssembly/design/pull/495?

**Comment by kripken** [comment]
What do you mean by `wasm.opt`? We don't have a tool by that name currently?

**Comment by haxxpop** [comment]
@kripken it's from `make opt` (the native version of wasm)
@sunfishcode I think that is exactly what @jfbastien means. However, that feature has not been implemented in `spec` yet. I would probably implement it soon, if you want :)

**Comment by kripken** [comment]
@haxxpop oh right, thanks!

**Comment by sunfishcode** [comment]
@haxxpop Yes, it would be good to keep the spec and the design in sync, rather than having them each do their own thing. Thanks!

**Comment by jfbastien** [comment]
That's what binaryen-shell does now, and it's convenient. We can also standardize on invoke or some declarator for entry point, but *right now* I'd like something and I'd like it to be uniform between tools, so IMO agreeing with the design isn't as high priority as getting things working.

**Comment by lukewagner** [comment]
In the interim before `start` is implemented in ml-proto, seems easy enough to work around in the harness by appending `(invoke blah)` to the .wast.

**Comment by rossberg-chromium** [comment]
I'll look into it.

**Comment by jfbastien** [comment]
It seems like renaming "invoke" to "start" and enforcing that there's just one is the best approach. I'll add support for "start" to binaryen.

**Comment by rossberg-chromium** [comment]
I actually think that 'invoke' makes much more sense, since you can invoke any exported function. You can just as well allow multiple --invoke parameters on the command line. This is somewhat orthogonal to the start function.

**Comment by jfbastien** [comment]
Supporting "start" from binaryen is indeed orthogonal to adding command-line parameters to spec.

I'd rather call the parameter `--entry` though, since binaryen-shell already uses that name and it's consistent with Linux-y things.

**Comment by jfbastien** [comment]
I opened a PR to add start to binaryen: https://github.com/WebAssembly/binaryen/pull/182

**Comment by sunfishcode** [comment]
With `start` now in both design and spec, is this issue still needed?

**Comment by jfbastien** [comment]
No, closing.
