### ISSUE TITLE
Inconsistency with "if" operator

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#275]
The spec `if` operator introduces a new branch depth for the `then` and `else` arms, but I don't see this specified anywhere in the AstSemantics doc. This is also inconsistent with how the binary format is currently implemented (in at least v8, probably other engines too).

I've ended up hacking around this in sexpr-wasm, but it would be nice to introduce some consistency here. AIUI, this was added in preparation for the switch to postorder; perhaps it should be in a `binary_0xb` branch?

**Comment by rossberg-chromium** [comment]
Yes, we talked about making this change in February, in order to make all blocks have labels consistently. But in the light of WebAssemply/design#652, it might make more sense not to do it. Let's see where we end up with that one.

**Comment by rossberg-chromium** [comment]
Decided to keep the if-labels.
