### ISSUE TITLE
ocaml build warning re multiple modules named Format

### ISSUE THREAD

**Issue by mbodart** [WebAssembly/spec#281]
I'm not an ocaml expert, so someone who is might want to weigh in on this build warning:

File "host/format.d.cmo", line 1:
Warning 31: files host/format.d.cmo and spec/ocaml/ocaml-4.02.2/../install/lib/ocaml/stdlib.cma(Format) both define a module named Format

If it's not problematic, feel free to just close this issue.

**Comment by rossberg-chromium** [comment]
Yeah, it's not a big issue, but I should find another name nevertheless...

**Comment by kmiller68** [comment]
It seems this build warning is being converted into a fatal error for me. I get:

File "host/format.d.cmo", line 1:
Warning 31: files host/format.d.cmo and /usr/local/lib/ocaml/stdlib.cma(Format) both define a module named Format
File "_none_", line 1:
Error: Some fatal warnings were triggered (1 occurrences)

Interestingly I only experience this issue when building the bytecode version. The native build works fine. Is there any workaround for the build error? I haven't used ocamlbuild in years, so I no longer remember how it works (I'm not sure I even understood how it worked then...)

**Comment by rossberg-chromium** [comment]
@kmiller68, weird. In any case, I just (finally) pushed a change renaming the module to make the warning go away.
