### ISSUE TITLE
Update grammar in ml-proto/README.md to match test suite

### ISSUE THREAD

**Issue by anon437843** [WebAssembly/spec#293]
There are multiple files in the test suite which do not match the grammar in ml-proto/README.md. Likely this is just because that file is outdated and needs to be updated.

Problems I've noticed so far:

- `<import>` production:
 - ml-proto/README.md specifies this production as `import:  ( import <name>? <string> <string> (param <type>* ) (result <type>)* )`
 - ml-proto/test/func_ptrs.wast includes the following: `(import $print "spectest" "print" (type 6))`
 - Suggestion: Update README.md to make the production: `import:  ( import <name>? <string> <string> <type>? (param <type>* ) (result <type>)* )`

- `<func>` production (and possibly other productions that use `<name>`)
  - ml-proto/README.md specifies this production as `func:   ( func <name>? <type>? <param>* <result>? <local>* <expr>* )`
  - ml-proto/test/block.wast includes the following: `(func "singular" <...> )`
  - Suggestion: Update README.md to replace the `<name>` non-terminal with the `<string>` non-terminal; otherwise update the test suite to ensure that all function names are productions of `<name>`

**Comment by rossberg-chromium** [comment]
Thanks! These should be fixed now in the README (and a couple of related issues).
