### ISSUE TITLE
multiple blocks can have the same label. Is this correct?

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/spec#303]
multiple blocks can have the same label. Is this correct behavior?
example
```
(module
  (start $main)
  (func $main 
    (block $0 
        (block $0 
         (br $0)
        ))))
```

**Comment by kripken** [comment]
I believe so. The name is scoped, so the `br` sees the closest one to it, basically.

**Comment by rossberg-chromium** [comment]
Right, labels simply use ordinary lexical scoping.
