### ISSUE TITLE
Stack branch type checking of call_indirect

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#318]
Type checking of call_indirect on the stack branch is currently defined as:

```
  | CallIndirect x ->
    let FuncType (ins, out) = type_ c.types x in
    (ins @ [I32Type]) --> Stack out
```

Which means the table index comes last (i.e. is on the top of the stack), is that correct? This is inconsistent with the binary format 0xb where the function index is first. Though I've also noticed that this isn't specified in the binary format design docs: https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#basic-operators-described-here.

Is this also changing with binary_0xc, or is this a bug?

**Comment by kripken** [comment]
I believe this is an intentional change, yes, to make `call_indirect` more like `select`, `br_table`, etc. The change showed up in https://github.com/WebAssembly/spec/commit/b155302bec5782af2c7d90898d97f976a71c25e8 together with test changes for it.

**Comment by binji** [comment]
OK, that makes sense, kind of.

**Comment by rossberg-chromium** [comment]
Yes, we decided to make this change for 0xC. Somebody still has to write the PR, though. I can do that.

**Comment by rossberg-chromium** [comment]
See WebAssembly/design#758.

**Comment by rossberg-chromium** [comment]
Design repo has been updated.
