### ISSUE TITLE
Memory sizes "up to 4 GiB"

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#327]
The design documents describe wasm32 as supporting memory up to 4 GiB in size. While a 32-bit underlying platform would not be able to efficiently support such a size, a 64-bit one theoretically could, and it seems unnecessary for the spec to prohibit it.

Of course, there are reasons why this might be awkward for some 64-bit implementations too, but the would not be required to support the full 4 GiB range if they were unable to, as available resources are always subject to implementation and environment limitations.

Currently, memory.wast in the testsuite has a test which tests that "memory size must be less than 65536 pages (4GiB)". I propose modifying the test to test for "less than or equal to 65536" instead.

**Comment by rossberg-chromium** [comment]
Sounds good to me.

**Comment by rossberg-chromium** [comment]
Changed on binary-0xc branch.
