### ISSUE TITLE
If label is in scope in if condition

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#339]
This program
```
(module
  (func (export "foo") (result i32)
    (block $purple
      (if $if (br $if) (return (i32.const 0)) (return (i32.const 1)))
      (return (i32.const 2))
    )
    (return (i32.const 3))
  )
)
```
validates and returns 3 in ml-proto in the block-sigs branch. This is surprising, since it suggests that control is being transfered to the $purple label, even though there is no fallthrough path to the $purple label and no branch syntactically mentioning $purple. I believe the desired behavior here would be to issue an error that $if is not in scope within the `if` condition, which would look slightly counterintuitive, but would make sense given the underlying wasm structure.

**Comment by rossberg-chromium** [comment]
Ah, good catch! Fixed and test added. (Yeah, the counter-intuitivity you mention was the reason why I originally had the labels on the arms.)
