### ISSUE TITLE
memop offset is serialized as varuint64

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/spec#340]
The design repo says that memory operations serialize their offset immediate as a `varuint32`, but the ml-proto binary-0xc branch uses `varuint64`. I encounted this as the `script-convert` branch of ml-proto converts [this assert_invalid in address.wast](https://github.com/WebAssembly/spec/blob/binary-0xc/ml-proto/test/address.wast#L34) is serializable, but invalid.

Should ml-proto use `varuint32` for memory access offsets, or should the design repo be changed to use `varuint64`?

And how should the script-convert branch handle this particular `assert_invalid` if the offset were unserializable?

**Comment by rossberg-chromium** [comment]
Yes, I should probably change that and make it an int32.

**Comment by rossberg-chromium** [comment]
Fixed on binary-0xc branch.
