### ISSUE TITLE
Memory import name parsing ambiguity?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/spec#346]
Relevant parts of spec docs:

````
memory_sig: <nat> <nat>?
import:  ( import <string> <string> <imkind> )
imkind:  ( memory <name>? <memory_sig> )
````

Consider this input:

````
(import "module" "base" (memory 0 1))
````

How can one tell what the "0" is? It could either be a numerical name for the 0th memory (i.e. using `<name>?` in imkind) or it could be the first part of the memory sig, assuming we provide the second optional part as well.

**Comment by AndrewScheidecker** [comment]
This isn't a use of a name, it's a declaration of a name: it only accepts `$<...>` or nothing for `<name>?`.

**Comment by kripken** [comment]
It does say though

````
name: (<letter> | <digit> ...
````

so the docs do seem to accept a digit here. Is that just an additional rule not specified in the docs then?

**Comment by AndrewScheidecker** [comment]
Yeah, looks like the docs don't match the code here.

**Comment by rossberg-chromium** [comment]
Yes, the `$` was misplaced in the `<var>` production instead of the `<name>` production. Fixed in binary-0xc README.
