### ISSUE TITLE
JS glue code for i64 a little off

### ISSUE THREAD

**Issue by titzer** [WebAssembly/spec#348]
The spec tool for generating a JS self-contained test has a little bug when it comes to the wrapping of i64 tests: it generates

instance(...blob..., {$$}).exports.run()

But here $$ is the instance, but that also has an exports object, so this should be:

instance(...blob..., {$$: $$["exports"]}).exports.run()

Or the $$ instance should be register'd, which makes the second argument unnecessary.

**Comment by rossberg-chromium** [comment]
Fixed by #349.
