### ISSUE TITLE
ml-proto rejects memories with names

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/spec#353]
If a memory is given a name:
```
(module
 (memory $0 0)
)
```
ml-proto emits a syntax error parsing the name.
However if you define the name along with an export, as in the following test from exports.wast
`(module (memory $a (export "a") 0))`
then it's happy.

**Comment by rossberg-chromium** [comment]
Hm, I can't reproduce that. Both examples work for me on the 0xc branch.

**Comment by dschuff** [comment]
Ah, sorry, the memory has to be exported:
```
(module
  (memory $0 17)
  (export "memory" (memory $0))
)
e.wast:3.28-3.30: syntax error: unknown memory $0
```
So it's not the naming but the reference to the name from the export

**Comment by rossberg-chromium** [comment]
Ah, okay, thanks. Same problem existed for tables. Fixed.
