### ISSUE TITLE
ocamlfind or no ocamlfind?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/spec#364]
The Makefile says:
```
# This Makefile uses ocamlbuild but does not rely on ocamlfind
# or the Opam package manager.
```
That seems to now be a lie :wink:

**Comment by rossberg-chromium** [comment]
Well, you still need neither, unless you want actually want to build the Opam package. But I agree that the wording could be clarified now.

**Comment by rossberg-chromium** [comment]
Updated the Makefile comment.
