### ISSUE TITLE
Binary Tests

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/spec#393]
It might be nice to have some binary tests. Binaries have a few things that can't be expressed in s-expressions such as a custom section.

**Comment by rossberg-chromium** [comment]
Yes. We had deferred them so far because the binary format was still undergoing many changes. But now might be a good time.

Note that the S-expression format _can_ express binaries, see binary.wast, which might be a good starting place for adding at least basic stuff. Contributions welcome. :)

**Comment by rossberg-chromium** [comment]
Seems like this has been addressed, even though we should have more such tests.
