### ISSUE TITLE
Elements init_expr with get_global

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/spec#396]
Right now the following is invalid in the spec interpreter with error `test.wast:4.21-4.23: invalid module: unknown global 0`
```
(module
  (table 1 anyfunc)
  (global $g i32 (i32.const 0))
  (elem (get_global $g))
)
```

It is valid using wabt wast2wasm.
It also made me realize that there are no tests in this repo testing elements with an init_expr using a global

**Comment by Cellule** [comment]
Oh thanks, I got confused between wabt, the spec interpreter, the design and our implementation.
So the example I gave should be invalid then by spec,
We probably should add some assert_invalid tests to cover non-imported globals in init_expr and also some tests to cover type mismatch of globals used in init_expr

**Comment by binji** [comment]
The wabt bug should be fixed in https://github.com/WebAssembly/wabt/pull/239.

**Comment by rossberg-chromium** [comment]
I assume this one is resolved.
