### ISSUE TITLE
Do elements need to have valid function indices?

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/spec#404]
for example, this seems to be valid currently but would not be valid if function indices had to exist.
```
(module
  (type $T (func (result i32)))
  (table anyfunc (elem 0 $t2 $some_non_existance_index 9999999) )

  (func $t1 (type $T) (i32.const 1))
  (func $t2 (type $T) (i32.const 2))

  (func (export "callt") (param $i i32) (result i32)
    (call_indirect $T (get_local $i))
  )
)
```

**Comment by binji** [comment]
This is already invalid in the spec interpreter:
```
test.wast:3.30-3.55: syntax error: unknown function $some_non_existance_index
```
and if you comment that out:
```
test.wast:4.30-4.37: invalid module: unknown function 9999999
```

**Comment by wanderer** [comment]
ah thanks @binji, it seems to pass through wahbt without error.

**Comment by binji** [comment]
Interesting, I guess there isn't a spec test for this yet. I've got a fix for wabt here: https://github.com/WebAssembly/wabt/pull/250

**Comment by wanderer** [comment]
ill add a test
