### ISSUE TITLE
select validation

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/spec#423]
The spec interpreter accepts the following
```
(module (func
  br 0
  block i32
   br 1
  end
  i32.const 0
  select
  drop
))
```
But rejects the following:
```
(module (func
 br 0
 block f32
  br 1
 end
 i32.const 0
 select
 drop
))
```
`selecttest2.wast:7.2-7.8: invalid module: type mismatch: operator requires [i32 i32 i32] but stack has [_ f32 i32]`
For the second example I believe the `_` should match f32 and be valid, correct? (FWIW wabt's validator accepts that).

**Comment by lukewagner** [comment]
Agreed (and tested in SM with polymorphic-checking patch).

**Comment by rossberg-chromium** [comment]
Correct, thanks! See #424 for a fix.
