### ISSUE TITLE
Remove the test on very big memory?

### ISSUE THREAD

**Issue by bnjbvr** [WebAssembly/spec#429]
There's a test in the core suite that allocates a Memory with [65536 pages](https://github.com/WebAssembly/spec/blob/master/test/core/memory.wast#L5), i.e. 4 GB of memory.

I think [V8](https://github.com/v8/v8/blob/master/src/wasm/wasm-limits.h#L21) and [SpiderMonkey](https://github.com/mozilla/gecko-dev/blob/master/js/src/wasm/WasmBinaryConstants.h#L461) both fail it at the moment, because of internal limits. I don't know what Chakra and JSC allow here.

The spec is explicit that we should allow up to 4 GB in the MVP (wasm32), but if it's a theoretical limit that no browsers achieve in practice, does it make sense to test it? That is, do the browsers need to raise up their limits, or should we comment/remove the test?

**Comment by rossberg-chromium** [comment]
I think you are misreading the test. It does not allocate 4 GB, it only declares an upper limit of 4 GB, but never grows the actual size beyond 0 bytes.

V8 succeeds on this test. I don't think we want to allow engines to fail it.

**Comment by bnjbvr** [comment]
Yes indeed; it's our implementation that is wrong here, thanks for the clarification.
