### ISSUE TITLE
Consistent arity of br_table

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#430]
I was a bit surprised to see this test (https://github.com/WebAssembly/spec/blob/680fa9ac4dada0c85e86a60dc745af495e4a02db/test/core/br_table.wast#L1404) fail on wabt. I guess it's required to have a consistent arity for all br_table targets?

It seems a bit strange to me, considering the equivalent brs work fine:
```
block
  block f32
    f32.const 0
    br 0 ;; or br 1
  end
block
```

Is there a benefit to having the br_table consume the same values for all targets?

**Comment by rossberg-chromium** [comment]
@binji, yes, all targets need to have the same type. If you implement this with an actual jump table then heterogeneous arities would be rather difficult to handle in general (depending on how arguments are passed to the target).

**Comment by binji** [comment]
Yes, I suppose that makes some sense. I assumed that it would be equivalent to dealing with the various stack unwinding depths, but perhaps it's a bit more involved.
