### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cwebber** [WebAssembly/spec#444]
No COPYING or LICENSE File is provided in this repository.  I've considered reading it to do a WASM port to another language, but I'm unwilling to read the source unless it's under some free and open source software license.

**Comment by shurcooL** [comment]
> No COPYING or LICENSE File is provided in this repository.

There is a LICENSE file at the root of this repository:

https://github.com/WebAssembly/spec/blob/master/LICENSE

**Comment by cwebber** [comment]
My bad!  Guess I missed it... sorry!  Thanks for working on WASM :)
