### ISSUE TITLE
Arithmetic with carry

### ISSUE THREAD

**Issue by fmccabe** [WebAssembly/spec#446]
The arithmetic operators do not seem to include an option of external carry, or overflow detect.

Without this, multi-word precision becomes virtually impossible. Yet every actual ISA has it.

**Comment by jfbastien** [comment]
We've usually filed such issues in the design repo: https://github.com/WebAssembly/design
Could you also detail which instructions you propose adding?

**Comment by fmccabe** [comment]
I put it in the spec repo because that is where the spec is being developed.
I will also craft some instruction specs.
———
Frank McCabe
Senior Software Architect
Phone: 650-740 6673 | Email: fmccabe@instartlogic.com <mailto:yourname@instartlogic.com> 
Instart Logic | 450 Lambert Ave, Palo Alto, CA 94306 | instartlogic.com <http://instartlogic.com/>

**Comment by rossberg-chromium** [comment]
Moved to design repo, so closing here.
