### ISSUE TITLE
Invalid grammar for func_sig

### ISSUE THREAD

**Issue by cretz** [WebAssembly/spec#461]
On the interpreter README that has the sexpr syntax, `func_sig` says it can be a type reference OR a param/result set. However https://github.com/WebAssembly/spec/blob/6a01dab6d29b7c2b5dfd3bb3879bbd6ab76fd5dc/test/core/func_ptrs.wast#L18 says otherwise.

**Comment by binji** [comment]
Good catch. You probably have already seen this, but the yacc-like syntax [here](https://github.com/WebAssembly/spec/blob/master/interpreter/text/parser.mly#L417) is quite helpful for resolving these things:

```
...
LPAR FUNC bind_var_opt inline_export type_use func_fields RPAR
...
```

This makes it clear that the `type_use` (e.g. `(type 3)`) must come before the `func_fields` (e.g. `(param i32)`).

**Comment by rossberg-chromium** [comment]
I tweaked the grammar in the README. Thanks for pointing out!
