### ISSUE TITLE
[spec] Graphical issue when horizontal scrolling

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#476]
It doesn't happen on all pages, but I was able to repro on
https://webassembly.github.io/spec/binary/instructions.html#control-instructions by shrinking the horizontal width of my screen.

When scrolling horizontally, the navbar on the left overlaps with the content and looks like a jumbled mess.

**Comment by quinox** [comment]
Example from my screen at full width on [Parametric Instructions](https://webassembly.github.io/spec/text/instructions.html#parametric-instructions):

![screenshot 2017-05-15 at 22 26 42](https://cloud.githubusercontent.com/assets/739770/26077831/c14ffa32-39bd-11e7-9a0e-5237dab47119.png)

**Comment by rossberg-chromium** [comment]
That seems to be a "feature" of the Alabaster theme. I'll see whether it is possible to override the CSS bits that enable this.

**Comment by rossberg-chromium** [comment]
This should be fixed.

**Comment by quinox** [comment]
Works for me, thanks.
