### ISSUE TITLE
[spec] Grammar A+ (mistake?)

### ISSUE THREAD

**Issue by pyfisch** [WebAssembly/spec#495]
The [Grammar](http://webassembly.github.io/spec/syntax/conventions.html) section defines A+ as:

> A+ is a possibly empty sequence of iterations of A. (This is a shorthand for An where n≥1.)

I think this is a copy-paste error and it was meant to say:

> A+ is a sequence of iterations of A with at least one element. (This is a shorthand for An where n≥1.)

**Comment by xor** [comment]
PR#482 took care of it recently.

**Comment by pyfisch** [comment]
Great! How often is the rendered version of the spec updated?

**Comment by xor** [comment]
> Great! How often is the rendered version of the spec updated?

@rossberg-chromium Should have a better idea.

**Comment by rossberg-chromium** [comment]
@pyfisch, for the time being I do it whenever I upload or update a spec PR.
