### ISSUE TITLE
Error object .message value

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/spec#501]
jsapi.js contains tests such as:

    assert_equals(new CompileError("hi").message, "hi");

This seems overly restrictive because it forbids implementations from providing context in `.message`. It's not very useful in this example, but it is useful to provide context when the WebAssembly error types actually occur (e.g. where was that call from, which one was it, etc).

In this specific test, JSC returns the following: `hi (evaluating 'new CompileError("hi")')`

I propose that we loosen the tests to allow this behavior: instead of strict equality we look for the message being contained.

**Comment by MikeHolman** [comment]
I'd prefer if we keep the normal JS Error behavior, which is specified here:

https://www.ecma-international.org/ecma-262/7.0/index.html#sec-error-constructor

**Comment by rossberg-chromium** [comment]
@jfbastien, as far as I can see, the ES spec is pretty clear on this, and the behaviour you're describing is non-conforming.

**Comment by jfbastien** [comment]
We're talking specifically about when the user invokes `new WebAssembly.CompileError("hi")` directly requiring that `.message` stay as-is? That's a totally useless usecase, so I don't mind agreeing to have zero context to it. So if we do this, then I agree the test is OK.

The `.message` generated by WebAssembly implementations themselves, however, have totally unspecified content and can therefore have as much context as we want, correct? There is no portable manner to test for these either.

**Comment by MikeHolman** [comment]
I agree it's not super useful, but the spec is clear on what the contents of message should be when new Error is called, and I don't see a compelling reason to diverge from js.

**Comment by rossberg-chromium** [comment]
@jfbastien, yes, impl-generated messages are free to be anything.

**Comment by jfbastien** [comment]
If we agree that:

1. User-called WebAssembly errors only contain the user-provided message.
2. Implementation-generated WebAssembly errors contain whatever the implementation sees fit, including any context it wants

Then I'm happy to close.
