### ISSUE TITLE
[interpreter] Unable to compile wast.js generated binary in current browsers

### ISSUE THREAD

**Issue by thelonious** [WebAssembly/spec#506]
I'm currently unable to create a new module from the binary generated by wast.js. I've verified this in  the following browsers:

- Brave 0.16.9
- Safari Technology Preview (Safari 11.0, WebKit 12604.1.23.0.4)
- Chrome 59.0.3071.86
- Firefox 53.0.3
- Opera 45.0.2552.888

For reference, I'm using this modified version of the sample code from the interpreter README.md

```
let source = '(module (func (export "f") (param i32 i32) (result i32) (i32.add (get_local 0) (get_local 1))))';
let binary = WebAssemblyText.encode(source);
let module = new WebAssembly.Module(binary);
let instance = new WebAssembly.Instance(module);

console.log("result = %d", instance.exports.f(3, 4));
```

All of the listed browsers complain about the version number. It is `0x0d` and should be `0x01`.

For testing purposes and out of curiosity, I changed [wast.js, line 16902](https://github.com/WebAssembly/spec/blob/master/test/harness/wast.js#L16903) to `u32(1)`. I was then able to run the test code in all browsers without issue. Of course, I could not convert the binary back to an s-expr since the expected version number had been changed.

I would file a pull request for this, but I don't know how the wast.js file is generated. I'm not sure what source file(s) would need to be changed. This also assumes there is no difference between the version 13 and version 1 file formats.

**Comment by rossberg-chromium** [comment]
Right, `wast.js` hasn't been updated in quite a while, #500 should have fixed this.

(To generate `wast.js`, it should be sufficient to say `make wast.js` in the `interpreter` directory (and then copy it over). However, you need BuckleScript installed.)

**Comment by thelonious** [comment]
Ah, OK. I had seen that mentioned in the README, but assumed the code in the repo was up to date.

Unfortunately, I'm not having any luck building wast.js on macOS. It's complaining about not being able to locate `bs-platform/lib/js/curry.js` when BuckleScript is checking dependencies. I'll give it a try on another platform later.

**Comment by thelonious** [comment]
I tried building on Linux and I'm seeing similar issues. Do you know if the wast.js file in the repo was built on Windows?

**Comment by rossberg-chromium** [comment]
I built it on Linux, though I might be using an older version of BS. Maybe it's a problem with the tree shaking I implemented in the build script. What error are you seeing exactly?

**Comment by thelonious** [comment]
I'm seeing a number of things like this currently:
```
[1/66] Building src/lib.cmi
FAILED: src/lib.cmi 
/home/kevin/n/lib/node_modules/bs-platform/bin/bsc.exe -bs-package-name wasm  -bs-package-output commonjs:lib/js/src -bs-no-builtin-ppx-mli -bs-no-implicit-include  -I src  -nostdlib -I /home/kevin/Documents/Projects/spec/interpreter/node_modules/bs-platform/lib/ocaml -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/lib.cmi -c  src/lib.mliast
File "command line", line 1:
Error: Unbound module Pervasives
```

Here's my build environment:
- Ubuntu 64-bit 17.04
- Fresh install of ocaml 4.02.3 and associated native compilers via apt
- node v7.10.0 and npm v4.2.0 installed via [n - node version manager](https://github.com/tj/n)

I installed bs-platform 1.7.4 to match the version used to build `wast.js` in the repo. I installed that globally and linked to that in the `spec/interpreter` directory; otherwise, `brb` couldn't be found. Related to that, I had to change `spec/interpreter/meta/jslib/build.sh` to execute `bsb` instead of `bsb.exe`, which is strange because `bsb` and `bsb.exe` are in the same directory reported by `BSPATH`.

I suspect the issue is some sort of combination of me not knowing ocaml and something odd with using `n` as my node version manager.

**Comment by rossberg-chromium** [comment]
Hm, if it doesn't even find the built-in `Pervasives` module then I suspect an issue with your BuckleScript installation. Hard to diagnose the problem from the distance, though. It may very well have to do with the node setup (I ran with 6.0.0, using nvm). I remember having some difficulties myself with that before. I wish there wasn't a dependency on an entire ecosystem like node just to run a cross-compiler...

**Comment by thelonious** [comment]
FWIW, I just tried using node v.6.11.0 and I get the same result. However, on macOS, I do get further, but I end up erroring out with:

```
/Users/kevin/Documents/Projects/spec/interpreter/_build/jslib/temp.js:11
      throw new Error('missing module: ' + name)
      ^

Error: missing module: curry
```

I'm using `n` there as well. When I looked into that error earlier, it looked like a path issue. The curry file existed, but node wasn't finding it, for some reason.

I'll try using `nvm` and see if I get further using that route. Thanks for the help.

**Comment by thelonious** [comment]
OK, I'm adding one more comment for completeness. I tried using `nvm` instead of `n` on Ubuntu and I'm seeing the same behavior either way: `Error: Unbound module Pervasives`, which, as you said, seems like an issue with the BuckleScript install. Someone had a similar issue and they resolved it be linking to the globally installed module, which is what I have done as well.

**Comment by rossberg-chromium** [comment]
@thelonious, seems the original issue is solved, so I'm closing this.
