### ISSUE TITLE
[spec] Nondescript anchor names

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#508]
I was trying to link to specific sections of the spec document and found that some have unexpected names. For example, in the execution runtime document, the "Stack" anchor is https://webassembly.github.io/spec/execution/runtime.html#index-11. In the same document, the "values" anchor is https://webassembly.github.io/spec/execution/runtime.html#id4.

It seems that https://webassembly.github.io/spec/execution/runtime.html#stack actually does work, so perhaps ReST is just choosing a poor example for the hover anchor? The values example is trickier, since it works too but goes to a different values section.

**Comment by rossberg-chromium** [comment]
These and all similar issues should be fixed by #514, although Sphinx's underlying logic is unclear, so there may still be other problems of this sort.
