### ISSUE TITLE
[spec] The spec is unreadable without JS on

### ISSUE THREAD

**Issue by vflyson** [WebAssembly/spec#524]
Thanks for the website and the docs, but gotta give my feedback and say that It's a bit contradicting to make the spec for a new technology rely on the one it's intended to replace:
https://webassembly.github.io/spec/syntax/conventions.html#grammar-notation is unreadable without JS. 

Specs/docs absolutely have to be portable and readable even with plain text viewers, that thing is hard to use, it should never require anything but plain HTML with a bit of CSS for readability.
Please create some fall-backs to make it readable without JS on (let's save some trees and eyes).

**Comment by jfbastien** [comment]
To be clear, WebAssembly is not intended to replace JavaScript.

I agree it would be nice to have docs that work without JavaScript. It's not, however, something I would prioritize over having a complete spec. I've got a preference for [bikeshed](https://tabatkins.github.io/bikeshed/), but I defer to @rossberg-chromium in choosing how to resolve this issue. Specifically, handling math isn't always feasible in pure HTML as implemented by all browsers (though bikeshed recently gained support).

**Comment by rossberg-chromium** [comment]
I sympathise and would prefer that myself, but the issue is math rendering, and as @jfbastien mentions, plain HTML isn't up to the task. It is possible to render math with images, but the results are usually awful, and hyperlinks would not work. I'm not aware of any working alternative, with any tool. [Insert rant about browser vendors, especially Chrome, who killed MathML.]

That said, you may consider the PDF as a fallback, if that works for you.

**Comment by vflyson** [comment]
I see... and how about SVG, do you think it could be rendered correctly using SVG, or perhaps canvas, with fallback to HTML+JS?

**Comment by jfbastien** [comment]
I think an SVG fallback can definitely be made to work. It's simply not a priority at the moment though. Would that be something you'd be interested in contributing?

**Comment by vflyson** [comment]
Once I pay off my rent and other debts -- sure! Will put it on my list.

**Comment by rossberg-chromium** [comment]
AFAICT all image-based solutions have the problem that you can't have hyperlinks from elements inside a formula (which are used extensively in the spec). They also tend to have the aesthetic issue that fonts don't match.

**Comment by caasi** [comment]
I try to create a tool for this and fail: https://gist.github.com/caasi/8c1d9ca2f8703c97810b6bb571b78061

I can't just simply replace the inner HTML with the rendered MathML.

**Comment by littledan** [comment]
MathML may come to Chrome soon; my coworkers at Igalia [are collaborating](https://bugs.chromium.org/p/chromium/issues/detail?id=6606#c61) with Chrome layout team on this. Maybe the Wasm spec could display MathML for browsers that support it (e.g., Firefox, Safari).

**Comment by binji** [comment]
The [single-page spec](http://webassembly.github.io/spec/core/bikeshed/index.html) uses KaTeX to render math, so it renders properly with JavaScript disabled. Please file bugs if you have an issues.
