### ISSUE TITLE
Module allocation & Store

### ISSUE THREAD

**Issue by LuisHsu** [WebAssembly/spec#528]
In the description of `4.5.3 Allocation (page 77)`, it says 

> New instances of functions, tables, memories, globals, and modules are allocated in a store S

But in `4.2.2 Store`, modules is not specified in the Store structure.

Is module instances still resides in the Store, or there's other mechanism that I didn't mentioned?

**Comment by rossberg-chromium** [comment]
This was meant to reflect that all the components of a module are allocated in the store (even though the record itself isn't). But I agree that it's misleading. Sneaked in a change into PR #526.
