### ISSUE TITLE
Difference between anchor and link for extend_s (etc) in exec/numerics

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#532]
I noticed that the anchor (the ¶ symbol) has a hyphen: https://webassembly.github.io/spec/exec/numerics.html#op-extend-u

But the links all use an underscore instead: https://webassembly.github.io/spec/exec/numerics.html#op-extend_u, so the links don't work.

This seems to be true for all instructions with an underscore.

**Comment by jfbastien** [comment]
Drive-by fun fact: ¶ is called "pilcrow" 😄
