### ISSUE TITLE
Spec interpreter invalid binary format float const reading

### ISSUE THREAD

**Issue by kripken** [WebAssembly/spec#543]
Consider
````
(module
 (export "calc" (func $calc))
 (func $calc (result f64)
  (f64.convert_u/i32
   (i32.const 4294967249)
  )
 )
)
````
and
````
(module
 (export "calc" (func $calc))
 (func $calc (result f64)
  (f64.const 4294967249)
 )
)
````
The only difference is that in the first we have the const as an int, then convert to a float, and in the second the conversion has been done already. But running these files leads to different results:
````
$ wasm a.wasm -e '(invoke "calc")' && wasm b.wasm -e '(invoke "calc")'
4294967249. : f64
4294965201. : f64
````
This is the same no matter who translates the text to binary (binaryen, wabt, the spec interpreter itself), so it looks like the bug is in the reading of the float const in the spec interpreter.

**Comment by sunfishcode** [comment]
This is likely due to https://github.com/WebAssembly/spec/issues/421.

**Comment by binji** [comment]
Hm, interesting, doesn't occur when parsing via text, only reading binary.

```
$ cat test.wast
(module
 (func (export "calc1") (result f64)
  (f64.convert_u/i32 (i32.const 4294967249))))
(invoke "calc1")

(module
 (func (export "calc2") (result f64)
  (f64.const 4294967249)))
(invoke "calc2")

$ ./wasm test.wast
4294967249. : f64
4294967249. : f64

$ ./wast2wasm --spec test.wast -o foo.json
$ ./wasm foo.1.wasm -e '(invoke "calc2")'
4294965201. : f64
```

**Comment by binji** [comment]
Looks like it was a bug when decoding f64 values -- it stores the representation as an OCaml int64, but reads it in two int32 pieces. The conversion from int32 -> int64 was sign-extending, which ended up flipping a bit in the result.
