### ISSUE TITLE
[doc] mapping of convert instructions -> numerics in exec section

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#545]
I'm probably missing something, but I don't see how to go from [exec-cvtop](https://webassembly.github.io/spec/exec/instructions.html#exec-cvtop) to the associated [numeric conversion](https://webassembly.github.io/spec/exec/numerics.html#conversions).

It looks like it should call `\cvtop_{t_1,t_2}(c_1)`, where `t_1` and `t_2` are one of `i32`, `i64`, `f32` or `f64`. But the `cvtop` numerics are defined like `\extends_{M,N}(i)` where `M` and `N` are used as sizes, not types. I think this is resolved for unary and binary ops via [this rule](https://webassembly.github.io/spec/exec/instructions.html#numeric-instructions), but I don't see how that would apply to the conversion instructions.

**Comment by rossberg-chromium** [comment]
Good catch. Please see #551.
