### ISSUE TITLE
[Spec] Should we check mutability while set_global?

### ISSUE THREAD

**Issue by LuisHsu** [WebAssembly/spec#546]
In current execution, mutability isn't be checked while setting global.

Should we check mutability and avoid immutable global be set?

**Comment by binji** [comment]
This is already specified [here](http://webassembly.github.io/spec/valid/instructions.html#valid-set-global). It is a validation error to use `set_global` on an immutable variable.

**Comment by LuisHsu** [comment]
Thanks you!
BTW, maybe we can add 
`5. Assert: due to validation, glob.mut must be Val.`
to the execution.

**Comment by binji** [comment]
I'm guessing that was not added because it is irrelevant to the following rules; you'll note that the other assertions are used to protect against invalid operations (e.g. "Assert: due to validation, a value is on the top of the stack." -> "Pop the value valval from the stack.")

**Comment by rossberg-chromium** [comment]
Right, what @binji said. In principle, assertions like this one could be added as well, but they would have a somewhat different nature than the existing ones. So if desired I'd rather make them a note. My only concern is that there are many other soundness invariants like this (potentially, everything that is specified by the notions of Store Validity and Store Extension in the soundness appendix), and it may cause significant clutter to add them everywhere exhaustively.

**Comment by rossberg-chromium** [comment]
After going through the store validity conditions in detail I observed that there are no others that aren't already used/asserted explicitly. So it seems fine to add a note for the specific case of set_global, see #556.
