### ISSUE TITLE
[JS] Nowrap = EnforceRange?

### ISSUE THREAD

**Issue by domenic** [WebAssembly/spec#548]
> The [Nowrap] extended attribute to an integer type throws a RangeError if the Number is greater than or less than the range which can be accurately represented by the type.

Seems a lot like https://heycam.github.io/webidl/#EnforceRange

**Comment by littledan** [comment]
Yeah, good point, the current draft switches to EnforceRange.

**Comment by ericprud** [comment]
@domenic, does that switch satisfy the issue? If so, can you close it?
