### ISSUE TITLE
Are names and UTF-8 validation web-only?

### ISSUE THREAD

**Issue by littledan** [WebAssembly/spec#550]
Right now, JS.md refers to Web.md to define [names](https://github.com/WebAssembly/design/blob/master/Web.md#names). That document just seems to say, decode the names as UTF-8 into UTF-16 and throw eagerly on any validation errors when validating the module as a whole. Is that right? A couple questions:
- Is there a particular reason this is in Web.md and not JS.md, and says "on the Web"? It's hard for me to understand which part of any of this would be skipped in other environments where WebAssembly is used. For example, wouldn't Node.js want to do all of the same things?
- Does that conversion algorithm do anything additional besides throw on invalid UTF-8? Why not just say, "throw on invalid UTF-8"?

**Comment by lukewagner** [comment]
The Web.md and JS.md bits you're referring to predate the more recent [agreement and PR](https://github.com/WebAssembly/design/pull/1016) that [all strings must be valid utf-8](https://webassembly.github.io/spec/binary/values.html#names) in wasm.  So we can probably nuke this "Names" section in Web.md and the JS-API spec can point to the core spec requirement.

Yeah, the conversion algorithm was I suppose just written that way to be concrete, I guess.

**Comment by littledan** [comment]
I see, seems to be pretty unambiguous from that PR. Thanks.
