### ISSUE TITLE
[spec] Should functions return a resulttype?

### ISSUE THREAD

**Issue by littledan** [WebAssembly/spec#559]
Looking at https://webassembly.github.io/spec/syntax/types.html#function-types , I was wondering if

functype::=[vec(valtype)]→[vec(valtype)]

Should actually be defined as

functype::=[vec(valtype)]→resulttype

given that resulttype was defined immediately prior, is not used in the AST, and would make sense as a way to enforce in the grammar that there is at most one value (which is otherwise only enforced in a note as far as I can tell).

**Comment by binji** [comment]
Result types are used for block results, see for example https://webassembly.github.io/spec/syntax/instructions.html#control-instructions.

Function types are validated to ensure there is at most one result here: http://webassembly.github.io/spec/valid/types.html#function-types.

It does seem a bit strange that `resulttype` is constrained in the structure and `functype`'s results are constrained in the validation, though.

**Comment by rossberg-chromium** [comment]
The reason is simple: The abstract syntax is defined to be in 1-to-1 correspondence with the binary format, because it is supposed to be its abstract representation. And the binary format (currently) happens to have the same difference (but see the multi-value proposal :) ).

**Comment by littledan** [comment]
I see, thanks for the explanation and sorry for the noise!
