### ISSUE TITLE
String byte escapes seem wrong

### ISSUE THREAD

**Issue by annevk** [WebAssembly/spec#577]
https://webassembly.github.io/spec/text/values.html#strings seems to suggest you can encode the 0xFF byte using \FF. However, that would allow you to end up with invalid UTF-8. Surely that can't be the goal here? (In particular as it would be a vastly different flavor from JavaScript's lone surrogate problem.)

**Comment by rossberg-chromium** [comment]
String syntax can be used for arbitrary byte sequences, such as memory segments. You are probably thinking of [names](https://webassembly.github.io/spec/text/values.html#names), which are strings that must be valid UTF-8 encodings.

**Comment by annevk** [comment]
Hmm, it would be more logical if Strings were named "Byte sequences" and Names "Strings".

**Comment by rossberg-chromium** [comment]
Well, byte sequences already exist, while strings are a textual representation of byte sequences in the text format (called that because they use the usual string notation). Read it as byte string, not character string.

**Comment by annevk** [comment]
It seems rather confusing to me, but happy to close this as I was mistaken about there being a factual error.

**Comment by annevk** [comment]
(In particular when you contrast this with something like Rust, which does have first-class UTF-8-backed strings.)
