### ISSUE TITLE
Spec Text Format For Quoted Modules And Binary

### ISSUE THREAD

**Issue by cretz** [WebAssembly/spec#578]
I haven't revisited the spec in a few months and saw that #471 and #475 have landed. However, browsing the spec I see no mention of binary or quoted module definitions for the text format. I saw the comments like https://github.com/WebAssembly/spec/pull/471#issuecomment-300906581 saying move forward without the binary for now, but it is built in to the spec tests, so implementers must implement it or not pass. As for the quote part, I didn't see that anywhere.

**Comment by rossberg-chromium** [comment]
The wast test format is a superset of the official text format. There is no expectation that other tool chains understand it, and the quote and binary syntax (as well as the other extensions) really only seem useful for testing consumers. But you should be able use the reference interpreter or wabt to convert it to bare wat.

**Comment by cretz** [comment]
Gotcha, I'll close this. Maybe this could be documented in https://github.com/WebAssembly/spec/blob/master/interpreter/README.md#s-expression-syntax somewhere? Using that doc for things like `assert_malformed` or the like really helped me write my original impl.

**Comment by rossberg-chromium** [comment]
Good point, README is updated!
