### ISSUE TITLE
Text Format Function Signature's Result Without Type

### ISSUE THREAD

**Issue by cretz** [WebAssembly/spec#579]
In #497, a change was made to the `func.wast` to have:

```
  (func $complex
    (param i32 f32) (param $x i64) (param) (param i32)
    (result) (result i32) (result)
    (local f32) (local $y i32) (local i64 i32) (local) (local f64 i32)
    (unreachable) (unreachable)
  )
```

I don't see in the interpreter README or in the text format spec where `(result)` (i.e. sans type) is defined. Am I misreading it? What should be done with a result without a type?

**Comment by cretz** [comment]
Ok, I see in the spec:

```
‘(’  ‘result’  valtype∗  ‘)’≡≡(‘(’  ‘param’  valtype  ‘)’)∗(‘(’  ‘result’  valtype  ‘)’)∗
```

So this issue is just a request to add an asterisk after `<type>` in the interpreter README for `result`.

**Comment by rossberg** [comment]
@cretz, done. Thanks for spotting.
