### ISSUE TITLE
[spec] Relationship between external standards and local definitions

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#580]
For both IEEE 754 and Unicode, WebAssembly contains both references to external specs, as well as its own copy of the content it uses from those specs. It's not currently clear what the intended relationship is between the external specs and the local copies.

For example, [RFC3629](http://www.ietf.org/rfc/rfc3629.txt) also has its own grammar describing UTF-8, and it makes the following note:

> NOTE -- The authoritative definition of UTF-8 is in [UNICODE].  This
   grammar is believed to describe the same thing Unicode describes, but
   does not claim to be authoritative.  Implementors are urged to rely
   on the authoritative source, rather than on this ABNF.

**Comment by rossberg** [comment]
Fixed by #582.
