### ISSUE TITLE
Text Format Function Export and Import On Same Line

### ISSUE THREAD

**Issue by cretz** [WebAssembly/spec#581]
See https://github.com/WebAssembly/spec/blob/b3986ab01335b0dca4564830e2a97020fa8704fc/test/core/imports.wast#L44.

This is mentioned in the spec, but the grammar in the interpreter README is not updated to conform.

On a general note, I wonder if it would be easier to just change the "S-Expression Syntax" section's grammar of the README to point to the spec to prevent all of these synchronization issues. Of course "Scripts" still has to remain because there is no analog in the spec.

**Comment by rossberg** [comment]
I updated the README grammar. I also added a disclaimer pointing to the spec as the definite source of truth.
