### ISSUE TITLE
Can we state wasm's MIME type next to the recommended file extension?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/spec#583]
Specifically, in §5.1.

**Comment by jfbastien** [comment]
Wouldn't that fall in the Web embedding spec that @littledan is working on?

**Comment by lukewagner** [comment]
It would make sense to mention it there too, since it's part of the semantics of `compileStreaming`/`instantiateSTreaming`, but I was thinking it makes sense here too, as a general "if you are serving one of these, here's the MIME type to use" note (which is technically broader than the Web).

**Comment by littledan** [comment]
Putting it in the web spec seems appropriate to me. As for §5.1, I'm surprised that remark exists. The JS spec doesn't say anything about file extensions. "What's a file  anyway?" is not really the most off-topic question when file extensions generally aren't significant on the web (aside from web servers guessing mimetypes). I think the right "normalized" place to put the file extension is in the IANA media type registry, and you find that by the Web spec saying that the mimetype is application/wasm. We can have other places where these things are indicated, as notes.

**Comment by rossberg** [comment]
I don't have a strong opinion, but I agree that both should be mentioned in the same place, while also agreeing that the main body of the spec may be a somewhat strange place for that. It probably would fit better into an Appendix, but can't find an obvious place. Any suggestion?

**Comment by littledan** [comment]
If you want to put it in the main spec, an appendix with all the mimetypes and file extensions sounds good to me. It'd be nice if whichever place says it points to the IANA media type registry as the source of truth. I don't quite understand why this should be in the main spec while the JS interface is left out, though, when not all Wasm use has file extensions or mimetypes (e.g., the current JS binding doesn't even support either).

**Comment by lukewagner** [comment]
That's true, but it is a somewhat general and non-web-specific convention that "when you need to pick an extension or MIME type, use these".

**Comment by lukewagner** [comment]
So ok if I put up a PR adding 'application/wasm' next to the mention of '.wasm'?

**Comment by rossberg** [comment]
Fine by me.

**Comment by lukewagner** [comment]
Ok, merged.  @rossberg could you perhaps merge into the gh-pages branch?
