### ISSUE TITLE
Minor: Errors in embedding spec don't give sufficient information

### ISSUE THREAD

**Issue by littledan** [WebAssembly/spec#586]
In the specification for [read_table](https://webassembly.github.io/spec/appendix/embedding.html#embed-read-table), an error is returned in two cases:
- If the table contains an unfilled entry
- If an out-of-bounds index is passed in

In the JS interface spec, the first case results in a TypeError, and the second case results in a RangeError. The JS spec can get around this by maintaining a parallel structure \[\[Values]] which is sufficient for doing this checking itself, but the overall result is a little messy. I imagine that other embedding environments might also want to differentiate between these two conditions.

**Comment by rossberg** [comment]
Actually, the first case is supposed to return `null` I think.

I'll change the definition of read_table such that it returns a an optional fa.

**Comment by rossberg** [comment]
Fixed by #587.
