### ISSUE TITLE
multiple build processes, processes disagree

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#59]
When using src/Makefile, one gets an executable at src/wasm. However, runtests.py expects an executable at src/main.native. It'd be useful for these to agree; which one is preferable?

**Comment by kg** [comment]
Happy to update runtests to handle this. I personally dislike what ocamlbuild does.

**Comment by rossberg-chromium** [comment]
SGTM as well. Would be nicer if we did get a binary named `wasm` in a consistent place (preferably outside the src dir). Can one do that with ocamlbuild?

**Comment by sunfishcode** [comment]
It looks like #83 would fix this.
