### ISSUE TITLE
[interpreter] OPAM package properly provides the `.mli` interfaces, but not the `.ml` files for modules such as Ast

### ISSUE THREAD

**Issue by msprotz** [WebAssembly/spec#593]
Thanks,

Jonathan

**Comment by rossberg** [comment]
@msprotz, pardon my ignorance, any hint what's at fault? I see that the Makefile's `install` target only explicitly lists mli files, but that has always been the case AFAICS. Should it include `ml` files as well?

**Comment by msprotz** [comment]
No worries -- it's just good practice to include interface files so that one can do "jump to definition" from one's editor and see the definition of the type in the original source file. Since Ast.ml and others in `syntax/` don't have an `.mli`, we could either:
- add `$(wildcard syntax/*.ml)` and install the `.ml` files too, but I don't see many people installing `.ml` files into findlib directories, so it looks like it's not the right thing to do;
- perhaps we could generate these `.mli`s via `ocamlbuild`'s `.inferred.mli` rules and then copy them?

Anyhow, not a big deal, just a minor improvement :).

Thanks,

Jonathan

**Comment by ericprud** [comment]
@msprotz, @rossberg, has this been decided? Can this issue be closed?

**Comment by rossberg** [comment]
The OPAM package needs updating. I'd leave this open for now. I have tagged this [interpreter] to make clear that it doesn't affect the spec.
