### ISSUE TITLE
Textual spec should indicate that memory alignments are stored as log2

### ISSUE THREAD

**Issue by eholk** [WebAssembly/spec#600]
Apologies if this is written somewhere else and I missed it, but https://webassembly.github.io/spec/binary/instructions.html#binary-memarg does not seem to mention that alignments are stored as the log2 of the alignment (e.g. 3 instead of 8). The spec interpreter does the left-shift though, so it looks like log2 is what is actually used. The textual spec should mention this too.

**Comment by rossberg** [comment]
Good point, see #601. In the spec the AST itself uses log2, so adding the note there instead.
