### ISSUE TITLE
instantiation tweaks

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/spec#603]
Two small requested tweaks to [instantiation](https://webassembly.github.io/spec/exec/modules.html#instantiation):
* I think the externtype' in "⊢module:externtype<sup>n</sup>→externtype′*" is meant (and needs) to be distinct from the externtype' used in both "(⊢externval:externtype′)<sup>n</sup>" and "(⊢externtype′≤externtype)<sup>n</sup>"
* could allocmodule be hyperlinked?

**Comment by rossberg** [comment]
Thanks. Please see #604.

**Comment by lukewagner** [comment]
Thanks!
