### ISSUE TITLE
specification of labels for loops and exiting from blocks

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/spec#608]
I have some problems with the spec. Namely, spec states for the [`loop`](https://github.com/WebAssembly/spec/blob/master/document/core/exec/instructions.rst#looptinstrastend): 

- Let L be the label whose arity is 0 and whose continuation is the start of the loop.

And then in the Blocks section, in [Exiting inst* with Label L](https://github.com/WebAssembly/spec/blob/master/document/core/exec/instructions.rst#exiting-instrast-with-label-l) (I assume this explains how `end` works?) it states:

- Let n be the arity of L
- ...
- Pop the results valⁿ from the stack

But is it correct? I'm interpreting this as "`loop..end` block can't return any values, because when executing `loop` we pushing label with arity=0 and when we execute `end` we pop 0 values". Which seems incorrect for me (e.g.  [counter-example](https://github.com/WebAssembly/spec/blob/c4774b47d326e4114f96232f1389a555639d7348/test/core/labels.wast#L69)).

Could someone clarify this to me?

**Comment by rossberg** [comment]
Note that at step 6, the same values are pushed back, after the label (i.e., the inner block) has been popped. That is because operand and label stack are [interleaved](https://webassembly.github.io/spec/exec/runtime.html#stack) in the abstract machine.

**Comment by pepyakin** [comment]
But isn't `n` is 0 for labels that is pushed by label, so no values are pushed and poped?
(I assume that `valⁿ` is denoting "`n` number of values")

**Comment by rossberg** [comment]
Ah, you are right, thanks, good catch! I ported this incorrectly from the paper. The number of values ought to be independent from the label's arity. See #609 for a fix.
