### ISSUE TITLE
[spec] global initializer type validation

### ISSUE THREAD

**Issue by HugoGuiroux** [WebAssembly/spec#613]
Globals are [allocated](https://webassembly.github.io/spec/exec/modules.html#alloc-global) with values initialized during the instantiation. Thanks to validation, the type of the val [is checked](https://webassembly.github.io/spec/exec/modules.html#alloc-global) against the type of the global.

I think it would be nice to add to the [global allocation specification](https://webassembly.github.io/spec/exec/modules.html#alloc-global) a remark like `Assert: due to validation, type of val is equals to globaltype`, which seems to be details used frequently throughout the spec.

**Comment by rossberg** [comment]
Explicit assertions are only used to guard consecutive execution steps that would fail if a specific condition didn't hold. There are many other properties one could assert in many places, but doing so would clutter the semantics. Verifying that all expected typing properties hold is the role of the [soundness](https://webassembly.github.io/spec/appendix/properties.html) statement in the appendix.

**Comment by HugoGuiroux** [comment]
I understand now. Thanks!
