### ISSUE TITLE
[spec] exports in Module Instances

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#616]
This page about [Module instances](https://webassembly.github.io/spec/exec/runtime.html#module-instances) shows the `exports` property of a module instance.

Please correct me if I'm wrong but it's not a List/Map and refers to the Export Instances object. It seems to me that only one export is allowed at runtime. Is that correct?

In your interpreter implementation is shows a list, [see](https://github.com/WebAssembly/spec/blob/a5d90cbec68b8ffb2a43bd1a6bafdc51cc58b158/interpreter/runtime/instance.ml#L10).

I'm happy to PR if that's not correct.

Same question with the other properties btw, shouldn't they be Vectors?

**Comment by rossberg** [comment]
I'm not sure I follow. Both spec and interpreter implement a list of exports, and that is of course necessary. Don't confuse it with the `exports` object in the JS API. The list of exports in the spec corresponds to the list of *properties* of that object.

**Comment by xtuc** [comment]
Ok, my understanding of the spec is probably wrong.
I don't see in the syntax how can you make the difference between a list of `exportinst` or reference to another structure.

**Comment by xtuc** [comment]
Sorry my understanding was definitely wrong! The star means that it's a list of zero to n elements.

Closing this since it's not an issue.
