### ISSUE TITLE
[spec] incorrect usage in tests of invoke

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#618]
According to the spec [here](https://webassembly.github.io/spec/exec/runtime.html#syntax-invoke):

```
instr ::= invoke funcaddr
```

Where 

```
funcaddr ::= 0 | 1 | 2 | …
```

In the spec repo I found this in the `call` tests:

https://github.com/WebAssembly/spec/blob/16d3cdd8f17984c5d552f25a1d5c0e34e38df95e/test/core/call.wast#L111

Which one is correct? I think that they should be changed to `call` instead of `invoke` instructions.

**Comment by binji** [comment]
`assert_return` and `invoke` are part of the extended `.wast` script syntax described [here](https://github.com/WebAssembly/spec/tree/master/interpreter#scripts). It's not actually part of the WebAssembly spec.

The `invoke` that is in the spec is (AIUI) a different mechanism for unifying internal and imported function calls.

**Comment by xtuc** [comment]
Ok, got it, thanks.

Closing this since it's not an issue.
