### ISSUE TITLE
[spec] section size in WASM format

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#620]
According to https://webassembly.github.io/spec/binary/modules.html#binary-section:

> the u32 size of the contents, in bytes.

Take the following example in [wat2wasm](https://cdn.rawgit.com/WebAssembly/wabt/fb986fbd/demo/wat2wasm/): the size of the type section is `00` which is on 1 byte instead of 4 bytes for the u32.

I'm not able to fully understand the code in the OCaml interpreter but it seems that the size is ignored (which explains the value found in the WASM).

**Comment by binji** [comment]
`u32` is defined [here](https://webassembly.github.io/spec/binary/values.html#binary-int) as a variable-length integer, so it can be between 1 and 5 bytes long, depending on its value.

**Comment by xtuc** [comment]
Indeed, thanks!

I assumed that both links of `u32` (1 and 2 on the picture) were pointing to the same page:
![screenshot from 2017-12-08 18-39-09](https://user-images.githubusercontent.com/1493671/33778024-3f2574ba-dc47-11e7-851b-5bc94ead3ceb.png)

**Comment by binji** [comment]
Ah, I see. Yes, that is a bit confusing.
