### ISSUE TITLE
[website] JS API not accessible anymore

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#630]
The JavaScript API documentation on the WebAssembly website has been replaced by `test` see https://webassembly.github.io/spec/js-api/index.html.

**Comment by xtuc** [comment]
In case you are looking for it it's available in Markdown here https://github.com/WebAssembly/design/blob/master/JS.md.

**Comment by pepyakin** [comment]
I believe that these documents are distinct. 

https://github.com/WebAssembly/design/blob/master/JS.md document is corresponds to http://webassembly.org/docs/js/ and still available online

The document https://webassembly.github.io/spec/js-api/index.html I believe is supposed to point to this file https://github.com/WebAssembly/spec/blob/master/document/js-api/index.bs
but for now it is not yet published, as far as i can tell

**Comment by littledan** [comment]
js-api/index.html obsoletes JS.md . I have a patch out for review (#628) which will automate deployment of the build. We should probably remove JS.md (or add a redirect) once this lands to reduce confusion.

**Comment by littledan** [comment]
You can now access the JS API spec at https://webassembly.github.io/spec/js-api/index.html .

**Comment by xtuc** [comment]
Nice! thanks @littledan
