### ISSUE TITLE
[WAST] assert_soft_invalid seems not used

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#639]
The WAST syntax specifies the instruction `assert_soft_invalid`, but it seems that it isn't used here anymore.

I found a reference to it in https://github.com/WebAssembly/spec/blob/645c6524371445bb8c3a85575ba8cb4810a175bc/test/harness/index.js#L159, but the function is neither exported nor used.

Is that correct?

**Comment by rossberg** [comment]
Indeed, removed by #641. Thanks!
