### ISSUE TITLE
Duplicated interpreter?

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#640]
First, sorry, this is not related to the spec. Feel free to close it if you want me to move it.

It seems that the reference interpreter is duplicated in many repo of the WebAssembly organization (see the search result of [parser.mly](https://github.com/search?utf8=%E2%9C%93&q=org%3AWebAssembly+filename%3Aparser.mly&type=Code) file).

I guess that's intentional to avoid having specific features into the main interpreter. The downside is that it increases the complexity and the maintenance (especially now that the interpreter is stable enough, some copies might not be as up-to-date).

Would you consider including it using submodules? Or some automated script? I would be happy to PR or chat.

**Comment by rossberg** [comment]
All these repos are forks of the `spec` repo whose purpose is to develop individual language proposals. See the [proposal process][https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group] for background.

**Comment by xtuc** [comment]
Ok, thanks for your answer. I hadn't read this paper before.
