### ISSUE TITLE
[WAST] nat not specified by the grammar

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#642]
In the [WAST grammar](https://github.com/WebAssembly/spec/tree/master/interpreter#s-expression-syntax) `nat` is not defined.

Is `nat` a primitive type?

Could you please confirm me that `nat: <int>` is correct, I would be happy to PR.

**Comment by rossberg** [comment]
Nat is a natural number, just like int is an integer number. I didn't bother to add all the lexical syntax before, but I just added it.

**Comment by xtuc** [comment]
Perfect thanks! Is it worth taking the time to replicate this change in the other repos (since it's not implementation specific)?

**Comment by rossberg** [comment]
Other repo owners decide for themselves when they fetch upstream changes.
