### ISSUE TITLE
[website] highlighting breaks the MathML render

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#643]
When you do a search and have the highlighting turned on some MathML formulas don't render anymore.

Example:
- On: https://webassembly.github.io/spec/core/valid/modules.html?highlight=a#data-segments
- Off: https://webassembly.github.io/spec/core/valid/modules.html#data-segments

I'm personally using the search often and need to edit the URL by hand to understand the formulas.

**Comment by rossberg** [comment]
Interesting. That's unfortunate, but is there anything we can do about this? The underlying problem is that MathJax, which is the math rendering package used here, is a JavaScript-based kludge (as are its alternatives) and the web still hasn't grown a proper solution (like MathML).

**Comment by littledan** [comment]
One thing you could do is not apply MathJax in browsers that nave native MathML support (currently, Gecko and WebKit-based browsers). Igalia is working on MathML in Chromium, so this could end up being a practical solution soon.

**Comment by rossberg** [comment]
Sounds good, but is serving different pages to different browsers even possible with GH pages?

Good to hear that Igalia is working on MathML, though!

**Comment by xtuc** [comment]
Do you know if the highlighting is actually useful? You can use Ctrl+f instead (once you get on the page), that sounds like a good compromise to me.

**Comment by littledan** [comment]
@rossberg I was imagining a JS snippet would decide which to show on the client side. Not sure if this would be a ton of trouble to implement.

**Comment by rossberg** [comment]
@littledan, with MathML the math isn't generated by JavaScript but is a static part of the document. You could probably set it up differently somehow, but I don't know of tools that support that.

**Comment by binji** [comment]
I don't see any difference here. I assume because we've switched from MathJax to Katex? Can we close this?

**Comment by rossberg** [comment]
Closing as won't fix.
