### ISSUE TITLE
Clarify signed/unsigned interpretation for ToJSValue with i32 arguments

### ISSUE THREAD

**Issue by maurobringolf** [WebAssembly/spec#647]
This is more of a question than an issue:
When calling an exported wasm function from JavaScript that returns an `i32`, is it guaranteed to be interpreted as signed i32 two's complement integer?

Is this specified somewhere? The only thing I could find was the **ToJSValue** algorithm which says:

> If w is of the form 𝗂𝟥𝟤.𝖼𝗈𝗇𝗌𝗍 i32, return the Number value for i32.

https://webassembly.github.io/spec/js-api/index.html#tojsvalue

If I understand it correctly, `i32` is not inherently signed or unsigned in general (depends on instruction, `i32.div_u` and `i32.div_s` for example. So maybe the sign interpretation of **ToJSValue** could be stated more clearly?

cc @ColinEberhardt @xtuc

**Comment by rossberg** [comment]
In the Wasm abstract syntax, i32 is represented by its unsigned interpretation (see [here](https://webassembly.github.io/spec/core/syntax/values.html#syntax-int)). So this implies an unsigned conversion. However, I agree that this is not very obvious, and that we should include a note to this effect with ToJSValue (and perhaps link i32 to its definition).

**Comment by gahaas** [comment]
In https://github.com/WebAssembly/design/blob/master/JS.md#tojsvalue it is clearly stated that i32 is interpreted as a signed integer.

**Comment by rossberg** [comment]
@gahaas, indeed, so the current wording in the API spec is in fact incorrect.

**Comment by maurobringolf** [comment]
Thank you, I wasn't aware of the design document. That helps alot.
