### ISSUE TITLE
Question: Wrap-around behavior of load/store instructions

### ISSUE THREAD

**Issue by icefoxen** [WebAssembly/spec#648]
Hi all,

Say I have the following sequence of instructions:

```wasm
i32.const 0x2
i32.load 0xFFFFFFFE ...
```

The specification states:

```
Let ea be the integer i+memarg.offset.
...
If ea+N/8 is larger than the length of mem.data, then: Trap.
```

In this case, `memarg.offset` is `0xFFFF_FFFE` and `i` is 0x2, so the effective address would be `0x1_0000_0001`, which is larger than the maximum size of a memory.  Is the intended behavior for this address to be wrapped at 2^32 and so wrap to `0x01`, or is the intended behavior to say "ea is larger than the length of the memory, trap"?  The spec seems to say the latter but I'm not 100% sure.

The same question applies to integer underflows as well as overflows, naturally.

**Comment by binji** [comment]
The sum does not wrap, so your example should trap. As a general rule, the spec uses standard arithmetic operations, and is explicit about any modular arithmetic performed. See for example [`iadd`](https://webassembly.github.io/spec/core/exec/numerics.html#op-iadd).

**Comment by icefoxen** [comment]
Thank you!  That makes sense.
