### ISSUE TITLE
Add header/version in text format

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#654]
Following https://github.com/WebAssembly/spec/issues/627#issuecomment-360859750, https://github.com/WebAssembly/spec/pull/649 introduces a breaking change.

Unlike WASM, WATF has no version or header information.
I think that it would be useful for parser implementer to have something like `(version 1.0) (module)`.

This will allow future more important breaking changes.

**Comment by rossberg** [comment]
We don't intend to make breaking changes to the text format once the standard is "official". But even if we did, how would a version declaration help? The only situation I can imagine is if you wanted to redefine legal existing syntax to mean something else than before, but that kind of thing should be avoided for many reasons.

**Comment by xtuc** [comment]
> But even if we did, how would a version declaration help?

I mean in the case of existing semantics or syntax changes. In that case you could refer to the version declaration to decide to pick on of the behaviors.

Of course breaking changes should be avoided. The WASM already has a version in its header but the WATF doesn't, even if they are under the same specification.

IMO we can't be sure that we won't ever introduce a breaking change in WATF, maybe we can add the version instruction at that time? I would prefer to have it now in the spec tho.

**Comment by rossberg** [comment]
To clarify my previous point: there are two ways in which you can potentially break the language:

1. A program that was previously valid is no longer valid.
2. A program that was previously valid is still valid but has changed meaning in incompatible ways.

For situation 1, parsing/translation will just fail, regardless of a version annotation.
Situation 2 is something we should never do, regardless of a version annotation.

**Comment by xtuc** [comment]
> For situation 1, parsing/translation will just fail, regardless of a version annotation.

Yes, that's a good point.

> Situation 2 is something we should never do, regardless of a version annotation.

I don't disagree on this but i'm wondering why you need a version in the WASM header?

And as I said I'm really not sure we can be sure to never ever introduce a change in the future, but that's only IMO.

**Comment by rossberg** [comment]
The difference with the binary format is that that leaves much less wiggle room for changes: in the text format, you can always pick a different syntax or keyword, in binary not so much. Also, the binary format will cause client-side errors, whereas text errors only concern devs.

**Comment by xtuc** [comment]
Ok I think that you're right. We can close this issue, but we can still comment in it.
