### ISSUE TITLE
inline-module spectest

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#656]
Is it normal that this tests hasn't any assertions? The implementer could completely ignore it.

https://github.com/WebAssembly/spec/blob/21f09e25a12a877aa3b9740fbfc623d463eb9f93/test/core/inline-module.wast#L1

I'm proposing to change it to:

```wast
(func) (memory 0) (func (export "f") (result i32) (i32.const 1))
(assert_return (get "f") (i32.const 1))
```

I preferred asking before making an actual PR, but if that's ok to you I can make it.

I guess that the point is to prove that an implicit module exits, testing the export ensures that.

**Comment by binji** [comment]
That test is meant to ensure that inline modules can be parsed. The alternative that you mention will not parse, since `assert_return` is not allowed within a module.

**Comment by rossberg** [comment]
This question was answered, closing.
