### ISSUE TITLE
Question about the "offset" terminal symbol in the Data and Element Segments definition

### ISSUE THREAD

**Issue by jcmellado** [WebAssembly/spec#662]
The textual grammar for [Data Segments](https://webassembly.github.io/spec/core/text/modules.html#data-segments) is given as follow:

> dataI ::=‘(’ ‘data’  (x:memidxI)?  ‘(’ **‘offset’**  e:exprI ‘)’  b∗:datastring ‘)’

Here, `offset` is a mandatory terminal symbol.

And according the [Data Segment](https://webassembly.github.io/spec/core/syntax/modules.html#syntax-data) definition:

> The offset is given by a constant expression.

So a Data Segment should be declared like in the following example:

`(data (offset i32.const 0) "\01\02\03")`

But I could not found any other reference neither test using the `offset` terminal symbol there.

The same happens for the textual grammar for [Element Segments](https://webassembly.github.io/spec/core/text/modules.html#element-segments).

Is it an error, a recent change in the specification, or I'm missing something?

**Comment by rossberg** [comment]
Ah, good catch. There is something missing in the spec. The offset form is legal, and always has been, but there is a short-hand: if the expression is single instruction, you can put it in place of the `(offset ...)` directly. That is the form being used in tests. (Currently, all valid expressions are single instructions, but that might change in the future.)

I'll add that to the spec, and also add a test using it.

**Comment by jcmellado** [comment]
Reopen and fix typo. 

PR https://github.com/WebAssembly/spec/pull/735
