### ISSUE TITLE
[bikeshed] Wrong fonts and spacing

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#669]
The Bikeshed version of the spec does not seem to respect \mathit and \mathrm formats in some contexts. Consequently, all letters are type-set as individual variables in italic font and spacing and kerning is off.

(See e.g. rendering of the "s with [i] = e" notation [here](http://flagxor.github.io/spec/core/bikeshed/index.html#auxiliary-notation①) or the rendering of variable names like "i16" in the note [here](http://flagxor.github.io/spec/core/bikeshed/index.html#integers①).)

Note: Cases like "with" and "if" are probably due to the use of \mbox?

**Comment by flagxor** [comment]
The bad kerning seems to be a general issue with katex:
https://khan.github.io/KaTeX/

Filed this:
https://github.com/Khan/KaTeX/issues/1259

**Comment by flagxor** [comment]
Worked around it for now.

**Comment by rossberg** [comment]
It seems like e.g. the "with" notation linked to in the OP is still rendered unreadable.

**Comment by rossberg** [comment]
Apparently I was looking at the wrong copy.

**Comment by rossberg** [comment]
It seems like there are still places where spaces get swallowed, see e.g.
http://webassembly.github.io/spec/core/bikeshed/index.html#tokens①
http://webassembly.github.io/spec/core/bikeshed/index.html#modules⑦  (foralli at bottom of section)

**Comment by binji** [comment]
> It seems like there are still places where spaces get swallowed, see e.g.
http://webassembly.github.io/spec/core/bikeshed/index.html#tokens①
http://webassembly.github.io/spec/core/bikeshed/index.html#modules⑦ (foralli at bottom of section)

These issues seem to be fixed by the update to v0.10.0, and by replacing `\mbox` with `\text`. PTAL

**Comment by rossberg** [comment]
Indeed, excellent, thanks!
