### ISSUE TITLE
[bikeshed] Vertical alignment of arrays

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#670]
Some uses of arrays do not seem to respect the [t] placement, such that vertical alignment is off.

(For example, see the grammer definition for store [here](http://flagxor.github.io/spec/core/bikeshed/index.html#store①).)

**Comment by flagxor** [comment]
This is due to [t] etc. not being supported:
https://github.com/Khan/KaTeX/issues/269

We could make this less glaring if we changed this:
```
   \begin{array}{llll}
   store &::=& \{~ 
     \begin{array}{lll}
     SFUNCS & funcinst^\ast, \\
     STABLES & tableinst^\ast, \\
     SMEMS & meminst^\ast, \\
     SGLOBALS & globalinst^\ast ~\}
     \end{array}
   \end{array}
```

We could make this less glaring if we changed this:
```
   \begin{array}{llll}
   store &::=& \{~ 
     \begin{array}{lll}
     SFUNCS & funcinst^\ast, \\
     STABLES & tableinst^\ast, \\
     SMEMS & meminst^\ast, \\
     SGLOBALS & globalinst^\ast
     \end{array}
     ~\}
   \end{array}
```

**Comment by rossberg** [comment]
Closing as "won't-fix", since the Bikeshed version no longer uses Katex".
