### ISSUE TITLE
[bikeshed] Array column alignment

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#671]
The Bikeshed/Katex rendering does not respect uses of alignment markers "&" in some arrays (when nested?).

(See e.g. the reduction rules [here](http://flagxor.github.io/spec/core/bikeshed/index.html#evaluation-contexts①).)

**Comment by flagxor** [comment]
Not seeing the issue, can you find a clearer example, or explain more?

**Comment by rossberg** [comment]
You're right, this was actually in the sources. Tweaked.
