### ISSUE TITLE
[bikeshed] Reduce width of TOC

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#676]
It is currently eating up a lot of horizontal screen estate, making various formulas overflow page width.

**Comment by flagxor** [comment]
This styling comes from W3C.
Is this still a problem with the adjusted TOC depth?
Tab, any idea whey the TOC is formatted this way.

**Comment by tabatkins** [comment]
The W3C styling assumes that specs can get by with 50ems of horizontal width; this is the suggested maximum line length for maximum readability.

If you don't like the ToC on the side, you can always close it - the button's there at the bottom.  This'll reset the ToC to being inline at the top of the spec. (This is not "sticky" tho; it'll reset to normal on a refresh or revisit.)

**Comment by rossberg** [comment]
Closing as "won't-fix".
