### ISSUE TITLE
Parser rejects i32.reinterpret/f32

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#68]
For this code:
```
(assert_eq
  (i32.reinterpret/f32 (f32.const 1.0))
  (i32.reinterpret/f32 (f32.const 1.0))
)
```

wasm says:

```
test/test.wasm:2.4-2.23: syntax error
```

As far as I can tell, i32.reinterpret/f32 should be a valid opcode recognized by the lexer. Is this code actually invalid, or is there a parsing bug here?

**Comment by rossberg-chromium** [comment]
The error is with your use of `assert_eq`: it only allows an `invoke` on the LHS, not a naked wasm expression.

**Comment by sunfishcode** [comment]
Ah, got it. I was attempting to write floating point tests that test for specific bit patterns, since `assert_eq` just uses `<>`. It looks like the solution is new flavors of assert then.
