### ISSUE TITLE
[bikeshed] All references should go to References section

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#680]
They currently occur as footnotes throughout the document. (Not clear how to fix this with Sphinx, though.)

**Comment by binji** [comment]
Are you talking about bikeshed references here (like [these](https://webassembly.github.io/spec/js-api/index.html#references)), or references to papers and documents?

**Comment by rossberg** [comment]
I think I meant the latter. In a linear document footnotes do not really make sense, and you usually want a bibliography at the end (as in the PDF).

Not super important, though.

**Comment by rossberg** [comment]
Closing as "won't-fix", since the Bikeshed version no longer is single-page.
