### ISSUE TITLE
Would it be possible to keep the spec URLs consistent?

### ISSUE THREAD

**Issue by ColinEberhardt** [WebAssembly/spec#689]
Your recent updates have resulted in the URLs changing ... for example:

https://webassembly.github.io/spec/core/exec/numerics.html#op-iadd

has become: 

https://webassembly.github.io/spec/core/multipage/exec/numerics.html#op-iadd

Within the codebase for the WebAssembly interpreter we are building (https://github.com/xtuc/js-webassembly-interpreter) we have a lot of links to the specification, which we've had to update a few times.

Would it be possible to keep the spec URLs consistent? Or when they change add redirects?

**Comment by ColinEberhardt** [comment]
By the way, I don't mean to whinge, I'd be happy to help find a solution. Jekyll does support redirects, but not sure how powerful they are (not sure if they support patterns)

**Comment by rossberg** [comment]
@ColinEberhardt, good point, haven't thought about that. It's true that there already are a number of links into the spec document, including in our own repos.

@flagxor, should we perhaps revert moving the current doc to /multipage?

**Comment by rossberg** [comment]
Fixed.

**Comment by ColinEberhardt** [comment]
Thanks :-)
