### ISSUE TITLE
Invalid render

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/spec#696]
When I go to 

http://webassembly.github.io/spec/core/multipage/binary/instructions.html#variable-instructions

I see something like this in either Chrome or in Safari

<img width="960" alt="screen shot 2018-02-15 at 22 51 19" src="https://user-images.githubusercontent.com/2205845/36277734-c56c4e40-12a2-11e8-8864-349029cf1296.png">

**Comment by rossberg** [comment]
Fixed.
