### ISSUE TITLE
[interpreter] Is there a way to produce static or dynamic library for interpreter?

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/spec#699]
I don't know much about ocaml and my initial shallow search led me to nowhere. 

But I'm wondering, can I produce static or dynamic library for spec interpreter?
I'm asking because fuzzing against spec interpreter sounds like a good idea, but seems like spawing spec interpreter as a process on each iteration is not very efficient

**Comment by rossberg** [comment]
Hm, I have no idea. The first problem probably is: if you want to link against C then you have to go through Ocaml's foreign function interface. Other than that, I found [this](http://www.camlcity.org/knowledge/kb_002_shared_library.html), but no idea how difficult it would be to make that all work, especially across platforms.

But I don't see the problem with just starting the interpreter as a separate process. Startup is fast.

**Comment by pepyakin** [comment]
Yeah, I already spin up the fuzzing spawing interpreter as a separate process, and it already gave fruits (https://github.com/WebAssembly/wabt/issues/762)!
However, it seems to be very slow, like 100-50 iterations per second (comparing with 2000-3000 iterations with statically linked wabt).

**Comment by rossberg** [comment]
Is that due to start-up, though? Note that the interpreter is not written for speed at all, and in fact is extremely slow in places; on execution for example, due to the small-step reduction rules it implements verbatim to match the spec literally (but which results in quadratic runtime).

**Comment by rossberg** [comment]
Closing this. Please reopen if you think there is a concrete action we could take.
