### ISSUE TITLE
A few binary tests for reserved bytes

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/spec#700]
The following module are contains grow_memory, current_memory, call_indirect with reserved byte isn't equal to 0 (all in base64 encoding)

```
AGFzbQEAAAABBAFgAAADAgEABQMBAAAKCQEHAEEAQAEaCwAKBG5hbWUCAwEAAA
```

```
AGFzbQEAAAABBAFgAAADAgEABQMBAAAKBwEFAD8BGgsACgRuYW1lAgMBAAA=
```

```
AGFzbQEAAAABBAFgAAADAgEABAQBcAAACgkBBwBBABEAAQsACgRuYW1lAgMBAAA=
```

I'm wondering are you interested in adding these tests in binary.wast? If so, I could make a PR.

**Comment by rossberg** [comment]
Yes, definitely would be!
