### ISSUE TITLE
[spec] Difficulty understanding numerics: How does ibits^(-1) work?

### ISSUE THREAD

**Issue by jamesray1** [WebAssembly/spec#716]
https://webassembly.github.io/spec/core/exec/numerics.html

How does ibits^(-1) work?

**Comment by jamesray1** [comment]
Does it just invert the bits?

**Comment by binji** [comment]
`ibits` is a function that takes a number and produces a bit sequence. `ibits^-1` is the inverse operation, which takes a bit sequence and produces a number.

**Comment by jamesray1** [comment]
Ah OK, makes sense! It might be helpful if that explanation was added to https://webassembly.github.io/spec/core/exec/numerics.html#aux-ibits.

**Comment by binji** [comment]
The `^-1` part is described at the top of that page in the "conventions" section:

> The notation f^−1 denotes the inverse of a bijective function f.

It is used for other functions as well. `signed^-1`, for example.

I agree that mentioning bit sequences in the ibits section would be a bit clearer, though.

**Comment by jamesray1** [comment]
Admittedly, I probably should've realised what it meant. f^-1 is standard notation.
