### ISSUE TITLE
[interpreter] Checking of labels types for br_table doesn't match with spec

### ISSUE THREAD

**Issue by SPY** [WebAssembly/spec#718]
Hi.
Could you help me to figure out am I wrong or an interpreter is not enough strict.
If we look to the spec for [br_table validation](https://webassembly.github.io/spec/core/valid/instructions.html#valid-br-table) we can see two rules:
* For all li in l∗, the label C.𝗅𝖺𝖻𝖾𝗅𝗌[li] must be defined in the context.
* For all li in l∗, C.𝗅𝖺𝖻𝖾𝗅𝗌[li] must be t?.

I understand them as labels have to be defined in context and have the same type as default label. So, if default label has value i32 all labels have to have the same, not empty.
But if we look in the interpeter we can [see](https://github.com/WebAssembly/spec/blob/master/interpreter/valid/valid.ml#L209) label types are checked with `check_stack` predicate.
`List.iter (fun x' -> check_stack (known ts) (known (label c x')) x'.at) xs;`
That predicate is used for more purposes and it too week for this case, because it checks types on equality only if both of them defined, but if at least one of them is None, then types are equal.
```
let eq_ty t1 t2 = (t1 = t2 || t1 = None || t2 = None)
let check_stack ts1 ts2 at =
  require (List.length ts1 = List.length ts2 && List.for_all2 eq_ty ts1 ts2) at
    ("type mismatch: operator requires " ^ string_of_infer_types ts1 ^
     " but stack has " ^ string_of_infer_types ts2)
```
And if it is error then [this function definition](https://github.com/WebAssembly/spec/blob/master/test/core/br_table.wast#L1215-L1231) in tests shouldn't be valid.

**Comment by binji** [comment]
> That predicate is used for more purposes and it too week for this case, because it checks types on equality only if both of them defined, but if at least one of them is None, then types are equal.

A label has the type `value_type list`. The `known` function lifts that to `value_type option list`, where it is never `None`. As described in [this comment](https://github.com/WebAssembly/spec/blob/master/interpreter/valid/valid.ml#L48-L55), the `None` value is used for unknown types (when handling polymorphic type checking, after a `br`, `br_table`, `return` or `unreachable` instruction.)

> And if it is error then this function definition in tests shouldn't be valid.

That test is valid because the `(result i32)` defines the `loop`'s result type, but the `br_table` target branches to the top of the loop, which has type `[]`. Another way of thinking of it is that the loop has type `[] -> [i32]`.

**Comment by SPY** [comment]
But then I do not understand why each label has concrete(non-empty) return type. I guessed if result type is omitted then block(and label) has empty result type. So in test example
```
      (loop (result i32) ;; has type [] -> [i32]
        (block ;; has type [] -> []
          (br_table 1 (; refs outer block ;) 0 (; refs inner block ;) 0 (; refs inner block as default ;) (get_local 0))
        )
        (i32.const 0)
      )
```
types of labels are different. Do I miss something?

**Comment by SPY** [comment]
I've finally figure out my problem :)
I misread the spec. I didn't spot first line of description for `loop` and `block` are different.
For loop:
```
Let C′ be the same context as C, but with the empty result type [] prepended to the 𝗅𝖺𝖻𝖾𝗅𝗌 vector.
```
But for block:
```
Let C′ be the same context as C, but with the result type [t?] prepended to the 𝗅𝖺𝖻𝖾𝗅𝗌 vector.
```
Only after 10 reading of @binji I got the point. Thank you
