### ISSUE TITLE
fdivN arguments order

### ISSUE THREAD

**Issue by franky47** [WebAssembly/spec#721]
The documentation for `fdivN`​ states:
```
4.3.3.6. fdivN​(z1​,z2​)
...
Else return the result of dividing z2​ by z1​ , rounded to the nearest representable value

...  floatN​(z1​/z2​)​​
```
There is a discrepancy in the description, it should read:
```
Else return the result of dividing z1 by z2​ , rounded to the nearest representable value
```

Source: https://www.w3.org/TR/wasm-core/#-href-exec-numericshtmlop-fdivmathrmfdiv_n-z_1-z_2

**Comment by rossberg** [comment]
Thanks, fixed in #722.
