### ISSUE TITLE
[spec review] Web API 

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/spec#731]
Detail oriented review of draft text:
https://webassembly.github.io/spec/web-api/index.html

Please try to be ready to discuss issues by the in person spec meeting.

**Comment by erights** [comment]
Given the JS API it build on, LGTM.

I like having a "Developer-Facing Display Conventions" section (and I like the particulars in this section). Is this section normative? Noting that tc39 perhaps should consider such sections for EcmaScript, though probably in non-normative text. Perhaps even separate from the spec, but representing general agreement.

**Comment by littledan** [comment]
That section relates to things that aren't really written about in any other specification that I know of. It's a good question whether it's really normative or not. Unlike the ECMAScript specification, which has many introductory sections that are considered "obviously" non-normative, web specs tend to explicitly note whether text is normative or not. This text is not noted as non-normative, but I'm not sure what it would really mean given the lack of specs to hook into. Do you think it should be marked as non-normative given tat?

**Comment by erights** [comment]
Yes, I do think it should be marked as non-normative. I also think that tc39 should have similar non-normative treatments of Developer-Facing Display Conventions.

**Comment by lukewagner** [comment]
Random nit I noticed in the Developer-Facing Display Conventions section: there is an unprocessed `[="name" section=]`

**Comment by binji** [comment]
It sounds like the issues were resolved here, closing.
