### ISSUE TITLE
"Name" section should allow names for globals/tables/memories

### ISSUE THREAD

**Issue by NWilson** [WebAssembly/spec#736]
Currently, the names section only allows naming the module, functions, and locals.

It should allow for naming globals, or debuggers won't be able to attach friendly names to the globals being accessed.

I suppose tables and memories should probably allow naming as well, although it's less likely in practice that there'll be more than one of those.

**Comment by AndrewScheidecker** [comment]
I have a pending pull request that supports round-tripping all the names in the text format through the names section: https://github.com/WebAssembly/design/pull/1064

**Comment by NWilson** [comment]
Aha, thanks! I was looking in the wrong repo there.

**Comment by rossberg** [comment]
Closing this, given its a feature request and there is WebAssembly/design#1064.
