### ISSUE TITLE
Parse error w/ flat call_indirect

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#737]
The following .wat file doesn't parse:
```
(table 1 anyfunc)
(func
  i32.const 0
  call_indirect)
```

It seems that this rule is the problem, requiring a following `instr`:
```
call_instr_results :
  | LPAR RESULT value_type_list RPAR call_instr_results
    { fun c -> let ts, es = $5 c in $3 @ ts, es }
  | instr
    { fun c -> [], $1 c }
```

Changing it to `/* empty */ { fun c -> [], [] }` introduces shift/reduce conflicts.

**Comment by rossberg** [comment]
Aw, frack. If only we had never introduced the flat syntax. Or yacc was LR(2). See #738 for the fix.

**Comment by binji** [comment]
This was fixed in https://github.com/WebAssembly/spec/pull/738.
