### ISSUE TITLE
[test] Make test suite "section" comprehensive

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/spec#739]
At various points, we've talked about making our test suite explicitly cover each point in the written spec.
ECMAScript's Test262 could serve as a model, wherein each test has a crisp correspondence with spec sections.
While our current coverage is good, something like this might be better.
However, this area would need a strong champion.

**Comment by littledan** [comment]
I plan to help out with this for the JS API and Web API specifications, but at the same time my work on Wasm is less that one day a week. If anyone else wants to pitch in, we could divide up the work and make faster progress. I believe there are a number of coverage gaps in the JS and Web APIs.

**Comment by rossberg** [comment]
Just to make sure that we're all on the same page: I assume we are talking about improving coverage such that every section is covered, potentially adding specific test cases per section? I hope we are not talking about physically organising the test suite in the style of Test262, where every test must be a micro test that lives in its own file.

**Comment by eholk** [comment]
I put together a document to start doing an inventory of the tests we have to give us an idea of where we need to focus more effort:

https://docs.google.com/document/d/1cEdT_S_Ijfu5Ur-TVttlckALFznn56K5ZTsvkIdy2bg/edit?usp=sharing

We have at least some coverage for the whole JS API as far as I could tell. I expect there are a lot of more detailed tests that are needed though. Mining the different engines' unit tests can shed some light here.

I didn't find any tests in the spec repo for the web embedding, but there are a couple in Chromium that should be pretty easy to import.

**Comment by littledan** [comment]
cc @ms2ger

**Comment by littledan** [comment]
There are a number of tests for the web embedding in [Web Platform Tests](https://github.com/w3c/web-platform-tests/tree/master/wasm). I'm not sure it makes sense to put more of those tests in the spec repository, as it will likely be an extra source of difficulty to get them running in web browsers. Maybe we should even move [the IndexedDB web-platform-test](https://github.com/WebAssembly/spec/blob/master/test/html/indexeddb.js) to wpt (or delete it if it's equivalent to the tests already there).

**Comment by eholk** [comment]
We've had a lot of discussion around this, so I may be off on the final decision (if there was one), but I think where we settled is that the Wasm spec repo would own its own tests and we'd set up one way sync to automatically move Wasm tests into the WPT repo.

**Comment by binji** [comment]
current status: @Ms2ger has significantly improved the JS testsuite. It is organized by exposed interfaces (`Memory`, `Table`, etc.) and their methods (`Memory.grow`, etc.)

There are currently no web-api tests.

**Comment by Ms2ger** [comment]
My understanding was that there was no interest in importing the web-api tests into this repo, because they can only be used by web browsers anyway.

**Comment by binji** [comment]
Oh, I see. I didn't follow along with the testing discussion closely enough, I suppose. :-)

In any case, this issue is unrelated -- we can decide to import the web tests or not, but how the testsuite should be organized is already done. So I think it's fine to close this.
