### ISSUE TITLE
`div_s` execution semantics invalid?

### ISSUE THREAD

**Issue by ehildenb** [WebAssembly/spec#742]
The `div_s` execution semantics seem to lead to invalid behaviour (file https://github.com/WebAssembly/spec/blob/master/document/core/exec/numerics.rst).

Take for example, that `i = 32`, `i_1 = (2 ^ 31) + 15`, and `i_2 = 7`.
The following script (which can be piped into command-line calculator `bc`) demonstrates that we are asked to calculate `signed^{-1}` of a number that is not in the range of `signed` (and thus not in the domain of `signed^{-1}`, since `signed` is bijective).

[bc-script.txt](https://github.com/WebAssembly/spec/files/1783639/bc-script.txt)

I think the issue is in the last line, inside the call to `signed^{-1}`, the *unsigned* values `i_1` and `i_2` appear, where perhaps the *signed* values `j_1` and `j_2` should appear.

**Comment by rossberg** [comment]
I suppose you  meant rem_s not div_s? In that case I agree, there was a typo, missing the signed around the other occurrences of i_1 and i_2. Fixed in #743.

Thanks!

**Comment by ehildenb** [comment]
Yes, thanks, `rem_s`, not `div_s`.
