### ISSUE TITLE
Interpreter doesn't validate "unused" bits terminal byte in varint

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#746]
See https://github.com/WebAssembly/wabt/issues/799.

I belive the encoded value `0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0xff 0x7e` is not valid as a 64-bit signed varint, as the value it is decoded to, 9151314442816847872, should be encoded as `0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0xff 0x00`, where the top bits of the last byte are a sign-extension of the sign bit (the least-significant bit).

**Comment by binji** [comment]
cc @rossberg, am I misunderstanding the spec here? v8's implementation at least matches this behavior.

**Comment by rossberg** [comment]
No, this is indeed a bug in the interpreter, the shift for the mask it used was off by one. Fixed in #750, with a range of new binary tests for LEB encodings. PTAL
