### ISSUE TITLE
Semaphore on webassembly

### ISSUE THREAD

**Issue by z--z---z-----** [WebAssembly/spec#747]
Hi,

What instruction will be used in order to create a semaphore.
I am unable to find a "test and set" type of instruction that normally are provided by CPUs to help on semaphore creation.

Thanks

**Comment by rossberg** [comment]
Version 1.0 of Wasm does not have support for threads. This will come with the [proposed threading extension](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md), which incorporates atomic compare/exchange instructions.
