### ISSUE TITLE
LegacyNamespace should not be used

### ISSUE THREAD

**Issue by dontcallmedom** [WebAssembly/spec#753]
per https://heycam.github.io/webidl/#LegacyNamespace

not sure if WebIDL [`namespace`](https://heycam.github.io/webidl/#dfn-namespace) matches what is wanted here

**Comment by annevk** [comment]
Pretty sure if you look at the history this was added for WebAssembly, but we didn't want others to follow the precedent set by WebAssembly.

**Comment by littledan** [comment]
Yeah, unfortunately we can't change the naming due to compatibility at this point.
