### ISSUE TITLE
[spec] Debuggability as design goal

### ISSUE THREAD

**Issue by liminzhu** [WebAssembly/spec#759]
In [design goals](http://webassembly.github.io/spec/core/bikeshed/index.html#design-goals①) in core spec, 

`WebAssembly code is also intended to be easy to inspect and debug, especially in environments like web browsers, but such features are beyond the scope of this specification.`

Do we consider this out of scope for the spec? Text format is for that purpose and is defined in the core spec.

**Comment by rossberg** [comment]
Well, the text format of course is a sort of prerequisite for debugging, but I wouldn't consider it a debugging aid per se (it has other uses, too). This sentence was meant to clarify that this spec doesn't define things like stack traces, break points, or other sorts of debugging interfaces.

**Comment by liminzhu** [comment]
This makes sense. Thanks for the explanation.
