### ISSUE TITLE
[js-api] "Creating a host function" requires a functype parameter

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#768]
The algorithm to create a host function uses the function's type:

* in step 1.1 implicitly as "the signature",
* in step 1.6 as |functype|.

However, that type is not actually provided. The algorithm needs to take |functype| as a parameter.

**Comment by littledan** [comment]
This is actually fixed only in 24e291c cc @Ms2ger

**Comment by littledan** [comment]
That patch landed too, so closing.
