### ISSUE TITLE
[js-api] Incorrect record-like access

### ISSUE THREAD

**Issue by binji** [WebAssembly/spec#774]
See here: https://github.com/WebAssembly/spec/blob/833db0f2d7cbae4b9ac371ce14641096f6ee94c3/document/js-api/index.bs#L333

`globaltype` is not a record, so the `.` syntax is not quite right. Instead it should be destructured (similar to the previous lines: `If |externtype| is of the form [=𝗀𝗅𝗈𝖻𝖺𝗅=] |globaltype|`)

**Comment by binji** [comment]
cc @littledan

**Comment by littledan** [comment]
Thanks, this sounds right, will fix.

**Comment by binji** [comment]
Looks like this was fixed with the mutable global merge.
