### ISSUE TITLE
[web-api] Download failure + lazy validate

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/spec#793]
The core spec allows for validation + compilation of functions to happen lazily:
http://webassembly.github.io/spec/core/bikeshed/index.html#validation%E2%91%A3

It just occurred to me that implementations that are lazy like Edge might similarly want defer handling of download failures to function invocation when implementing instantiateStreaming.

Michael, does Edge do / plan to do anything like that?
(I.e. do you return from instantiateStreaming before download is complete?)

We could always allow more implementer freedom later if this isn't currently a compat issue, but figured I should check.

**Comment by MikeHolman** [comment]
We have discussed this idea, but I don’t really think we want to do it (at least not by default), since latency for calling a function that hasn’t been downloaded could be extreme.

**Comment by littledan** [comment]
OK, sounds like there is nothing to do here, is that right?

**Comment by binji** [comment]
No discussion since June, so closing.
