### ISSUE TITLE
Are block labels supported?

### ISSUE THREAD

**Issue by ColinEberhardt** [WebAssembly/spec#796]
ref: https://github.com/xtuc/webassemblyjs/issues/277 - I am struggling to make block labels work.

The spec indicates that [blocks can have an optional label](https://webassembly.github.io/spec/core/text/instructions.html#control-instructions), and that `br` / `br_if` instructions may use a label or index. 

Here's a simple function that counts to twenty:

```
(func $count 
  (local $x i32)
  (set_local $x (i32.const 0))

  (block 
    (loop 
      (call $log
        (get_local $x)
      )
      
      (set_local $x
        (i32.add 
          (get_local $x)
          (i32.const 1)
        )
      )
      ;; loop for 20
      (br_if 1 (i32.eq (get_local $x) (i32.const 20)))
      (br 0)
    )
  )
)
```

This works just fine. 

My expectation is that the `br_if` instruction can reference the block by name rather than depth. For example:

```
(func $count 
  (local $x i32)
  (set_local $x (i32.const 0))

  (block $myblock       <---------
    (loop 
      (call $log
        (get_local $x)
      )
      
      (set_local $x
        (i32.add 
          (get_local $x)
          (i32.const 1)
        )
      )
      ;; loop for 20
      (br_if $myblock (i32.eq (get_local $x) (i32.const 20)))  <---------
      (br 0)
    )
  )
)
```

However this doesn't work.

I've been looking at the spec test suite and can only see one block with a label, but it is unused:

https://github.com/WebAssembly/testsuite/blob/master/block.wast#L9

I'd appreciate some help, or a working example :-)

**Comment by xtuc** [comment]
https://github.com/WebAssembly/design/pull/1064 includes it

**Comment by rossberg** [comment]
What do you mean by "this doesn't work"? The labeled version of your code should work fine, and does in the reference interpreter. What tool were you using?

There are plenty of uses of labels in the test suite, see e.g. [labels.wast](https://github.com/WebAssembly/spec/blob/master/test/core/labels.wast) or [stack.wast](https://github.com/WebAssembly/spec/blob/master/test/core/stack.wast).

**Comment by ColinEberhardt** [comment]
Thanks @rossberg - I've narrowed things down a bit. I'm using the WeAssembly build of wabt:

```
const wasmModule = wabt.parseWat(inputWat, readFileSync(inputWat, "utf8"));
const { buffer } = wasmModule.toBinary({ write_debug_names: true });
```

Which is giving the following error:

```
CompileError: WasmCompile: Compiling wasm function #1:count failed: invalid break depth: 1652124964 @+82
```

Whereas, compiling the same file with `wat2wasm --debug-names` works just fine. However, I have noticed that the block label `myblock` does not appear in the custom name. 

Anyhow, closing this issue :-)

**Comment by ColinEberhardt** [comment]
Thanks @xtuc that explains why I'm not seeing the labels in custom name section. Anyhow, I'll investigate that compiler error to see if I can find the root cause.

**Comment by binji** [comment]
@ColinEberhardt yeah, I believe someone else ran into the same issue recently. You have to call `resolveNames` for this to work. It seems there should be a better error for this (currently I think it's just an assertion).
