### ISSUE TITLE
section() in binary format chapter links to wrong definition

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/spec#797]
Currently clicking on section<sub>N</sub>(...) links to  binary/modules.html#sections when I think instead it should link to binary/modules.html#sections.

Also, a formatting nit: even in the MathJax version, the N of section<sub>N</sub> seems too close to the "section".

**Comment by rossberg** [comment]
Thanks, fixed link. The spacing seems correct on Chrome. I assume you tried FF? Are they rendering it the same on your machine?

**Comment by ericprud** [comment]
@lukewagner, can you say how to reproduce the spacing problem and close this issue?

**Comment by lukewagner** [comment]
(Oops, sorry for missing the reply.)  Looks like a FF issue; the MathJax looks fine on Chrome and matches the W3C HTML and PDF.  The W3C HTML looks fine on FF, though, and this is really only a few pixels on FF for the MathJax, so it's probably not worth spending any time on.
