### ISSUE TITLE
Any intention add fp16 & i16 native support in webassembly?

### ISSUE THREAD

**Issue by lygstate** [WebAssembly/spec#804]
As fp16 are broadly used in nowadays, and i16 is something corresponding to i16. So I suggest add these two type as native support in webassembly. Anyway, i8 seems not necessary, but i16 somewhat are necessary for fp16

**Comment by jfbastien** [comment]
fp16 is supported in two broad manners on some HW: some only support it as a storage type (widen loads to 32 or 64, and narrow stores, with all arithmetic in 32 or 64), whereas some architectures also support 16-bit arithmetic. To move any fp16 proposal forward, it would be useful to have a survey of relevant architectures and what they support. When considering arithmetic, it's further useful to understand if full IEEE 754 is supported.

**Comment by lygstate** [comment]
Yeap, for some target such as MCU they only have i16 support. does i16 are necessary?

**Comment by jfbastien** [comment]
I don't think i16 is necessary: we can expand any f16 conversion to i32 or i64, and do arithmetic on those types.

**Comment by AhliLi** [comment]
i|f bitscope is critical for optimization & range profiling.

**Comment by lygstate** [comment]
We can use i16 as bitwise representation of fp16.

**Comment by vshymanskyy** [comment]
My opinion on the topic: https://github.com/WebAssembly/spec/issues/899#issuecomment-578108626

**Comment by rossberg** [comment]
Closing. Please create a proposal if you want to see this feature in future Wasm.
