### ISSUE TITLE
js api: improve definition of error objects

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#810]
There's `[LegacyNamespace=WebAssembly] interface CompileError { };` and then a bunch of prose requirements on the objects that are constructed because of that IDL. AFAICT the only thing that the IDL is supposed to do is define that the namespace object has properties called `FooError`. Let's just do that manually and avoid the conflict?

**Comment by ericprud** [comment]
@Ms2ger , can you see if this has been addressed and close this issue if not?

**Comment by Ms2ger** [comment]
There has been no attempt to address this.

**Comment by Ms2ger** [comment]
I'm working on it.
