### ISSUE TITLE
Default value in constructor of Global

### ISSUE THREAD

**Issue by dontcallmedom** [WebAssembly/spec#816]
The current definition of the constructor for `Global` uses a default value for the 2nd argument:
  `Constructor(GlobalDescriptor descriptor, unrestricted double value = 0)`

AFAIU, default values can only be used with optional arguments - so I think `value` should be marked as `optional`.

**Comment by rossberg** [comment]
Actually, I think there is another problem here, namely that the type of the value depends on the descriptor. In the future, it might denote a non-numeric type, so double is not adequate. It should probably be `any` and default to `undefined`.

**Comment by binji** [comment]
@rossberg That's a good point, but we discussed in the meeting having globals of the numeric types default to 0. So I suppose we need to handle it specially in the constructor's algorithm.

**Comment by binji** [comment]
Fixed in #818.
