### ISSUE TITLE
GlobalDescriptor::value is an odd name

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#852]
It can accept the values "i32", "i64", "f32" and "f64". This sounds more like something that should be called "type" or something along those lines.

(Also, it could be a [WebIDL enumeration](https://heycam.github.io/webidl/#idl-enums).)

**Comment by rossberg** [comment]
See [this issue](https://github.com/WebAssembly/mutable-global/issues/16) for context, and the [notes of the May 15 meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-05-15.md).

**Comment by ericprud** [comment]
Does the CG decision referenced in [binji's comment](https://github.com/WebAssembly/mutable-global/issues/16#issuecomment-389234666) close this issue?

**Comment by binji** [comment]
Yes, closing.

**Comment by xtuc** [comment]
We discussed about the name of the field.

I would be in favor of switch it to a enumeration ('i32', 'i64', 'f32', or 'f64') of value types (as @rossberg mentioned). I would be happy to bring that up in the next meeting.
