### ISSUE TITLE
use hot(0xflags,, priority, id, {var,} ) as compiler directive profile

### ISSUE THREAD

**Issue by AhliLi** [WebAssembly/spec#863]
use HOT as compiler directives and profile hints for efficient prioritisation.

flags: first bits should indicate
{ start/stop directive, linear sequence, iterator loop, parallel, parallel^, thread synch, (calls function), and optimisation profile (standard pattern)}
float priority: 1.0f typical, sorted by compiler
id: <></>

optional variable / register declarations

Also wise to include numeric scope for higher efficiency processing of fixed bit scope, io profile for gl and audio/video, hints on endpoint optimisation (pixel buffer, audio, webgl, etc.)

**Comment by rossberg** [comment]
Closing, since you already opened a duplicate in the design repo.

**Comment by AhliLi** [comment]
Spec TXT link is not design link in docs, also w3c working group link is bad
