### ISSUE TITLE
Typo: n -> m

### ISSUE THREAD

**Issue by Ekleog** [WebAssembly/spec#886]
In [§4.4.7.2](https://webassembly.github.io/spec/core/bikeshed/index.html#returning-from-a-function%E2%91%A0), I think the number of values popped then pushed should be `m`: the number of return values, and not the number of argument values.

Am I correct?

**Comment by Ekleog** [comment]
Oh indeed, thanks! well, then suggestion: rename this `n` to a `m`, because changing the variable name at paragraph change is confusing, I being an example of its confusingness :)

**Comment by binji** [comment]
I think changing this case is fine, but this isn't an isolated case -- many places in the spec use the same variable name for different purposes. I'm curious if you found other places in the document where this was confusing.
