### ISSUE TITLE
Relicense  test/js-api/limits.js

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#890]
@titzer could you please relicense the test, or explicitly state that you're fine with doing that, so I can submit it into wpt?

Target license is https://github.com/web-platform-tests/wpt/blob/e048b62ee65e141c8e5a1e621fae41f1e7dd0a37/LICENSE.md.

**Comment by binji** [comment]
ping @titzer

**Comment by ericprud** [comment]
@binji , @Ms2ger , @titzer , I see these were merged. Do they have the license commitment? If so, please close this issue.
