### ISSUE TITLE
[interpreter] No support for custom sections

### ISSUE THREAD

**Issue by nomeata** [WebAssembly/spec#895]
The WebAssembly standard allows for custom named sections, but the reference interpretation does not seem to include this possibility in its AST or decoder.

I would expect something esesntially like
```
type module_ = module_' Source.phrase
and module_' =
{
  …
  custom_sections : (name * string)  list;
}
```
(with possibly a proper record and use of `Source.phrase`).

**Comment by rossberg** [comment]
This design is intentional, since the AST is supposed to mirror the spec. Note that custom sections are  a feature of the binary format, not the abstract syntax. Among other things, they don't have any representation in the text format (although the annotations proposal adds an analogue).

**Comment by nomeata** [comment]
Interesting point. I also learned since that custom sections can simply be appended to the binary format, so at least for encoding the lack of AST support in the library is less of a hurdle than I thought initially.
