### ISSUE TITLE
[bikeshed] Incorrect links in footnotes

### ISSUE THREAD

**Issue by jmdejong** [WebAssembly/spec#896]
On several occasions in [the single-page specification](https://www.w3.org/TR/wasm-core-1/) the links from the footnotes pointing back to their location in the text point to the wrong id.
For example in the [footnote about the stack machine](https://www.w3.org/TR/wasm-core-1/#stackmachine) the link that is supposed to take you back to where you were instead takes you to the [mention of memory safety](https://www.w3.org/TR/wasm-core-1/#id2), which is actually the link target for another footnote.
This was tested in Firefox 62.0.3

I believe the cause of this is that the document was designed for a multi-page view, and therefore the ids that are being linked to are automatically generated, but with the same name.

A possible solution could be to prefix these ids with the section name when combining them into the single-page version.

**Comment by binji** [comment]
This seems to be a [sphinx bug](https://github.com/sphinx-doc/sphinx/issues/4814).

**Comment by rossberg** [comment]
Closing, since it needs to be fixed on the Sphinx side.
