### ISSUE TITLE
[jsapi] Inconsistency with custom section decoding 

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#914]
This isn't really an issue, just seems inconsistent with the Module decoding semantics.

The JS spec specifies that `WebAssembly.Module.customSections` throws when a decoding error has been encountered in the name, see https://webassembly.github.io/spec/js-api/index.html#dom-module-customsections.

I had in mind that failing to decode a custom section should be ignored.

However, this API is used to search for a specific section.

**Comment by xtuc** [comment]
After thinking more about that, I guess it's fine, closing for now.

**Comment by littledan** [comment]
Yes, I agree that this shouldn't be changed. Note that the contents of the custom section are not verified.
