### ISSUE TITLE
Running interpreter's 'winmake.bat' does not produce 'wasm.exe'

### ISSUE THREAD

**Issue by anurse** [WebAssembly/spec#917]
Prereqs: 
* Windows Machine
* Install OCaml

**Repro Steps**:
1. Clone this repo
2. `cd interpreter`
3. `winmake.bat`

**Expected Behavior**: `wasm.exe` is dropped in the current directory

**Actual Behavior**: No `wasm.exe` is dropped. The `-o` switch in the final OCaml build instruction has `main/main.d.byte` in it. Renaming this file to `wasm.exe` results in a working interpreter.

**Comment by anurse** [comment]
It does produce an exe now, thanks! It's called `main.exe`, but that's fine with me.

**Comment by rossberg** [comment]
Oops, name corrected.
