### ISSUE TITLE
Unknown import "env"."enlargeMemory"

### ISSUE THREAD

**Issue by ireneGP** [WebAssembly/spec#919]
Hello,

I followed the dev guide (https://webassembly.org/getting-started/developers-guide/) to compile a hello world program into `.wasm` file, and then tried to use `wasm` to interpret the binary code.  

However, it seems that some contexts are not well configured. 

````
➜  interpreter git:(master) ./wasm ~/work/code/wasm/test_code/hello.wasm
/home/irene/work/code/wasm/test_code/hello.wasm:0x72-0x86: link failure: unknown import "env"."enlargeMemory"

````

Could anyone shed some lights on this? Thanks.

**Comment by xtuc** [comment]
What's the `./wasm` executable you are using?

**Comment by ireneGP** [comment]
I use the latest version from the github, commit at #e8222139162103144ff526303.

**Comment by rossberg** [comment]
The "env.*" imports are generated by Emscripten and provided by Emscripten's JS glue code to work on the Web. The reference interpreter doesn't know anything about them. It can only instantiate modules that do not have platform-specific imports.

**Comment by ireneGP** [comment]
@rossberg  I see the point here. Sorry I am a newbie to this filed. So according to my understanding, `wasm` code needs to leverages JS to use some system-related functionalities, like the `I/O` related operators.

In other words, I shouldn't be able to leverage the interpreter here to execute a simple "hello world" code right? Since even for such piece of code it needs to talk with the JS part and print out. Our task is that we have a bunch of webassembly produced by `C/C++`, and we were thinking to verify its functionality via this standard interpreter. So this conceptually shouldn't be viable, right?

**Comment by rossberg** [comment]
@ireneGP, yes that's right. The reference interpreter is intended for testing the execution of the Wasm instruction set itself. It is mostly useful for compiler and VM engineers, not so much for users of their tools.

**Comment by ireneGP** [comment]
@rossberg  I see. Thank you! Originally we were thinking to take the interpreter as an "oracle" to test our web assembly code base. Right now it seems that the only thing we can do is to setup some differential testing...
