### ISSUE TITLE
[spec] Can memory.grow take n < 0 ?

### ISSUE THREAD

**Issue by Centril** [WebAssembly/spec#924]
Reading the operational semantics of [`memory.grow`](http://webassembly.github.io/spec/core/exec/instructions.html#exec-memory-grow) it isn't clear whether you can shrink the amount of memory with that instruction (the meaning of "grow" and "append" isn't detailed but once can guess what it means...).

Similarly, reading [`growmem`](https://webassembly.github.io/spec/core/exec/modules.html#grow-mem) does not bring clarity; I didn't see the syntax `meminst.data (0x00)n⋅64Ki` defined anywhere; I assume it means that `meminst.data` is concatenated with `(0x00)n⋅64Ki` but it would be nice to make this clearer wrt. behavior and inductively define the operation `A B`.

cc https://github.com/rust-lang/rust/issues/56292
Some advice would be good. :)

**Comment by binji** [comment]
Runtime integer values are always stored on the execution stack unsigned, see the definition of Values [here](http://webassembly.github.io/spec/core/exec/runtime.html#values), which references the definition of integers [here](http://webassembly.github.io/spec/core/syntax/values.html#syntax-int):

> The latter class defines uninterpreted integers, whose signedness interpretation can vary depending on context. In the abstract syntax, they are represented as unsigned values. However, some operations convert them to signed based on a two’s complement interpretation.

You can see an example of this in the definition of [i32.gt_s](http://webassembly.github.io/spec/core/exec/numerics.html#op-igt-s).

> Where "added" works for both signed and unsigned integers, but "divided" does not specify if a signed / unsigned dive operation is performed.

The numerics in the formal syntax always use the standard mathematical syntax. Unsigned integer division, for example, is defined like [this](http://webassembly.github.io/spec/core/exec/numerics.html#op-idiv-u): `trunc(i1/i2)`

Similarly, none of the numbers in the formal definitions use modular arithmetic (you can see an example of how that would be specified in [i32.add](http://webassembly.github.io/spec/core/exec/numerics.html#op-iadd)) so  it is not possible for them to wrap around.

> I didn't see the syntax meminst.data (0x00)n⋅64Ki defined anywhere; I assume it means that meminst.data is concatenated with (0x00)n⋅64Ki but it would be nice to make this clearer wrt. behavior and inductively define the operation A B.

I don't see the definition of that either, though perhaps I missed it. It is indeed meant to be a concatenation.

**Comment by Centril** [comment]
@binji Thanks for the details! :)

Perhaps [`meminst.data ++ (0x00)n⋅64Ki `](http://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#v:-43--43-) would be clearer?

**Comment by binji** [comment]
For this example, maybe, but this form of concatenation is used pervasively elsewhere in the spec (see the [binary section](https://webassembly.github.io/spec/core/binary/instructions.html#control-instructions) for example) where it would be visually very noisy to do this.

**Comment by Centril** [comment]
@binji ah; makes sense -- how about adding `A B` to the list of conventions somewhere instead?

**Comment by binji** [comment]
Sounds good to me, but I'll defer to @rossberg for that :-)

**Comment by Centril** [comment]
@rossberg I do think someone who is not familiar with reading literature on operational semantics could be confused so it seems noteworthy with a sentence somewhere. :) I understood what `A B` meant only from the context since it can also be function application in other contexts.

**Comment by binji** [comment]
Perhaps the formal semantics could be clearer, but I think the meaning of "grow" and "append" in the prose would have to be awkwardly contorted to allow shrinking. As described [here](https://webassembly.github.io/spec/core/exec/conventions.html) the purpose of the prose to provide the intuitive meaning, which seems to have been understood here.

Closing, but feel free to reopen if you feel strongly here.

**Comment by xtuc** [comment]
Now that we switched to the WebIDL specification, the {Table,Memory}.grow takes an unsigned 32 bits int.
