### ISSUE TITLE
Filename extension for S-expression test files

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#94]
The test files in ml-proto/test were originally name with a '.wasm' extension. However, we might expect .wasm to eventually be the filename extension for the official binary format. I propose we use '.wase' for the S-expression text format.

I accidentally committed a patch implementing this to master in be2b6ea5eefd338f647c5c698142492698644544 which renames the files to '.wase', rather than submitting a pull request. I'm happy to revert it, or I'm happy to submit a new patch using some other extension, following whatever consensus we get here.

**Comment by lukewagner** [comment]
Good point, this has been bugging me too for a while.  .wase sounds ok to me, although I would have gone with .wast (Wasm AST or WASm Test).

**Comment by rossberg-chromium** [comment]
I like .wast.

**Comment by sunfishcode** [comment]
'.wast' works for me. I submitted #100 to implement it.

**Comment by sunfishcode** [comment]
#100 is merged. Thanks!
