### ISSUE TITLE
Possible typo in fNmag definition.

### ISSUE THREAD

**Issue by hjorthjort** [WebAssembly/spec#956]
In syntax/values, there is the following definition of floating point numbers.

```tex
\production{floating-point magnitude} & \fNmag &::=&
  (1 + \uM\cdot 2^{-M}) \cdot 2^e & (\iff -2^{E-1}+2 \leq e \leq 2^{E-1}-1) \\ &&|&      [2nd line]
  (0 + \uM\cdot 2^{-M}) \cdot 2^e & (\iff e = -2^{E-1}+2) \\ &&|&                        [3rd line]
  \infty \\ &&|&
  \NAN(n) & (\iff 1 \leq n < 2^M) \\
\end{array}
```

The 2nd and 3rd line seem to have overlapping conditions, i.e., if `e = -2^{E-1}+2`, then it could be either normal or subnormal, which would cause trouble, since the leading 1 or 0 is implicit. I don't know the standard well enough to say if the 2nd line should use `<` instead of `\leq` for the lower bound, or the 3rd line should say `e = -2^{E-1}+1)`, but this seemed like a strange inconsistency to me.

**Comment by rossberg** [comment]
Ah, this is in fact explained in the note following the paragraph: this being abstract syntax, the distinction is made by the leading "1 +" vs "0 +"; the side conditions is merely limiting the value of e.

**Comment by hjorthjort** [comment]
Oh no, I missed the note. Sorry for that. Thanks for pointing it out.
