### ISSUE TITLE
[test] merge wasm-constants.js and wasm-module-builder.js

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/spec#958]
We merged wasm-constants.js and wasm-module-builder.js files together in v8 (https://chromium-review.googlesource.com/c/v8/v8/+/1446452).

Since those files are copied in this repo, for consistency, I would like to merge them here as well. However, some other projects might depends on one of the files independently.

Are people happy with that change?

cc @binji @hammacher @Ms2ger

**Comment by Ms2ger** [comment]
That makes sense to me. `wasm-module-builder.js` isn't usable without `wasm-constants.js` anyway.

**Comment by hammacher** [comment]
+1
