### ISSUE TITLE
Little endian?

### ISSUE THREAD

**Issue by digama0** [WebAssembly/spec#967]
According to 4.3.1 (p. 47), bytes are stored in little endian order, with the following definition:

    bytes_t(i) = littleendian(bits_t(i))
    littleendian(ep) = ep
    littleendian(d_1^8 d_2^(N-8)) = ibits_8^-1(d_1^8) littleendian(d_2^(N-8))

However, the definition of `ibits`:

    ibits_N(i) = d_(N-1) ... d_0   (i = 2^(N-1) * d_(N-1) + ... + 2^0 * d_0)

indicates that high order bits come at the left of the vector (low index), so that the decomposition in the definition of `littleendian` into the left 8 bits and the right N-8 bits would actually pull off the MSB and put it at the left end (low index), which corresponds to big endian byte order according to the wikipedia link. Assuming the spec actually means little endian byte order, one solution is to change the `littleendian` second clause to:

    littleendian(d_1^(N-8) d_2^8) = ibits_8^-1(d_2^8) littleendian(d_1^(N-8))

Another possibility is that vectors are indexed starting from the right end. The `vec` section could probably be a bit clearer about this (in section 2.1.2 auxiliary notation or 2.1.3 vectors), but this seems unlikely.

**Comment by rossberg** [comment]
Indeed, you are right, see #968 for a fix.

**Comment by rossberg** [comment]
Fixed.
