### ISSUE TITLE
[test] uncovered edge cases

### ISSUE THREAD

**Issue by cdetrio** [WebAssembly/spec#974]
A comment in [test/Todo.md](https://github.com/WebAssembly/spec/blob/c8338e9b4a60edb431edba51a4e1a1617060c2e9/test/Todo.md) says tests should "either be specified in Semantics.md, have a link to an open issue/PR, or be obvious." Is there a policy elsewhere for including test cases in the suite?

I'm asking because we've ran into a number of bugs in various parser and interpreter implementations, even though the implementations were passing the full spec test suite. I also wanted to open this issue to start tracking them: https://github.com/go-interpreter/wagon/pull/93  https://github.com/go-interpreter/wagon/pull/104   https://github.com/yurydelendik/wasmparser.rs/pull/92 (and more I can dig up later).

**Comment by binji** [comment]
I don't think we have a more explicit policy for tests. The comment you mention sounds like it should be updated (we don't use Semantics.md anymore, for example).

That said, the tests you describe sound useful. Please feel free to open PRs to add them.

**Comment by ericprud** [comment]
@cdetrio , do you still expect to produce tests? Should this issue remain open?
