### ISSUE TITLE
[js-api] Review object caching

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#985]
See the discussion in https://github.com/WebAssembly/threads/pull/118

**Comment by Ms2ger** [comment]
The suggestion there seems to be that the spec requires that `postMessage` can produce an existing object in its deserialization. However, [the HTML spec doesn't support that](https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize):

> Set value to a new instance of the interface identified by interfaceName, created in targetRealm.

and the prose about `Module` agrees with that. (@binji added a test for this in https://github.com/web-platform-tests/wpt/pull/12488.)

In the existing spec, it seems like we only need to remove the following sentence from a note in js-api:

> This mapping is used to ensure that, for a given agent, there exists at most one JavaScript object for a particular WebAssembly address.

because it's not true.

The threads proposal will also need to be updated to take that into account.

**Comment by binji** [comment]
OK, this sounds good to me. Thanks for looking into it.

**Comment by littledan** [comment]
The analysis looks right to me; apologies for the confusion. @Ms2ger would you be interested in creating spec PRs and tests for this change?

**Comment by binji** [comment]
@Ms2ger ping

**Comment by Ms2ger** [comment]
Wrote some extra tests at https://github.com/web-platform-tests/wpt/pull/18590.
