### ISSUE TITLE
Appendix omission - `if` consumes an i32 from the stack

### ISSUE THREAD

**Issue by James0x57** [WebAssembly/spec#986]
On this page:
https://webassembly.github.io/spec/core/appendix/index-instructions.html

the `Type` definition for `if` here:
![image](https://user-images.githubusercontent.com/7545075/54388955-fc035580-466c-11e9-89a9-eecb932c3e9d.png)
should (I believe) indicate that it consumes an i32 from the stack.

Here's the line in the code:
https://github.com/WebAssembly/spec/blob/gh-pages/core/appendix/index-instructions.html#L125

Currently:
```html
<td><span class="math notranslate nohighlight">\([] \href{../syntax/types.html#syntax-functype}{\rightarrow} [t^\ast]\)</span></td>
```
should be:
```html
<td><span class="math notranslate nohighlight">\([\href{../syntax/types.html#syntax-valtype}{\mathsf{i32}}] \href{../syntax/types.html#syntax-functype}{\rightarrow} [t^\ast]\)</span></td>
```

🍻

**Comment by binji** [comment]
Thanks! Fix in #987.
