### ISSUE TITLE
"unreachable" vs "unreachable executed"

### ISSUE THREAD

**Issue by rianhunter** [WebAssembly/spec#991]
In select.wast

https://github.com/WebAssembly/spec/blob/master/test/core/select.wast#L208

The string being tested is "unreachable executed" but in other tests, e.g. unwind.wast, the string tested is "unreachable"

Should the string in select.wast be changed to "unreachable"?

**Comment by binji** [comment]
The interpreter emits "unreachable executed", but the `assert_trap` command only checks substring equality. It probably is better to be consistent, though. PR here: https://github.com/WebAssembly/spec/pull/992

**Comment by rianhunter** [comment]
Ah okay, my test runner does full string equality. I'll change that.

**Comment by rianhunter** [comment]
Seems like this was resolved, so I'll close here. Thanks for noticing.
