### ISSUE TITLE
Start function that traps after populating imported table

### ISSUE THREAD

**Issue by rianhunter** [WebAssembly/spec#993]
Found an interesting corner case.

If the start function results in the trap, the module is considered "uninstantiable". As far as I can tell, uninstantiable modules should not affect the store.

During instantiation, before the start function can be invoked, the elements and data must be initialized.

What should happen if a start function results in a trap, after an *imported* table has been populated with functions from the *local* module? I can't find anything about this in the spec. I see this:

https://github.com/WebAssembly/spec/blame/1443de9e303f54eab0b5dee6fa0d48ff89422f4b/document/core/exec/modules.rst#L736

But that can't be true, since you can't check if a start function will trap before invoking it, and the store must be mutated in order to invoke the start function.

**Comment by binji** [comment]
> All failure conditions are checked before any observable mutation of the store takes place.

That comment should probably be clarified. The formal definition above makes it clearer; the segments are bound-checked against the memory and table, and if they are in bounds the store is modified. After that, the start function is invoked. If it traps at this point, there is not a valid instance, but the store has already been modified.

**Comment by rianhunter** [comment]
But if external tables have been filled with function instances from an invalid module instance, won't the store be in an undefined state?

**Comment by binji** [comment]
Only to the same extent that it would be if you call any function and trap. It's certainly an odd case, but it doesn't break the semantics since the module has already been validated.

**Comment by rianhunter** [comment]
I see, so the module stays allocated / referenced somewhere. I was assuming that not being a valid instance implied the module instance would be deallocated. Got it, thank you very much.

**Comment by rianhunter** [comment]
For reference here is a test that shows the case I'm talking about:

```
(module $Mt
  (type (func (result i32)))

  (table (export "tab") 1 funcref)

  (func (export "call") (param i32) (result i32)
    (call_indirect (type 0) (local.get 0))
  )
)
(register "Mt" $Mt)
(assert_trap (invoke $Mt "call" (i32.const 0)) "uninitialized")

(assert_trap
  (module
    (table (import "Mt" "tab") 1 funcref)
    (func $f (result i32) (i32.const 0))
    (elem (i32.const 0) $f)
    (func $main (unreachable))
    (start $main)
  )
  "unreachable"
)
(assert_trap (invoke $Mt "call" (i32.const 0)) "uninitialized")
```

**Comment by binji** [comment]
Yes, I just added a similar test here: https://github.com/WebAssembly/spec/pull/994

**Comment by rianhunter** [comment]
Awesome, thanks Ben

**Comment by rianhunter** [comment]
New question, let's say the invalid module was given a name. Should it be possible to invoke functions on it?

```
(assert_trap
  (module $Gt
    (func $f (result i32) (i32.const 0))
    (export "f" (func $f))
    (func $main (unreachable))
    (start $main)
  )
  "unreachable"
)

;; (assert_trap (invoke $Gt "f") "????")
;; or
;; (assert_return (invoke $Gt "f") (i32.const 0))
```

**Comment by binji** [comment]
The reference interpreter doesn't allow it. And I think that makes sense; the embedder should be communicating with the wasm core through the [embedding API](http://webassembly.github.io/spec/core/appendix/embedding.html), and the [`instantiate_module` function](http://webassembly.github.io/spec/core/appendix/embedding.html#embed-instantiate-module) returns an error (and no instance) if it fails.

**Comment by rianhunter** [comment]
Okay, so this is a bit nuanced. Even though `instantiate_module` returns no instance because the start function trapped, if the instance is valid and filled the store with its own functions, the instance is still allocated somewhere and referenced from the store, correct?

**Comment by binji** [comment]
As far as the core spec is concerned, that's not necessary. An [instance](http://webassembly.github.io/spec/core/exec/runtime.html#syntax-moduleinst) contains references to other entities in the store, it doesn't own those entities.

**Comment by rianhunter** [comment]
Crystal clear, thank you.

**Comment by rianhunter** [comment]
Sorry Ben, I just realized something. If the function instance is still active in the store, then the module instance must still be allocated, since function instances contain references to the module instance from which it originated. So even if `instantiate_module` returns no module instance during a start trap, it still must be allocated somewhere.

**Comment by binji** [comment]
Yes, I see what you mean. So yes, the module instance does need to be kept around.
