### ISSUE TITLE
Potentially incorrect definition of formal trunc

### ISSUE THREAD

**Issue by rianhunter** [WebAssembly/spec#996]
As far as I understand the abstract truncation function, it works like this:

```
trunc(q) = sign(q) * floor(abs(q))
```

This seems consistent with how various numeric instructions are tested in the spec tests. The definition provided by the spec doesn't quite seem to match this:

https://github.com/WebAssembly/spec/blame/8059cd6a68e9c8b874844051596fe1e0158eee91/document/core/exec/numerics.rst#L57

According to that definition, it seems like `trunc(-0.5)` would evaluate to `-1`. Is there something I'm missing?

**Comment by rossberg** [comment]
I believe the definition is correct. Note that _q_ ranges over unsigned rationals, i.e., the abs is not needed. For your example, _q_ would be 0.5 and the only natural number _i_ in the range between 0.5-1 and 0.5 is 0. So the definition would produce -0, i.e., 0.

**Comment by rianhunter** [comment]
I see now

https://github.com/WebAssembly/spec/blame/8059cd6a68e9c8b874844051596fe1e0158eee91/document/core/exec/numerics.rst#L49

`q` is a metavariable that represents the magnitude of the float. Sorry about that
